[gtk]
icons = "Arc"
theme = "Arc-Lighter"

[desktop]
wallpaper = "$HOME/dotfiles/wallpapers/sea.jpg"

[apps]
term = "ghostty"
launcher = "vicinae"

[theme]
font = "Fira Code 10"
background = "#1c1e26"
foreground = "#cbced0"
text = "#1c1e26"
cursor = "#cbced0"
black = "#1c1e26"
red = "#e95678"
green = "#29d398"
yellow = "#fac29a"
blue = "#268bd2"
magenta = "#ee64ac"
cyan = "#59e1e3"
white = "#cbced0"
light_black = "#6f6f70"
light_red = "#fab795"
light_green = "#232530"
light_yellow = "#2e303e"
light_blue = "#9da0a2"
light_magenta = "#dcdfe4"
light_cyan = "#f09383"
light_white = "#e3e6ee"

[theme.icons.battery]
charging = ""
empty = ""
quarter = ""
half = ""
three_quarter = ""
full = ""

[theme.icons.volume]
zero = ""
low = ""
high = ""
muted = ""

[theme.icons.brightness]
default = ""

[theme.icons.workspace]
1 = ""
2 = ""
3 = ""
4 = ""
5 = ""
6 = ""
7 = ""
8 = ""
9 = ""
10 = ""

[theme.icons.capture]
camera = ""
display = ""
select = ""
record = ""

[theme.icon.wifi]
wifi_up = ""
wifi_down = ""

[theme.icon.eth]
eth_up = ""
eth_down = ""
