base00 = "031A16"
base01 = "0B342D"
base02 = "184E45"
base03 = "2B685E"
base04 = "5F9C92"
base05 = "81B5AC"
base06 = "A7CEC8"
base07 = "D2E7E4"
base08 = "3E9688"
base09 = "3E7996"
base0A = "3E4C96"
base0B = "883E96"
base0C = "963E4C"
base0D = "96883E"
base0E = "4C963E"
base0F = "3E965B"

gtk_colors = """
@define-color base00  #031A16;
@define-color base01  #0B342D;
@define-color base02  #184E45;
@define-color base03  #2B685E;
@define-color base04  #5F9C92;
@define-color base05  #81B5AC;
@define-color base06  #A7CEC8;
@define-color base07  #D2E7E4;
@define-color base08  #3E9688;
@define-color base09  #3E7996;
@define-color base0A  #3E4C96;
@define-color base0B  #883E96;
@define-color base0C  #963E4C;
@define-color base0D  #96883E;
@define-color base0E  #4C963E;
@define-color base0F  #3E965B;
"""

scss_colors = """
$base00: #031A16;
$base01: #0B342D;
$base02: #184E45;
$base03: #2B685E;
$base04: #5F9C92;
$base05: #81B5AC;
$base06: #A7CEC8;
$base07: #D2E7E4;
$base08: #3E9688;
$base09: #3E7996;
$base0A: #3E4C96;
$base0B: #883E96;
$base0C: #963E4C;
$base0D: #96883E;
$base0E: #4C963E;
$base0F: #3E965B;
"""
