base00 = "efecf4"
base01 = "e2dfe7"
base02 = "8b8792"
base03 = "7e7887"
base04 = "655f6d"
base05 = "585260"
base06 = "26232a"
base07 = "19171c"
base08 = "be4678"
base09 = "aa573c"
base0A = "a06e3b"
base0B = "2a9292"
base0C = "398bc6"
base0D = "576ddb"
base0E = "955ae7"
base0F = "bf40bf"

gtk_colors = """
@define-color base00  #efecf4;
@define-color base01  #e2dfe7;
@define-color base02  #8b8792;
@define-color base03  #7e7887;
@define-color base04  #655f6d;
@define-color base05  #585260;
@define-color base06  #26232a;
@define-color base07  #19171c;
@define-color base08  #be4678;
@define-color base09  #aa573c;
@define-color base0A  #a06e3b;
@define-color base0B  #2a9292;
@define-color base0C  #398bc6;
@define-color base0D  #576ddb;
@define-color base0E  #955ae7;
@define-color base0F  #bf40bf;
"""

scss_colors = """
$base00: #efecf4;
$base01: #e2dfe7;
$base02: #8b8792;
$base03: #7e7887;
$base04: #655f6d;
$base05: #585260;
$base06: #26232a;
$base07: #19171c;
$base08: #be4678;
$base09: #aa573c;
$base0A: #a06e3b;
$base0B: #2a9292;
$base0C: #398bc6;
$base0D: #576ddb;
$base0E: #955ae7;
$base0F: #bf40bf;
"""
