base00 = "ecf4ee"
base01 = "dfe7e2"
base02 = "87928a"
base03 = "78877d"
base04 = "5f6d64"
base05 = "526057"
base06 = "232a25"
base07 = "171c19"
base08 = "b16139"
base09 = "9f713c"
base0A = "a07e3b"
base0B = "489963"
base0C = "1c9aa0"
base0D = "478c90"
base0E = "55859b"
base0F = "867469"

gtk_colors = """
@define-color base00  #ecf4ee;
@define-color base01  #dfe7e2;
@define-color base02  #87928a;
@define-color base03  #78877d;
@define-color base04  #5f6d64;
@define-color base05  #526057;
@define-color base06  #232a25;
@define-color base07  #171c19;
@define-color base08  #b16139;
@define-color base09  #9f713c;
@define-color base0A  #a07e3b;
@define-color base0B  #489963;
@define-color base0C  #1c9aa0;
@define-color base0D  #478c90;
@define-color base0E  #55859b;
@define-color base0F  #867469;
"""

scss_colors = """
$base00: #ecf4ee;
$base01: #dfe7e2;
$base02: #87928a;
$base03: #78877d;
$base04: #5f6d64;
$base05: #526057;
$base06: #232a25;
$base07: #171c19;
$base08: #b16139;
$base09: #9f713c;
$base0A: #a07e3b;
$base0B: #489963;
$base0C: #1c9aa0;
$base0D: #478c90;
$base0E: #55859b;
$base0F: #867469;
"""
