base00 = "fefbec"
base01 = "e8e4cf"
base02 = "a6a28c"
base03 = "999580"
base04 = "7d7a68"
base05 = "6e6b5e"
base06 = "292824"
base07 = "20201d"
base08 = "d73737"
base09 = "b65611"
base0A = "ae9513"
base0B = "60ac39"
base0C = "1fad83"
base0D = "6684e1"
base0E = "b854d4"
base0F = "d43552"

gtk_colors = """
@define-color base00  #fefbec;
@define-color base01  #e8e4cf;
@define-color base02  #a6a28c;
@define-color base03  #999580;
@define-color base04  #7d7a68;
@define-color base05  #6e6b5e;
@define-color base06  #292824;
@define-color base07  #20201d;
@define-color base08  #d73737;
@define-color base09  #b65611;
@define-color base0A  #ae9513;
@define-color base0B  #60ac39;
@define-color base0C  #1fad83;
@define-color base0D  #6684e1;
@define-color base0E  #b854d4;
@define-color base0F  #d43552;
"""

scss_colors = """
$base00: #fefbec;
$base01: #e8e4cf;
$base02: #a6a28c;
$base03: #999580;
$base04: #7d7a68;
$base05: #6e6b5e;
$base06: #292824;
$base07: #20201d;
$base08: #d73737;
$base09: #b65611;
$base0A: #ae9513;
$base0B: #60ac39;
$base0C: #1fad83;
$base0D: #6684e1;
$base0E: #b854d4;
$base0F: #d43552;
"""
