base00 = "161b1d"
base01 = "1f292e"
base02 = "516d7b"
base03 = "5a7b8c"
base04 = "7195a8"
base05 = "7ea2b4"
base06 = "c1e4f6"
base07 = "ebf8ff"
base08 = "d22d72"
base09 = "935c25"
base0A = "8a8a0f"
base0B = "568c3b"
base0C = "2d8f6f"
base0D = "257fad"
base0E = "6b6bb8"
base0F = "b72dd2"

gtk_colors = """
@define-color base00  #161b1d;
@define-color base01  #1f292e;
@define-color base02  #516d7b;
@define-color base03  #5a7b8c;
@define-color base04  #7195a8;
@define-color base05  #7ea2b4;
@define-color base06  #c1e4f6;
@define-color base07  #ebf8ff;
@define-color base08  #d22d72;
@define-color base09  #935c25;
@define-color base0A  #8a8a0f;
@define-color base0B  #568c3b;
@define-color base0C  #2d8f6f;
@define-color base0D  #257fad;
@define-color base0E  #6b6bb8;
@define-color base0F  #b72dd2;
"""

scss_colors = """
$base00: #161b1d;
$base01: #1f292e;
$base02: #516d7b;
$base03: #5a7b8c;
$base04: #7195a8;
$base05: #7ea2b4;
$base06: #c1e4f6;
$base07: #ebf8ff;
$base08: #d22d72;
$base09: #935c25;
$base0A: #8a8a0f;
$base0B: #568c3b;
$base0C: #2d8f6f;
$base0D: #257fad;
$base0E: #6b6bb8;
$base0F: #b72dd2;
"""
