base00 = "f5f7ff"
base01 = "dfe2f1"
base02 = "979db4"
base03 = "898ea4"
base04 = "6b7394"
base05 = "5e6687"
base06 = "293256"
base07 = "202746"
base08 = "c94922"
base09 = "c76b29"
base0A = "c08b30"
base0B = "ac9739"
base0C = "22a2c9"
base0D = "3d8fd1"
base0E = "6679cc"
base0F = "9c637a"

gtk_colors = """
@define-color base00  #f5f7ff;
@define-color base01  #dfe2f1;
@define-color base02  #979db4;
@define-color base03  #898ea4;
@define-color base04  #6b7394;
@define-color base05  #5e6687;
@define-color base06  #293256;
@define-color base07  #202746;
@define-color base08  #c94922;
@define-color base09  #c76b29;
@define-color base0A  #c08b30;
@define-color base0B  #ac9739;
@define-color base0C  #22a2c9;
@define-color base0D  #3d8fd1;
@define-color base0E  #6679cc;
@define-color base0F  #9c637a;
"""

scss_colors = """
$base00: #f5f7ff;
$base01: #dfe2f1;
$base02: #979db4;
$base03: #898ea4;
$base04: #6b7394;
$base05: #5e6687;
$base06: #293256;
$base07: #202746;
$base08: #c94922;
$base09: #c76b29;
$base0A: #c08b30;
$base0B: #ac9739;
$base0C: #22a2c9;
$base0D: #3d8fd1;
$base0E: #6679cc;
$base0F: #9c637a;
"""
