base00 = "f4ecec"
base01 = "e7dfdf"
base02 = "8a8585"
base03 = "7e7777"
base04 = "655d5d"
base05 = "585050"
base06 = "292424"
base07 = "1b1818"
base08 = "ca4949"
base09 = "b45a3c"
base0A = "a06e3b"
base0B = "4b8b8b"
base0C = "5485b6"
base0D = "7272ca"
base0E = "8464c4"
base0F = "bd5187"

gtk_colors = """
@define-color base00  #f4ecec;
@define-color base01  #e7dfdf;
@define-color base02  #8a8585;
@define-color base03  #7e7777;
@define-color base04  #655d5d;
@define-color base05  #585050;
@define-color base06  #292424;
@define-color base07  #1b1818;
@define-color base08  #ca4949;
@define-color base09  #b45a3c;
@define-color base0A  #a06e3b;
@define-color base0B  #4b8b8b;
@define-color base0C  #5485b6;
@define-color base0D  #7272ca;
@define-color base0E  #8464c4;
@define-color base0F  #bd5187;
"""

scss_colors = """
$base00: #f4ecec;
$base01: #e7dfdf;
$base02: #8a8585;
$base03: #7e7777;
$base04: #655d5d;
$base05: #585050;
$base06: #292424;
$base07: #1b1818;
$base08: #ca4949;
$base09: #b45a3c;
$base0A: #a06e3b;
$base0B: #4b8b8b;
$base0C: #5485b6;
$base0D: #7272ca;
$base0E: #8464c4;
$base0F: #bd5187;
"""
