base00 = "f4f3ec"
base01 = "e7e6df"
base02 = "929181"
base03 = "878573"
base04 = "6c6b5a"
base05 = "5f5e4e"
base06 = "302f27"
base07 = "22221b"
base08 = "ba6236"
base09 = "ae7313"
base0A = "a5980d"
base0B = "7d9726"
base0C = "5b9d48"
base0D = "36a166"
base0E = "5f9182"
base0F = "9d6c7c"

gtk_colors = """
@define-color base00  #f4f3ec;
@define-color base01  #e7e6df;
@define-color base02  #929181;
@define-color base03  #878573;
@define-color base04  #6c6b5a;
@define-color base05  #5f5e4e;
@define-color base06  #302f27;
@define-color base07  #22221b;
@define-color base08  #ba6236;
@define-color base09  #ae7313;
@define-color base0A  #a5980d;
@define-color base0B  #7d9726;
@define-color base0C  #5b9d48;
@define-color base0D  #36a166;
@define-color base0E  #5f9182;
@define-color base0F  #9d6c7c;
"""

scss_colors = """
$base00: #f4f3ec;
$base01: #e7e6df;
$base02: #929181;
$base03: #878573;
$base04: #6c6b5a;
$base05: #5f5e4e;
$base06: #302f27;
$base07: #22221b;
$base08: #ba6236;
$base09: #ae7313;
$base0A: #a5980d;
$base0B: #7d9726;
$base0C: #5b9d48;
$base0D: #36a166;
$base0E: #5f9182;
$base0F: #9d6c7c;
"""
