base00 = "f7f3f7"
base01 = "d8cad8"
base02 = "ab9bab"
base03 = "9e8f9e"
base04 = "776977"
base05 = "695d69"
base06 = "292329"
base07 = "1b181b"
base08 = "ca402b"
base09 = "a65926"
base0A = "bb8a35"
base0B = "918b3b"
base0C = "159393"
base0D = "516aec"
base0E = "7b59c0"
base0F = "cc33cc"

gtk_colors = """
@define-color base00  #f7f3f7;
@define-color base01  #d8cad8;
@define-color base02  #ab9bab;
@define-color base03  #9e8f9e;
@define-color base04  #776977;
@define-color base05  #695d69;
@define-color base06  #292329;
@define-color base07  #1b181b;
@define-color base08  #ca402b;
@define-color base09  #a65926;
@define-color base0A  #bb8a35;
@define-color base0B  #918b3b;
@define-color base0C  #159393;
@define-color base0D  #516aec;
@define-color base0E  #7b59c0;
@define-color base0F  #cc33cc;
"""

scss_colors = """
$base00: #f7f3f7;
$base01: #d8cad8;
$base02: #ab9bab;
$base03: #9e8f9e;
$base04: #776977;
$base05: #695d69;
$base06: #292329;
$base07: #1b181b;
$base08: #ca402b;
$base09: #a65926;
$base0A: #bb8a35;
$base0B: #918b3b;
$base0C: #159393;
$base0D: #516aec;
$base0E: #7b59c0;
$base0F: #cc33cc;
"""
