base00 = "f4fbf4"
base01 = "cfe8cf"
base02 = "8ca68c"
base03 = "809980"
base04 = "687d68"
base05 = "5e6e5e"
base06 = "242924"
base07 = "131513"
base08 = "e6193c"
base09 = "87711d"
base0A = "98981b"
base0B = "29a329"
base0C = "1999b3"
base0D = "3d62f5"
base0E = "ad2bee"
base0F = "e619c3"

gtk_colors = """
@define-color base00  #f4fbf4;
@define-color base01  #cfe8cf;
@define-color base02  #8ca68c;
@define-color base03  #809980;
@define-color base04  #687d68;
@define-color base05  #5e6e5e;
@define-color base06  #242924;
@define-color base07  #131513;
@define-color base08  #e6193c;
@define-color base09  #87711d;
@define-color base0A  #98981b;
@define-color base0B  #29a329;
@define-color base0C  #1999b3;
@define-color base0D  #3d62f5;
@define-color base0E  #ad2bee;
@define-color base0F  #e619c3;
"""

scss_colors = """
$base00: #f4fbf4;
$base01: #cfe8cf;
$base02: #8ca68c;
$base03: #809980;
$base04: #687d68;
$base05: #5e6e5e;
$base06: #242924;
$base07: #131513;
$base08: #e6193c;
$base09: #87711d;
$base0A: #98981b;
$base0B: #29a329;
$base0C: #1999b3;
$base0D: #3d62f5;
$base0E: #ad2bee;
$base0F: #e619c3;
"""
