base00 = "002635"
base01 = "00384d"
base02 = "517F8D"
base03 = "6C8B91"
base04 = "869696"
base05 = "a1a19a"
base06 = "e6e6dc"
base07 = "fafaf8"
base08 = "ff5a67"
base09 = "f08e48"
base0A = "ffcc1b"
base0B = "7fc06e"
base0C = "14747e"
base0D = "5dd7b9"
base0E = "9a70a4"
base0F = "c43060"

gtk_colors = """
@define-color base00  #002635;
@define-color base01  #00384d;
@define-color base02  #517F8D;
@define-color base03  #6C8B91;
@define-color base04  #869696;
@define-color base05  #a1a19a;
@define-color base06  #e6e6dc;
@define-color base07  #fafaf8;
@define-color base08  #ff5a67;
@define-color base09  #f08e48;
@define-color base0A  #ffcc1b;
@define-color base0B  #7fc06e;
@define-color base0C  #14747e;
@define-color base0D  #5dd7b9;
@define-color base0E  #9a70a4;
@define-color base0F  #c43060;
"""

scss_colors = """
$base00: #002635;
$base01: #00384d;
$base02: #517F8D;
$base03: #6C8B91;
$base04: #869696;
$base05: #a1a19a;
$base06: #e6e6dc;
$base07: #fafaf8;
$base08: #ff5a67;
$base09: #f08e48;
$base0A: #ffcc1b;
$base0B: #7fc06e;
$base0C: #14747e;
$base0D: #5dd7b9;
$base0E: #9a70a4;
$base0F: #c43060;
"""
