base00 = "171B24"
base01 = "1F2430"
base02 = "242936"
base03 = "707A8C"
base04 = "8A9199"
base05 = "CCCAC2"
base06 = "D9D7CE"
base07 = "F3F4F5"
base08 = "F28779"
base09 = "FFAD66"
base0A = "FFD173"
base0B = "D5FF80"
base0C = "95E6CB"
base0D = "5CCFE6"
base0E = "D4BFFF"
base0F = "F29E74"

gtk_colors = """
@define-color base00  #171B24;
@define-color base01  #1F2430;
@define-color base02  #242936;
@define-color base03  #707A8C;
@define-color base04  #8A9199;
@define-color base05  #CCCAC2;
@define-color base06  #D9D7CE;
@define-color base07  #F3F4F5;
@define-color base08  #F28779;
@define-color base09  #FFAD66;
@define-color base0A  #FFD173;
@define-color base0B  #D5FF80;
@define-color base0C  #95E6CB;
@define-color base0D  #5CCFE6;
@define-color base0E  #D4BFFF;
@define-color base0F  #F29E74;
"""

scss_colors = """
$base00: #171B24;
$base01: #1F2430;
$base02: #242936;
$base03: #707A8C;
$base04: #8A9199;
$base05: #CCCAC2;
$base06: #D9D7CE;
$base07: #F3F4F5;
$base08: #F28779;
$base09: #FFAD66;
$base0A: #FFD173;
$base0B: #D5FF80;
$base0C: #95E6CB;
$base0D: #5CCFE6;
$base0E: #D4BFFF;
$base0F: #F29E74;
"""
