base00 = "28211c"
base01 = "36312e"
base02 = "5e5d5c"
base03 = "666666"
base04 = "797977"
base05 = "8a8986"
base06 = "9d9b97"
base07 = "baae9e"
base08 = "cf6a4c"
base09 = "cf7d34"
base0A = "f9ee98"
base0B = "54be0d"
base0C = "afc4db"
base0D = "5ea6ea"
base0E = "9b859d"
base0F = "937121"

gtk_colors = """
@define-color base00  #28211c;
@define-color base01  #36312e;
@define-color base02  #5e5d5c;
@define-color base03  #666666;
@define-color base04  #797977;
@define-color base05  #8a8986;
@define-color base06  #9d9b97;
@define-color base07  #baae9e;
@define-color base08  #cf6a4c;
@define-color base09  #cf7d34;
@define-color base0A  #f9ee98;
@define-color base0B  #54be0d;
@define-color base0C  #afc4db;
@define-color base0D  #5ea6ea;
@define-color base0E  #9b859d;
@define-color base0F  #937121;
"""

scss_colors = """
$base00: #28211c;
$base01: #36312e;
$base02: #5e5d5c;
$base03: #666666;
$base04: #797977;
$base05: #8a8986;
$base06: #9d9b97;
$base07: #baae9e;
$base08: #cf6a4c;
$base09: #cf7d34;
$base0A: #f9ee98;
$base0B: #54be0d;
$base0C: #afc4db;
$base0D: #5ea6ea;
$base0E: #9b859d;
$base0F: #937121;
"""
