base00 = "000000"
base01 = "121212"
base02 = "222222"
base03 = "333333"
base04 = "999999"
base05 = "c1c1c1"
base06 = "999999"
base07 = "c1c1c1"
base08 = "5f8787"
base09 = "aaaaaa"
base0A = "556677"
base0B = "7799bb"
base0C = "aaaaaa"
base0D = "888888"
base0E = "999999"
base0F = "444444"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #121212;
@define-color base02  #222222;
@define-color base03  #333333;
@define-color base04  #999999;
@define-color base05  #c1c1c1;
@define-color base06  #999999;
@define-color base07  #c1c1c1;
@define-color base08  #5f8787;
@define-color base09  #aaaaaa;
@define-color base0A  #556677;
@define-color base0B  #7799bb;
@define-color base0C  #aaaaaa;
@define-color base0D  #888888;
@define-color base0E  #999999;
@define-color base0F  #444444;
"""

scss_colors = """
$base00: #000000;
$base01: #121212;
$base02: #222222;
$base03: #333333;
$base04: #999999;
$base05: #c1c1c1;
$base06: #999999;
$base07: #c1c1c1;
$base08: #5f8787;
$base09: #aaaaaa;
$base0A: #556677;
$base0B: #7799bb;
$base0C: #aaaaaa;
$base0D: #888888;
$base0E: #999999;
$base0F: #444444;
"""
