base00 = "141F2E"
base01 = "1e5c1e"
base02 = "273e5c"
base03 = "a0ffa0"
base04 = "1e5c1e"
base05 = "FFCC33"
base06 = "91CCFF"
base07 = "375780"
base08 = "fffab1"
base09 = "FF8080"
base0A = "91CCFF"
base0B = "80ff80"
base0C = "80ff80"
base0D = "a2cff5"
base0E = "0099FF"
base0F = "e7e7e7"

gtk_colors = """
@define-color base00  #141F2E;
@define-color base01  #1e5c1e;
@define-color base02  #273e5c;
@define-color base03  #a0ffa0;
@define-color base04  #1e5c1e;
@define-color base05  #FFCC33;
@define-color base06  #91CCFF;
@define-color base07  #375780;
@define-color base08  #fffab1;
@define-color base09  #FF8080;
@define-color base0A  #91CCFF;
@define-color base0B  #80ff80;
@define-color base0C  #80ff80;
@define-color base0D  #a2cff5;
@define-color base0E  #0099FF;
@define-color base0F  #e7e7e7;
"""

scss_colors = """
$base00: #141F2E;
$base01: #1e5c1e;
$base02: #273e5c;
$base03: #a0ffa0;
$base04: #1e5c1e;
$base05: #FFCC33;
$base06: #91CCFF;
$base07: #375780;
$base08: #fffab1;
$base09: #FF8080;
$base0A: #91CCFF;
$base0B: #80ff80;
$base0C: #80ff80;
$base0D: #a2cff5;
$base0E: #0099FF;
$base0F: #e7e7e7;
"""
