base00 = "0c0d0e"
base01 = "2e2f30"
base02 = "515253"
base03 = "737475"
base04 = "959697"
base05 = "b7b8b9"
base06 = "dadbdc"
base07 = "fcfdfe"
base08 = "e31a1c"
base09 = "e6550d"
base0A = "dca060"
base0B = "31a354"
base0C = "80b1d3"
base0D = "3182bd"
base0E = "756bb1"
base0F = "b15928"

gtk_colors = """
@define-color base00  #0c0d0e;
@define-color base01  #2e2f30;
@define-color base02  #515253;
@define-color base03  #737475;
@define-color base04  #959697;
@define-color base05  #b7b8b9;
@define-color base06  #dadbdc;
@define-color base07  #fcfdfe;
@define-color base08  #e31a1c;
@define-color base09  #e6550d;
@define-color base0A  #dca060;
@define-color base0B  #31a354;
@define-color base0C  #80b1d3;
@define-color base0D  #3182bd;
@define-color base0E  #756bb1;
@define-color base0F  #b15928;
"""

scss_colors = """
$base00: #0c0d0e;
$base01: #2e2f30;
$base02: #515253;
$base03: #737475;
$base04: #959697;
$base05: #b7b8b9;
$base06: #dadbdc;
$base07: #fcfdfe;
$base08: #e31a1c;
$base09: #e6550d;
$base0A: #dca060;
$base0B: #31a354;
$base0C: #80b1d3;
$base0D: #3182bd;
$base0E: #756bb1;
$base0F: #b15928;
"""
