base00 = "000000"
base01 = "303030"
base02 = "505050"
base03 = "b0b0b0"
base04 = "d0d0d0"
base05 = "e0e0e0"
base06 = "f5f5f5"
base07 = "ffffff"
base08 = "fb0120"
base09 = "fc6d24"
base0A = "fda331"
base0B = "a1c659"
base0C = "76c7b7"
base0D = "6fb3d2"
base0E = "d381c3"
base0F = "be643c"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #303030;
@define-color base02  #505050;
@define-color base03  #b0b0b0;
@define-color base04  #d0d0d0;
@define-color base05  #e0e0e0;
@define-color base06  #f5f5f5;
@define-color base07  #ffffff;
@define-color base08  #fb0120;
@define-color base09  #fc6d24;
@define-color base0A  #fda331;
@define-color base0B  #a1c659;
@define-color base0C  #76c7b7;
@define-color base0D  #6fb3d2;
@define-color base0E  #d381c3;
@define-color base0F  #be643c;
"""

scss_colors = """
$base00: #000000;
$base01: #303030;
$base02: #505050;
$base03: #b0b0b0;
$base04: #d0d0d0;
$base05: #e0e0e0;
$base06: #f5f5f5;
$base07: #ffffff;
$base08: #fb0120;
$base09: #fc6d24;
$base0A: #fda331;
$base0B: #a1c659;
$base0C: #76c7b7;
$base0D: #6fb3d2;
$base0E: #d381c3;
$base0F: #be643c;
"""
