base00 = "1f1f1f"
base01 = "f81118"
base02 = "2dc55e"
base03 = "ecba0f"
base04 = "2a84d2"
base05 = "4e5ab7"
base06 = "1081d6"
base07 = "d6dbe5"
base08 = "d6dbe5"
base09 = "de352e"
base0A = "1dd361"
base0B = "f3bd09"
base0C = "1081d6"
base0D = "5350b9"
base0E = "0f7ddb"
base0F = "ffffff"

gtk_colors = """
@define-color base00  #1f1f1f;
@define-color base01  #f81118;
@define-color base02  #2dc55e;
@define-color base03  #ecba0f;
@define-color base04  #2a84d2;
@define-color base05  #4e5ab7;
@define-color base06  #1081d6;
@define-color base07  #d6dbe5;
@define-color base08  #d6dbe5;
@define-color base09  #de352e;
@define-color base0A  #1dd361;
@define-color base0B  #f3bd09;
@define-color base0C  #1081d6;
@define-color base0D  #5350b9;
@define-color base0E  #0f7ddb;
@define-color base0F  #ffffff;
"""

scss_colors = """
$base00: #1f1f1f;
$base01: #f81118;
$base02: #2dc55e;
$base03: #ecba0f;
$base04: #2a84d2;
$base05: #4e5ab7;
$base06: #1081d6;
$base07: #d6dbe5;
$base08: #d6dbe5;
$base09: #de352e;
$base0A: #1dd361;
$base0B: #f3bd09;
$base0C: #1081d6;
$base0D: #5350b9;
$base0E: #0f7ddb;
$base0F: #ffffff;
"""
