base00 = "E3EFEF"
base01 = "C9DBDC"
base02 = "B0C5C8"
base03 = "98AFB5"
base04 = "8299A1"
base05 = "6D828E"
base06 = "5A6D7A"
base07 = "485867"
base08 = "b38686"
base09 = "d8bba2"
base0A = "aab386"
base0B = "87b386"
base0C = "86b3b3"
base0D = "868cb3"
base0E = "b386b2"
base0F = "b39f9f"

gtk_colors = """
@define-color base00  #E3EFEF;
@define-color base01  #C9DBDC;
@define-color base02  #B0C5C8;
@define-color base03  #98AFB5;
@define-color base04  #8299A1;
@define-color base05  #6D828E;
@define-color base06  #5A6D7A;
@define-color base07  #485867;
@define-color base08  #b38686;
@define-color base09  #d8bba2;
@define-color base0A  #aab386;
@define-color base0B  #87b386;
@define-color base0C  #86b3b3;
@define-color base0D  #868cb3;
@define-color base0E  #b386b2;
@define-color base0F  #b39f9f;
"""

scss_colors = """
$base00: #E3EFEF;
$base01: #C9DBDC;
$base02: #B0C5C8;
$base03: #98AFB5;
$base04: #8299A1;
$base05: #6D828E;
$base06: #5A6D7A;
$base07: #485867;
$base08: #b38686;
$base09: #d8bba2;
$base0A: #aab386;
$base0B: #87b386;
$base0C: #86b3b3;
$base0D: #868cb3;
$base0E: #b386b2;
$base0F: #b39f9f;
"""
