base00 = "1c1213"
base01 = "3a2425"
base02 = "563837"
base03 = "6d4745"
base04 = "8b5d57"
base05 = "a87569"
base06 = "c58d7b"
base07 = "e3a68c"
base08 = "c24f57"
base09 = "a63650"
base0A = "f28171"
base0B = "806c61"
base0C = "6b6566"
base0D = "684c59"
base0E = "a63650"
base0F = "893f45"

gtk_colors = """
@define-color base00  #1c1213;
@define-color base01  #3a2425;
@define-color base02  #563837;
@define-color base03  #6d4745;
@define-color base04  #8b5d57;
@define-color base05  #a87569;
@define-color base06  #c58d7b;
@define-color base07  #e3a68c;
@define-color base08  #c24f57;
@define-color base09  #a63650;
@define-color base0A  #f28171;
@define-color base0B  #806c61;
@define-color base0C  #6b6566;
@define-color base0D  #684c59;
@define-color base0E  #a63650;
@define-color base0F  #893f45;
"""

scss_colors = """
$base00: #1c1213;
$base01: #3a2425;
$base02: #563837;
$base03: #6d4745;
$base04: #8b5d57;
$base05: #a87569;
$base06: #c58d7b;
$base07: #e3a68c;
$base08: #c24f57;
$base09: #a63650;
$base0A: #f28171;
$base0B: #806c61;
$base0C: #6b6566;
$base0D: #684c59;
$base0E: #a63650;
$base0F: #893f45;
"""
