base00 = "eff1f5"
base01 = "e6e9ef"
base02 = "ccd0da"
base03 = "bcc0cc"
base04 = "acb0be"
base05 = "4c4f69"
base06 = "dc8a78"
base07 = "7287fd"
base08 = "d20f39"
base09 = "fe640b"
base0A = "df8e1d"
base0B = "40a02b"
base0C = "179299"
base0D = "1e66f5"
base0E = "8839ef"
base0F = "dd7878"

gtk_colors = """
@define-color base00  #eff1f5;
@define-color base01  #e6e9ef;
@define-color base02  #ccd0da;
@define-color base03  #bcc0cc;
@define-color base04  #acb0be;
@define-color base05  #4c4f69;
@define-color base06  #dc8a78;
@define-color base07  #7287fd;
@define-color base08  #d20f39;
@define-color base09  #fe640b;
@define-color base0A  #df8e1d;
@define-color base0B  #40a02b;
@define-color base0C  #179299;
@define-color base0D  #1e66f5;
@define-color base0E  #8839ef;
@define-color base0F  #dd7878;
"""

scss_colors = """
$base00: #eff1f5;
$base01: #e6e9ef;
$base02: #ccd0da;
$base03: #bcc0cc;
$base04: #acb0be;
$base05: #4c4f69;
$base06: #dc8a78;
$base07: #7287fd;
$base08: #d20f39;
$base09: #fe640b;
$base0A: #df8e1d;
$base0B: #40a02b;
$base0C: #179299;
$base0D: #1e66f5;
$base0E: #8839ef;
$base0F: #dd7878;
"""
