base00 = "24273a"
base01 = "1e2030"
base02 = "363a4f"
base03 = "494d64"
base04 = "5b6078"
base05 = "cad3f5"
base06 = "f4dbd6"
base07 = "b7bdf8"
base08 = "ed8796"
base09 = "f5a97f"
base0A = "eed49f"
base0B = "a6da95"
base0C = "8bd5ca"
base0D = "8aadf4"
base0E = "c6a0f6"
base0F = "f0c6c6"

gtk_colors = """
@define-color base00  #24273a;
@define-color base01  #1e2030;
@define-color base02  #363a4f;
@define-color base03  #494d64;
@define-color base04  #5b6078;
@define-color base05  #cad3f5;
@define-color base06  #f4dbd6;
@define-color base07  #b7bdf8;
@define-color base08  #ed8796;
@define-color base09  #f5a97f;
@define-color base0A  #eed49f;
@define-color base0B  #a6da95;
@define-color base0C  #8bd5ca;
@define-color base0D  #8aadf4;
@define-color base0E  #c6a0f6;
@define-color base0F  #f0c6c6;
"""

scss_colors = """
$base00: #24273a;
$base01: #1e2030;
$base02: #363a4f;
$base03: #494d64;
$base04: #5b6078;
$base05: #cad3f5;
$base06: #f4dbd6;
$base07: #b7bdf8;
$base08: #ed8796;
$base09: #f5a97f;
$base0A: #eed49f;
$base0B: #a6da95;
$base0C: #8bd5ca;
$base0D: #8aadf4;
$base0E: #c6a0f6;
$base0F: #f0c6c6;
"""
