base00 = "1e1e2e"
base01 = "181825"
base02 = "313244"
base03 = "45475a"
base04 = "585b70"
base05 = "cdd6f4"
base06 = "f5e0dc"
base07 = "b4befe"
base08 = "f38ba8"
base09 = "fab387"
base0A = "f9e2af"
base0B = "a6e3a1"
base0C = "94e2d5"
base0D = "89b4fa"
base0E = "cba6f7"
base0F = "f2cdcd"

gtk_colors = """
@define-color base00  #1e1e2e;
@define-color base01  #181825;
@define-color base02  #313244;
@define-color base03  #45475a;
@define-color base04  #585b70;
@define-color base05  #cdd6f4;
@define-color base06  #f5e0dc;
@define-color base07  #b4befe;
@define-color base08  #f38ba8;
@define-color base09  #fab387;
@define-color base0A  #f9e2af;
@define-color base0B  #a6e3a1;
@define-color base0C  #94e2d5;
@define-color base0D  #89b4fa;
@define-color base0E  #cba6f7;
@define-color base0F  #f2cdcd;
"""

scss_colors = """
$base00: #1e1e2e;
$base01: #181825;
$base02: #313244;
$base03: #45475a;
$base04: #585b70;
$base05: #cdd6f4;
$base06: #f5e0dc;
$base07: #b4befe;
$base08: #f38ba8;
$base09: #fab387;
$base0A: #f9e2af;
$base0B: #a6e3a1;
$base0C: #94e2d5;
$base0D: #89b4fa;
$base0E: #cba6f7;
$base0F: #f2cdcd;
"""
