base00 = "191919"
base01 = "202020"
base02 = "303030"
base03 = "5f5a60"
base04 = "505050"
base05 = "a7a7a7"
base06 = "808080"
base07 = "ffffff"
base08 = "dc657d"
base09 = "4bb1a7"
base0A = "c3ba63"
base0B = "84b97c"
base0C = "4bb1a7"
base0D = "639ee4"
base0E = "b888e2"
base0F = "b888e2"

gtk_colors = """
@define-color base00  #191919;
@define-color base01  #202020;
@define-color base02  #303030;
@define-color base03  #5f5a60;
@define-color base04  #505050;
@define-color base05  #a7a7a7;
@define-color base06  #808080;
@define-color base07  #ffffff;
@define-color base08  #dc657d;
@define-color base09  #4bb1a7;
@define-color base0A  #c3ba63;
@define-color base0B  #84b97c;
@define-color base0C  #4bb1a7;
@define-color base0D  #639ee4;
@define-color base0E  #b888e2;
@define-color base0F  #b888e2;
"""

scss_colors = """
$base00: #191919;
$base01: #202020;
$base02: #303030;
$base03: #5f5a60;
$base04: #505050;
$base05: #a7a7a7;
$base06: #808080;
$base07: #ffffff;
$base08: #dc657d;
$base09: #4bb1a7;
$base0A: #c3ba63;
$base0B: #84b97c;
$base0C: #4bb1a7;
$base0D: #639ee4;
$base0E: #b888e2;
$base0F: #b888e2;
"""
