base00 = "F5F5F5"
base01 = "E0E0E0"
base02 = "D0D0D0"
base03 = "B0B0B0"
base04 = "505050"
base05 = "303030"
base06 = "202020"
base07 = "151515"
base08 = "AC4142"
base09 = "D28445"
base0A = "F4BF75"
base0B = "90A959"
base0C = "75B5AA"
base0D = "6A9FB5"
base0E = "AA759F"
base0F = "8F5536"

gtk_colors = """
@define-color base00  #F5F5F5;
@define-color base01  #E0E0E0;
@define-color base02  #D0D0D0;
@define-color base03  #B0B0B0;
@define-color base04  #505050;
@define-color base05  #303030;
@define-color base06  #202020;
@define-color base07  #151515;
@define-color base08  #AC4142;
@define-color base09  #D28445;
@define-color base0A  #F4BF75;
@define-color base0B  #90A959;
@define-color base0C  #75B5AA;
@define-color base0D  #6A9FB5;
@define-color base0E  #AA759F;
@define-color base0F  #8F5536;
"""

scss_colors = """
$base00: #F5F5F5;
$base01: #E0E0E0;
$base02: #D0D0D0;
$base03: #B0B0B0;
$base04: #505050;
$base05: #303030;
$base06: #202020;
$base07: #151515;
$base08: #AC4142;
$base09: #D28445;
$base0A: #F4BF75;
$base0B: #90A959;
$base0C: #75B5AA;
$base0D: #6A9FB5;
$base0E: #AA759F;
$base0F: #8F5536;
"""
