base00 = "232c31"
base01 = "1c3657"
base02 = "2a343a"
base03 = "3f4944"
base04 = "84898c"
base05 = "9ea7a6"
base06 = "a7cfa3"
base07 = "b5d8f6"
base08 = "2a5491"
base09 = "43820d"
base0A = "a03b1e"
base0B = "237986"
base0C = "b02f30"
base0D = "484d79"
base0E = "c59820"
base0F = "c98344"

gtk_colors = """
@define-color base00  #232c31;
@define-color base01  #1c3657;
@define-color base02  #2a343a;
@define-color base03  #3f4944;
@define-color base04  #84898c;
@define-color base05  #9ea7a6;
@define-color base06  #a7cfa3;
@define-color base07  #b5d8f6;
@define-color base08  #2a5491;
@define-color base09  #43820d;
@define-color base0A  #a03b1e;
@define-color base0B  #237986;
@define-color base0C  #b02f30;
@define-color base0D  #484d79;
@define-color base0E  #c59820;
@define-color base0F  #c98344;
"""

scss_colors = """
$base00: #232c31;
$base01: #1c3657;
$base02: #2a343a;
$base03: #3f4944;
$base04: #84898c;
$base05: #9ea7a6;
$base06: #a7cfa3;
$base07: #b5d8f6;
$base08: #2a5491;
$base09: #43820d;
$base0A: #a03b1e;
$base0B: #237986;
$base0C: #b02f30;
$base0D: #484d79;
$base0E: #c59820;
$base0F: #c98344;
"""
