base00 = "111111"
base01 = "333333"
base02 = "555555"
base03 = "777777"
base04 = "999999"
base05 = "bbbbbb"
base06 = "dddddd"
base07 = "ffffff"
base08 = "ff4136"
base09 = "ff851b"
base0A = "ffdc00"
base0B = "2ecc40"
base0C = "7fdbff"
base0D = "0074d9"
base0E = "b10dc9"
base0F = "85144b"

gtk_colors = """
@define-color base00  #111111;
@define-color base01  #333333;
@define-color base02  #555555;
@define-color base03  #777777;
@define-color base04  #999999;
@define-color base05  #bbbbbb;
@define-color base06  #dddddd;
@define-color base07  #ffffff;
@define-color base08  #ff4136;
@define-color base09  #ff851b;
@define-color base0A  #ffdc00;
@define-color base0B  #2ecc40;
@define-color base0C  #7fdbff;
@define-color base0D  #0074d9;
@define-color base0E  #b10dc9;
@define-color base0F  #85144b;
"""

scss_colors = """
$base00: #111111;
$base01: #333333;
$base02: #555555;
$base03: #777777;
$base04: #999999;
$base05: #bbbbbb;
$base06: #dddddd;
$base07: #ffffff;
$base08: #ff4136;
$base09: #ff851b;
$base0A: #ffdc00;
$base0B: #2ecc40;
$base0C: #7fdbff;
$base0D: #0074d9;
$base0E: #b10dc9;
$base0F: #85144b;
"""
