base00 = "171726"
base01 = "22273d"
base02 = "525866"
base03 = "878d96"
base04 = "c8c8c8"
base05 = "ffffff"
base06 = "ffffff"
base07 = "ffffff"
base08 = "fa7883"
base09 = "ffc387"
base0A = "ff9470"
base0B = "98c379"
base0C = "8af5ff"
base0D = "6bb8ff"
base0E = "e799ff"
base0F = "b3684f"

gtk_colors = """
@define-color base00  #171726;
@define-color base01  #22273d;
@define-color base02  #525866;
@define-color base03  #878d96;
@define-color base04  #c8c8c8;
@define-color base05  #ffffff;
@define-color base06  #ffffff;
@define-color base07  #ffffff;
@define-color base08  #fa7883;
@define-color base09  #ffc387;
@define-color base0A  #ff9470;
@define-color base0B  #98c379;
@define-color base0C  #8af5ff;
@define-color base0D  #6bb8ff;
@define-color base0E  #e799ff;
@define-color base0F  #b3684f;
"""

scss_colors = """
$base00: #171726;
$base01: #22273d;
$base02: #525866;
$base03: #878d96;
$base04: #c8c8c8;
$base05: #ffffff;
$base06: #ffffff;
$base07: #ffffff;
$base08: #fa7883;
$base09: #ffc387;
$base0A: #ff9470;
$base0B: #98c379;
$base0C: #8af5ff;
$base0D: #6bb8ff;
$base0E: #e799ff;
$base0F: #b3684f;
"""
