base00 = "2d302f"
base01 = "434846"
base02 = "5a605d"
base03 = "9da8a3"
base04 = "cad8d2"
base05 = "e0f0eF"
base06 = "ecf6f2"
base07 = "fcfefd"
base08 = "F9906F"
base09 = "B38A61"
base0A = "F0C239"
base0B = "8AB361"
base0C = "30DFF3"
base0D = "B0A4E3"
base0E = "CCA4E3"
base0F = "CA6924"

gtk_colors = """
@define-color base00  #2d302f;
@define-color base01  #434846;
@define-color base02  #5a605d;
@define-color base03  #9da8a3;
@define-color base04  #cad8d2;
@define-color base05  #e0f0eF;
@define-color base06  #ecf6f2;
@define-color base07  #fcfefd;
@define-color base08  #F9906F;
@define-color base09  #B38A61;
@define-color base0A  #F0C239;
@define-color base0B  #8AB361;
@define-color base0C  #30DFF3;
@define-color base0D  #B0A4E3;
@define-color base0E  #CCA4E3;
@define-color base0F  #CA6924;
"""

scss_colors = """
$base00: #2d302f;
$base01: #434846;
$base02: #5a605d;
$base03: #9da8a3;
$base04: #cad8d2;
$base05: #e0f0eF;
$base06: #ecf6f2;
$base07: #fcfefd;
$base08: #F9906F;
$base09: #B38A61;
$base0A: #F0C239;
$base0B: #8AB361;
$base0C: #30DFF3;
$base0D: #B0A4E3;
$base0E: #CCA4E3;
$base0F: #CA6924;
"""
