base00 = "2b2b2b"
base01 = "323232"
base02 = "323232"
base03 = "606366"
base04 = "a4a3a3"
base05 = "a9b7c6"
base06 = "ffc66d"
base07 = "ffffff"
base08 = "4eade5"
base09 = "689757"
base0A = "bbb529"
base0B = "6a8759"
base0C = "629755"
base0D = "9876aa"
base0E = "cc7832"
base0F = "808080"

gtk_colors = """
@define-color base00  #2b2b2b;
@define-color base01  #323232;
@define-color base02  #323232;
@define-color base03  #606366;
@define-color base04  #a4a3a3;
@define-color base05  #a9b7c6;
@define-color base06  #ffc66d;
@define-color base07  #ffffff;
@define-color base08  #4eade5;
@define-color base09  #689757;
@define-color base0A  #bbb529;
@define-color base0B  #6a8759;
@define-color base0C  #629755;
@define-color base0D  #9876aa;
@define-color base0E  #cc7832;
@define-color base0F  #808080;
"""

scss_colors = """
$base00: #2b2b2b;
$base01: #323232;
$base02: #323232;
$base03: #606366;
$base04: #a4a3a3;
$base05: #a9b7c6;
$base06: #ffc66d;
$base07: #ffffff;
$base08: #4eade5;
$base09: #689757;
$base0A: #bbb529;
$base0B: #6a8759;
$base0C: #629755;
$base0D: #9876aa;
$base0E: #cc7832;
$base0F: #808080;
"""
