base00 = "1D2021"
base01 = "32302F"
base02 = "504945"
base03 = "665C54"
base04 = "928374"
base05 = "A89984"
base06 = "D5C4A1"
base07 = "FDF4C1"
base08 = "FB543F"
base09 = "FE8625"
base0A = "FAC03B"
base0B = "95C085"
base0C = "8BA59B"
base0D = "0D6678"
base0E = "8F4673"
base0F = "A87322"

gtk_colors = """
@define-color base00  #1D2021;
@define-color base01  #32302F;
@define-color base02  #504945;
@define-color base03  #665C54;
@define-color base04  #928374;
@define-color base05  #A89984;
@define-color base06  #D5C4A1;
@define-color base07  #FDF4C1;
@define-color base08  #FB543F;
@define-color base09  #FE8625;
@define-color base0A  #FAC03B;
@define-color base0B  #95C085;
@define-color base0C  #8BA59B;
@define-color base0D  #0D6678;
@define-color base0E  #8F4673;
@define-color base0F  #A87322;
"""

scss_colors = """
$base00: #1D2021;
$base01: #32302F;
$base02: #504945;
$base03: #665C54;
$base04: #928374;
$base05: #A89984;
$base06: #D5C4A1;
$base07: #FDF4C1;
$base08: #FB543F;
$base09: #FE8625;
$base0A: #FAC03B;
$base0B: #95C085;
$base0C: #8BA59B;
$base0D: #0D6678;
$base0E: #8F4673;
$base0F: #A87322;
"""
