base00 = "171e1f"
base01 = "252c2d"
base02 = "373c3d"
base03 = "555e5f"
base04 = "818f80"
base05 = "c7c7a5"
base06 = "e3e3c8"
base07 = "e1eaef"
base08 = "ff4658"
base09 = "e6db74"
base0A = "fdb11f"
base0B = "499180"
base0C = "66d9ef"
base0D = "498091"
base0E = "9bc0c8"
base0F = "d27b53"

gtk_colors = """
@define-color base00  #171e1f;
@define-color base01  #252c2d;
@define-color base02  #373c3d;
@define-color base03  #555e5f;
@define-color base04  #818f80;
@define-color base05  #c7c7a5;
@define-color base06  #e3e3c8;
@define-color base07  #e1eaef;
@define-color base08  #ff4658;
@define-color base09  #e6db74;
@define-color base0A  #fdb11f;
@define-color base0B  #499180;
@define-color base0C  #66d9ef;
@define-color base0D  #498091;
@define-color base0E  #9bc0c8;
@define-color base0F  #d27b53;
"""

scss_colors = """
$base00: #171e1f;
$base01: #252c2d;
$base02: #373c3d;
$base03: #555e5f;
$base04: #818f80;
$base05: #c7c7a5;
$base06: #e3e3c8;
$base07: #e1eaef;
$base08: #ff4658;
$base09: #e6db74;
$base0A: #fdb11f;
$base0B: #499180;
$base0C: #66d9ef;
$base0D: #498091;
$base0E: #9bc0c8;
$base0F: #d27b53;
"""
