base00 = "2d2d2d"
base01 = "393939"
base02 = "515151"
base03 = "777777"
base04 = "b4b7b4"
base05 = "cccccc"
base06 = "e0e0e0"
base07 = "ffffff"
base08 = "ff7f7b"
base09 = "ffbf70"
base0A = "ffd67c"
base0B = "beda78"
base0C = "bed6ff"
base0D = "90bee1"
base0E = "efb3f7"
base0F = "ff93b3"

gtk_colors = """
@define-color base00  #2d2d2d;
@define-color base01  #393939;
@define-color base02  #515151;
@define-color base03  #777777;
@define-color base04  #b4b7b4;
@define-color base05  #cccccc;
@define-color base06  #e0e0e0;
@define-color base07  #ffffff;
@define-color base08  #ff7f7b;
@define-color base09  #ffbf70;
@define-color base0A  #ffd67c;
@define-color base0B  #beda78;
@define-color base0C  #bed6ff;
@define-color base0D  #90bee1;
@define-color base0E  #efb3f7;
@define-color base0F  #ff93b3;
"""

scss_colors = """
$base00: #2d2d2d;
$base01: #393939;
$base02: #515151;
$base03: #777777;
$base04: #b4b7b4;
$base05: #cccccc;
$base06: #e0e0e0;
$base07: #ffffff;
$base08: #ff7f7b;
$base09: #ffbf70;
$base0A: #ffd67c;
$base0B: #beda78;
$base0C: #bed6ff;
$base0D: #90bee1;
$base0E: #efb3f7;
$base0F: #ff93b3;
"""
