base00 = "f8f8f8"
base01 = "e8e8e8"
base02 = "d8d8d8"
base03 = "b8b8b8"
base04 = "585858"
base05 = "383838"
base06 = "282828"
base07 = "181818"
base08 = "ab4642"
base09 = "dc9656"
base0A = "f7ca88"
base0B = "a1b56c"
base0C = "86c1b9"
base0D = "7cafc2"
base0E = "ba8baf"
base0F = "a16946"

gtk_colors = """
@define-color base00  #f8f8f8;
@define-color base01  #e8e8e8;
@define-color base02  #d8d8d8;
@define-color base03  #b8b8b8;
@define-color base04  #585858;
@define-color base05  #383838;
@define-color base06  #282828;
@define-color base07  #181818;
@define-color base08  #ab4642;
@define-color base09  #dc9656;
@define-color base0A  #f7ca88;
@define-color base0B  #a1b56c;
@define-color base0C  #86c1b9;
@define-color base0D  #7cafc2;
@define-color base0E  #ba8baf;
@define-color base0F  #a16946;
"""

scss_colors = """
$base00: #f8f8f8;
$base01: #e8e8e8;
$base02: #d8d8d8;
$base03: #b8b8b8;
$base04: #585858;
$base05: #383838;
$base06: #282828;
$base07: #181818;
$base08: #ab4642;
$base09: #dc9656;
$base0A: #f7ca88;
$base0B: #a1b56c;
$base0C: #86c1b9;
$base0D: #7cafc2;
$base0E: #ba8baf;
$base0F: #a16946;
"""
