base00 = "e0e0e0"
base01 = "d0dad0"
base02 = "d0d0d0"
base03 = "707070"
base04 = "202020"
base05 = "000000"
base06 = "f8f8f8"
base07 = "c4d9c4"
base08 = "840000"
base09 = "006565"
base0A = "755B00"
base0B = "730073"
base0C = "755B00"
base0D = "007300"
base0E = "000090"
base0F = "755B00"

gtk_colors = """
@define-color base00  #e0e0e0;
@define-color base01  #d0dad0;
@define-color base02  #d0d0d0;
@define-color base03  #707070;
@define-color base04  #202020;
@define-color base05  #000000;
@define-color base06  #f8f8f8;
@define-color base07  #c4d9c4;
@define-color base08  #840000;
@define-color base09  #006565;
@define-color base0A  #755B00;
@define-color base0B  #730073;
@define-color base0C  #755B00;
@define-color base0D  #007300;
@define-color base0E  #000090;
@define-color base0F  #755B00;
"""

scss_colors = """
$base00: #e0e0e0;
$base01: #d0dad0;
$base02: #d0d0d0;
$base03: #707070;
$base04: #202020;
$base05: #000000;
$base06: #f8f8f8;
$base07: #c4d9c4;
$base08: #840000;
$base09: #006565;
$base0A: #755B00;
$base0B: #730073;
$base0C: #755B00;
$base0D: #007300;
$base0E: #000090;
$base0F: #755B00;
"""
