base00 = "282936"
base01 = "3a3c4e"
base02 = "4d4f68"
base03 = "626483"
base04 = "62d6e8"
base05 = "e9e9f4"
base06 = "f1f2f8"
base07 = "f7f7fb"
base08 = "ea51b2"
base09 = "b45bcf"
base0A = "00f769"
base0B = "ebff87"
base0C = "a1efe4"
base0D = "62d6e8"
base0E = "b45bcf"
base0F = "00f769"

gtk_colors = """
@define-color base00  #282936;
@define-color base01  #3a3c4e;
@define-color base02  #4d4f68;
@define-color base03  #626483;
@define-color base04  #62d6e8;
@define-color base05  #e9e9f4;
@define-color base06  #f1f2f8;
@define-color base07  #f7f7fb;
@define-color base08  #ea51b2;
@define-color base09  #b45bcf;
@define-color base0A  #00f769;
@define-color base0B  #ebff87;
@define-color base0C  #a1efe4;
@define-color base0D  #62d6e8;
@define-color base0E  #b45bcf;
@define-color base0F  #00f769;
"""

scss_colors = """
$base00: #282936;
$base01: #3a3c4e;
$base02: #4d4f68;
$base03: #626483;
$base04: #62d6e8;
$base05: #e9e9f4;
$base06: #f1f2f8;
$base07: #f7f7fb;
$base08: #ea51b2;
$base09: #b45bcf;
$base0A: #00f769;
$base0B: #ebff87;
$base0C: #a1efe4;
$base0D: #62d6e8;
$base0E: #b45bcf;
$base0F: #00f769;
"""
