base00 = "262729"
base01 = "88909f"
base02 = "b7bec9"
base03 = "3e4249"
base04 = "73b3e7"
base05 = "b7bec9"
base06 = "d390e7"
base07 = "3e4249"
base08 = "e77171"
base09 = "e77171"
base0A = "dbb774"
base0B = "a1bf78"
base0C = "5ebaa5"
base0D = "73b3e7"
base0E = "d390e7"
base0F = "5ebaa5"

gtk_colors = """
@define-color base00  #262729;
@define-color base01  #88909f;
@define-color base02  #b7bec9;
@define-color base03  #3e4249;
@define-color base04  #73b3e7;
@define-color base05  #b7bec9;
@define-color base06  #d390e7;
@define-color base07  #3e4249;
@define-color base08  #e77171;
@define-color base09  #e77171;
@define-color base0A  #dbb774;
@define-color base0B  #a1bf78;
@define-color base0C  #5ebaa5;
@define-color base0D  #73b3e7;
@define-color base0E  #d390e7;
@define-color base0F  #5ebaa5;
"""

scss_colors = """
$base00: #262729;
$base01: #88909f;
$base02: #b7bec9;
$base03: #3e4249;
$base04: #73b3e7;
$base05: #b7bec9;
$base06: #d390e7;
$base07: #3e4249;
$base08: #e77171;
$base09: #e77171;
$base0A: #dbb774;
$base0B: #a1bf78;
$base0C: #5ebaa5;
$base0D: #73b3e7;
$base0E: #d390e7;
$base0F: #5ebaa5;
"""
