base00 = "fafafa"
base01 = "7c9f4b"
base02 = "d69822"
base03 = "5e646f"
base04 = "6587bf"
base05 = "5e646f"
base06 = "b870ce"
base07 = "5e646f"
base08 = "db7070"
base09 = "db7070"
base0A = "d69822"
base0B = "7c9f4b"
base0C = "509c93"
base0D = "6587bf"
base0E = "b870ce"
base0F = "509c93"

gtk_colors = """
@define-color base00  #fafafa;
@define-color base01  #7c9f4b;
@define-color base02  #d69822;
@define-color base03  #5e646f;
@define-color base04  #6587bf;
@define-color base05  #5e646f;
@define-color base06  #b870ce;
@define-color base07  #5e646f;
@define-color base08  #db7070;
@define-color base09  #db7070;
@define-color base0A  #d69822;
@define-color base0B  #7c9f4b;
@define-color base0C  #509c93;
@define-color base0D  #6587bf;
@define-color base0E  #b870ce;
@define-color base0F  #509c93;
"""

scss_colors = """
$base00: #fafafa;
$base01: #7c9f4b;
$base02: #d69822;
$base03: #5e646f;
$base04: #6587bf;
$base05: #5e646f;
$base06: #b870ce;
$base07: #5e646f;
$base08: #db7070;
$base09: #db7070;
$base0A: #d69822;
$base0B: #7c9f4b;
$base0C: #509c93;
$base0D: #6587bf;
$base0E: #b870ce;
$base0F: #509c93;
"""
