base00 = "2d2d2d"
base01 = "393939"
base02 = "515151"
base03 = "747369"
base04 = "a09f93"
base05 = "d3d0c8"
base06 = "e8e6df"
base07 = "f2f0ec"
base08 = "f2777a"
base09 = "f99157"
base0A = "ffcc66"
base0B = "99cc99"
base0C = "66cccc"
base0D = "6699cc"
base0E = "cc99cc"
base0F = "d27b53"

gtk_colors = """
@define-color base00  #2d2d2d;
@define-color base01  #393939;
@define-color base02  #515151;
@define-color base03  #747369;
@define-color base04  #a09f93;
@define-color base05  #d3d0c8;
@define-color base06  #e8e6df;
@define-color base07  #f2f0ec;
@define-color base08  #f2777a;
@define-color base09  #f99157;
@define-color base0A  #ffcc66;
@define-color base0B  #99cc99;
@define-color base0C  #66cccc;
@define-color base0D  #6699cc;
@define-color base0E  #cc99cc;
@define-color base0F  #d27b53;
"""

scss_colors = """
$base00: #2d2d2d;
$base01: #393939;
$base02: #515151;
$base03: #747369;
$base04: #a09f93;
$base05: #d3d0c8;
$base06: #e8e6df;
$base07: #f2f0ec;
$base08: #f2777a;
$base09: #f99157;
$base0A: #ffcc66;
$base0B: #99cc99;
$base0C: #66cccc;
$base0D: #6699cc;
$base0E: #cc99cc;
$base0F: #d27b53;
"""
