base00 = "16130F"
base01 = "2C2620"
base02 = "433B32"
base03 = "5A5047"
base04 = "8A8075"
base05 = "A39A90"
base06 = "BEB6AE"
base07 = "DBD6D1"
base08 = "826D57"
base09 = "828257"
base0A = "6D8257"
base0B = "57826D"
base0C = "576D82"
base0D = "6D5782"
base0E = "82576D"
base0F = "825757"

gtk_colors = """
@define-color base00  #16130F;
@define-color base01  #2C2620;
@define-color base02  #433B32;
@define-color base03  #5A5047;
@define-color base04  #8A8075;
@define-color base05  #A39A90;
@define-color base06  #BEB6AE;
@define-color base07  #DBD6D1;
@define-color base08  #826D57;
@define-color base09  #828257;
@define-color base0A  #6D8257;
@define-color base0B  #57826D;
@define-color base0C  #576D82;
@define-color base0D  #6D5782;
@define-color base0E  #82576D;
@define-color base0F  #825757;
"""

scss_colors = """
$base00: #16130F;
$base01: #2C2620;
$base02: #433B32;
$base03: #5A5047;
$base04: #8A8075;
$base05: #A39A90;
$base06: #BEB6AE;
$base07: #DBD6D1;
$base08: #826D57;
$base09: #828257;
$base0A: #6D8257;
$base0B: #57826D;
$base0C: #576D82;
$base0D: #6D5782;
$base0E: #82576D;
$base0F: #825757;
"""
