base00 = "efefef"
base01 = "bebed2"
base02 = "9e9eaf"
base03 = "7c7c98"
base04 = "505063"
base05 = "313145"
base06 = "22223a"
base07 = "1a1a2f"
base08 = "f43979"
base09 = "d22a8b"
base0A = "ff669b"
base0B = "0073a8"
base0C = "2155d6"
base0D = "471397"
base0E = "6916b6"
base0F = "8d17a5"

gtk_colors = """
@define-color base00  #efefef;
@define-color base01  #bebed2;
@define-color base02  #9e9eaf;
@define-color base03  #7c7c98;
@define-color base04  #505063;
@define-color base05  #313145;
@define-color base06  #22223a;
@define-color base07  #1a1a2f;
@define-color base08  #f43979;
@define-color base09  #d22a8b;
@define-color base0A  #ff669b;
@define-color base0B  #0073a8;
@define-color base0C  #2155d6;
@define-color base0D  #471397;
@define-color base0E  #6916b6;
@define-color base0F  #8d17a5;
"""

scss_colors = """
$base00: #efefef;
$base01: #bebed2;
$base02: #9e9eaf;
$base03: #7c7c98;
$base04: #505063;
$base05: #313145;
$base06: #22223a;
$base07: #1a1a2f;
$base08: #f43979;
$base09: #d22a8b;
$base0A: #ff669b;
$base0B: #0073a8;
$base0C: #2155d6;
$base0D: #471397;
$base0E: #6916b6;
$base0F: #8d17a5;
"""
