base00 = "0c1118"
base01 = "181c22"
base02 = "22262d"
base03 = "7b776e"
base04 = "949088"
base05 = "afaba2"
base06 = "cac6bd"
base07 = "e7e2d9"
base08 = "f04339"
base09 = "df5923"
base0A = "bb8801"
base0B = "7f8b00"
base0C = "00948b"
base0D = "008dd1"
base0E = "6a7fd2"
base0F = "e3488e"

gtk_colors = """
@define-color base00  #0c1118;
@define-color base01  #181c22;
@define-color base02  #22262d;
@define-color base03  #7b776e;
@define-color base04  #949088;
@define-color base05  #afaba2;
@define-color base06  #cac6bd;
@define-color base07  #e7e2d9;
@define-color base08  #f04339;
@define-color base09  #df5923;
@define-color base0A  #bb8801;
@define-color base0B  #7f8b00;
@define-color base0C  #00948b;
@define-color base0D  #008dd1;
@define-color base0E  #6a7fd2;
@define-color base0F  #e3488e;
"""

scss_colors = """
$base00: #0c1118;
$base01: #181c22;
$base02: #22262d;
$base03: #7b776e;
$base04: #949088;
$base05: #afaba2;
$base06: #cac6bd;
$base07: #e7e2d9;
$base08: #f04339;
$base09: #df5923;
$base0A: #bb8801;
$base0B: #7f8b00;
$base0C: #00948b;
$base0D: #008dd1;
$base0E: #6a7fd2;
$base0F: #e3488e;
"""
