base00 = "111111"
base01 = "1b1b1b"
base02 = "262626"
base03 = "777777"
base04 = "919191"
base05 = "ababab"
base06 = "c6c6c6"
base07 = "e2e2e2"
base08 = "f04339"
base09 = "df5923"
base0A = "bb8801"
base0B = "7f8b00"
base0C = "00948b"
base0D = "008dd1"
base0E = "6a7fd2"
base0F = "e3488e"

gtk_colors = """
@define-color base00  #111111;
@define-color base01  #1b1b1b;
@define-color base02  #262626;
@define-color base03  #777777;
@define-color base04  #919191;
@define-color base05  #ababab;
@define-color base06  #c6c6c6;
@define-color base07  #e2e2e2;
@define-color base08  #f04339;
@define-color base09  #df5923;
@define-color base0A  #bb8801;
@define-color base0B  #7f8b00;
@define-color base0C  #00948b;
@define-color base0D  #008dd1;
@define-color base0E  #6a7fd2;
@define-color base0F  #e3488e;
"""

scss_colors = """
$base00: #111111;
$base01: #1b1b1b;
$base02: #262626;
$base03: #777777;
$base04: #919191;
$base05: #ababab;
$base06: #c6c6c6;
$base07: #e2e2e2;
$base08: #f04339;
$base09: #df5923;
$base0A: #bb8801;
$base0B: #7f8b00;
$base0C: #00948b;
$base0D: #008dd1;
$base0E: #6a7fd2;
$base0F: #e3488e;
"""
