base00 = "f1f1f1"
base01 = "e2e2e2"
base02 = "d4d4d4"
base03 = "777777"
base04 = "5e5e5e"
base05 = "474747"
base06 = "303030"
base07 = "1b1b1b"
base08 = "d02023"
base09 = "bf3e05"
base0A = "9d6f00"
base0B = "637200"
base0C = "007a72"
base0D = "0073b5"
base0E = "4e66b6"
base0F = "c42775"

gtk_colors = """
@define-color base00  #f1f1f1;
@define-color base01  #e2e2e2;
@define-color base02  #d4d4d4;
@define-color base03  #777777;
@define-color base04  #5e5e5e;
@define-color base05  #474747;
@define-color base06  #303030;
@define-color base07  #1b1b1b;
@define-color base08  #d02023;
@define-color base09  #bf3e05;
@define-color base0A  #9d6f00;
@define-color base0B  #637200;
@define-color base0C  #007a72;
@define-color base0D  #0073b5;
@define-color base0E  #4e66b6;
@define-color base0F  #c42775;
"""

scss_colors = """
$base00: #f1f1f1;
$base01: #e2e2e2;
$base02: #d4d4d4;
$base03: #777777;
$base04: #5e5e5e;
$base05: #474747;
$base06: #303030;
$base07: #1b1b1b;
$base08: #d02023;
$base09: #bf3e05;
$base0A: #9d6f00;
$base0B: #637200;
$base0C: #007a72;
$base0D: #0073b5;
$base0E: #4e66b6;
$base0F: #c42775;
"""
