base00 = "f5f0e7"
base01 = "e7e2d9"
base02 = "d8d4cb"
base03 = "73777f"
base04 = "5a5f66"
base05 = "43474e"
base06 = "2c3138"
base07 = "181c22"
base08 = "d02023"
base09 = "bf3e05"
base0A = "9d6f00"
base0B = "637200"
base0C = "007a72"
base0D = "0073b5"
base0E = "4e66b6"
base0F = "c42775"

gtk_colors = """
@define-color base00  #f5f0e7;
@define-color base01  #e7e2d9;
@define-color base02  #d8d4cb;
@define-color base03  #73777f;
@define-color base04  #5a5f66;
@define-color base05  #43474e;
@define-color base06  #2c3138;
@define-color base07  #181c22;
@define-color base08  #d02023;
@define-color base09  #bf3e05;
@define-color base0A  #9d6f00;
@define-color base0B  #637200;
@define-color base0C  #007a72;
@define-color base0D  #0073b5;
@define-color base0E  #4e66b6;
@define-color base0F  #c42775;
"""

scss_colors = """
$base00: #f5f0e7;
$base01: #e7e2d9;
$base02: #d8d4cb;
$base03: #73777f;
$base04: #5a5f66;
$base05: #43474e;
$base06: #2c3138;
$base07: #181c22;
$base08: #d02023;
$base09: #bf3e05;
$base0A: #9d6f00;
$base0B: #637200;
$base0C: #007a72;
$base0D: #0073b5;
$base0E: #4e66b6;
$base0F: #c42775;
"""
