base00 = "0a0920"
base01 = "13133a"
base02 = "23255a"
base03 = "333773"
base04 = "4a5293"
base05 = "606bac"
base06 = "7986c5"
base07 = "9aaae5"
base08 = "f768a3"
base09 = "f768a3"
base0A = "faaea2"
base0B = "faaea2"
base0C = "258fc4"
base0D = "258fc4"
base0E = "f768a3"
base0F = "f768a3"

gtk_colors = """
@define-color base00  #0a0920;
@define-color base01  #13133a;
@define-color base02  #23255a;
@define-color base03  #333773;
@define-color base04  #4a5293;
@define-color base05  #606bac;
@define-color base06  #7986c5;
@define-color base07  #9aaae5;
@define-color base08  #f768a3;
@define-color base09  #f768a3;
@define-color base0A  #faaea2;
@define-color base0B  #faaea2;
@define-color base0C  #258fc4;
@define-color base0D  #258fc4;
@define-color base0E  #f768a3;
@define-color base0F  #f768a3;
"""

scss_colors = """
$base00: #0a0920;
$base01: #13133a;
$base02: #23255a;
$base03: #333773;
$base04: #4a5293;
$base05: #606bac;
$base06: #7986c5;
$base07: #9aaae5;
$base08: #f768a3;
$base09: #f768a3;
$base0A: #faaea2;
$base0B: #faaea2;
$base0C: #258fc4;
$base0D: #258fc4;
$base0E: #f768a3;
$base0F: #f768a3;
"""
