base00 = "2d2d2d"
base01 = "393939"
base02 = "515151"
base03 = "777777"
base04 = "b4b7b4"
base05 = "cccccc"
base06 = "e0e0e0"
base07 = "ffffff"
base08 = "d25252"
base09 = "f9a959"
base0A = "ffc66d"
base0B = "a5c261"
base0C = "bed6ff"
base0D = "6c99bb"
base0E = "d197d9"
base0F = "f97394"

gtk_colors = """
@define-color base00  #2d2d2d;
@define-color base01  #393939;
@define-color base02  #515151;
@define-color base03  #777777;
@define-color base04  #b4b7b4;
@define-color base05  #cccccc;
@define-color base06  #e0e0e0;
@define-color base07  #ffffff;
@define-color base08  #d25252;
@define-color base09  #f9a959;
@define-color base0A  #ffc66d;
@define-color base0B  #a5c261;
@define-color base0C  #bed6ff;
@define-color base0D  #6c99bb;
@define-color base0E  #d197d9;
@define-color base0F  #f97394;
"""

scss_colors = """
$base00: #2d2d2d;
$base01: #393939;
$base02: #515151;
$base03: #777777;
$base04: #b4b7b4;
$base05: #cccccc;
$base06: #e0e0e0;
$base07: #ffffff;
$base08: #d25252;
$base09: #f9a959;
$base0A: #ffc66d;
$base0B: #a5c261;
$base0C: #bed6ff;
$base0D: #6c99bb;
$base0E: #d197d9;
$base0F: #f97394;
"""
