base00 = "000000"
base01 = "202020"
base02 = "303030"
base03 = "505050"
base04 = "b0b0b0"
base05 = "d0d0d0"
base06 = "e0e0e0"
base07 = "ffffff"
base08 = "f5708a"
base09 = "ee8122"
base0A = "b8a300"
base0B = "54bc5c"
base0C = "00bab3"
base0D = "00aff2"
base0E = "9095ff"
base0F = "d47ada"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #202020;
@define-color base02  #303030;
@define-color base03  #505050;
@define-color base04  #b0b0b0;
@define-color base05  #d0d0d0;
@define-color base06  #e0e0e0;
@define-color base07  #ffffff;
@define-color base08  #f5708a;
@define-color base09  #ee8122;
@define-color base0A  #b8a300;
@define-color base0B  #54bc5c;
@define-color base0C  #00bab3;
@define-color base0D  #00aff2;
@define-color base0E  #9095ff;
@define-color base0F  #d47ada;
"""

scss_colors = """
$base00: #000000;
$base01: #202020;
$base02: #303030;
$base03: #505050;
$base04: #b0b0b0;
$base05: #d0d0d0;
$base06: #e0e0e0;
$base07: #ffffff;
$base08: #f5708a;
$base09: #ee8122;
$base0A: #b8a300;
$base0B: #54bc5c;
$base0C: #00bab3;
$base0D: #00aff2;
$base0E: #9095ff;
$base0F: #d47ada;
"""
