base00 = "272e33"
base01 = "2e383c"
base02 = "414b50"
base03 = "859289"
base04 = "9da9a0"
base05 = "d3c6aa"
base06 = "e4e1cd"
base07 = "fdf6e3"
base08 = "7fbbb3"
base09 = "d699b6"
base0A = "dbbc7f"
base0B = "83c092"
base0C = "e69875"
base0D = "a7c080"
base0E = "e67e80"
base0F = "4C3743"

gtk_colors = """
@define-color base00  #272e33;
@define-color base01  #2e383c;
@define-color base02  #414b50;
@define-color base03  #859289;
@define-color base04  #9da9a0;
@define-color base05  #d3c6aa;
@define-color base06  #e4e1cd;
@define-color base07  #fdf6e3;
@define-color base08  #7fbbb3;
@define-color base09  #d699b6;
@define-color base0A  #dbbc7f;
@define-color base0B  #83c092;
@define-color base0C  #e69875;
@define-color base0D  #a7c080;
@define-color base0E  #e67e80;
@define-color base0F  #4C3743;
"""

scss_colors = """
$base00: #272e33;
$base01: #2e383c;
$base02: #414b50;
$base03: #859289;
$base04: #9da9a0;
$base05: #d3c6aa;
$base06: #e4e1cd;
$base07: #fdf6e3;
$base08: #7fbbb3;
$base09: #d699b6;
$base0A: #dbbc7f;
$base0B: #83c092;
$base0C: #e69875;
$base0D: #a7c080;
$base0E: #e67e80;
$base0F: #4C3743;
"""
