base00 = "202126"
base01 = "2d303d"
base02 = "5a576e"
base03 = "a1d2e6"
base04 = "cad3ff"
base05 = "e9e7e1"
base06 = "eff0f9"
base07 = "f2fbff"
base08 = "ff661a"
base09 = "19f988"
base0A = "ffdc2d"
base0B = "f2e6a9"
base0C = "fb6acb"
base0D = "40bfff"
base0E = "ae94f9"
base0F = "6187ff"

gtk_colors = """
@define-color base00  #202126;
@define-color base01  #2d303d;
@define-color base02  #5a576e;
@define-color base03  #a1d2e6;
@define-color base04  #cad3ff;
@define-color base05  #e9e7e1;
@define-color base06  #eff0f9;
@define-color base07  #f2fbff;
@define-color base08  #ff661a;
@define-color base09  #19f988;
@define-color base0A  #ffdc2d;
@define-color base0B  #f2e6a9;
@define-color base0C  #fb6acb;
@define-color base0D  #40bfff;
@define-color base0E  #ae94f9;
@define-color base0F  #6187ff;
"""

scss_colors = """
$base00: #202126;
$base01: #2d303d;
$base02: #5a576e;
$base03: #a1d2e6;
$base04: #cad3ff;
$base05: #e9e7e1;
$base06: #eff0f9;
$base07: #f2fbff;
$base08: #ff661a;
$base09: #19f988;
$base0A: #ffdc2d;
$base0B: #f2e6a9;
$base0C: #fb6acb;
$base0D: #40bfff;
$base0E: #ae94f9;
$base0F: #6187ff;
"""
