base00 = "ffffff"
base01 = "f5f5f5"
base02 = "c8c8fa"
base03 = "969896"
base04 = "e8e8e8"
base05 = "333333"
base06 = "ffffff"
base07 = "ffffff"
base08 = "ed6a43"
base09 = "0086b3"
base0A = "795da3"
base0B = "183691"
base0C = "183691"
base0D = "795da3"
base0E = "a71d5d"
base0F = "333333"

gtk_colors = """
@define-color base00  #ffffff;
@define-color base01  #f5f5f5;
@define-color base02  #c8c8fa;
@define-color base03  #969896;
@define-color base04  #e8e8e8;
@define-color base05  #333333;
@define-color base06  #ffffff;
@define-color base07  #ffffff;
@define-color base08  #ed6a43;
@define-color base09  #0086b3;
@define-color base0A  #795da3;
@define-color base0B  #183691;
@define-color base0C  #183691;
@define-color base0D  #795da3;
@define-color base0E  #a71d5d;
@define-color base0F  #333333;
"""

scss_colors = """
$base00: #ffffff;
$base01: #f5f5f5;
$base02: #c8c8fa;
$base03: #969896;
$base04: #e8e8e8;
$base05: #333333;
$base06: #ffffff;
$base07: #ffffff;
$base08: #ed6a43;
$base09: #0086b3;
$base0A: #795da3;
$base0B: #183691;
$base0C: #183691;
$base0D: #795da3;
$base0E: #a71d5d;
$base0F: #333333;
"""
