base00 = "ffffff"
base01 = "e0e0e0"
base02 = "c5c8c6"
base03 = "b4b7b4"
base04 = "969896"
base05 = "373b41"
base06 = "282a2e"
base07 = "1d1f21"
base08 = "CC342B"
base09 = "F96A38"
base0A = "FBA922"
base0B = "198844"
base0C = "3971ED"
base0D = "3971ED"
base0E = "A36AC7"
base0F = "3971ED"

gtk_colors = """
@define-color base00  #ffffff;
@define-color base01  #e0e0e0;
@define-color base02  #c5c8c6;
@define-color base03  #b4b7b4;
@define-color base04  #969896;
@define-color base05  #373b41;
@define-color base06  #282a2e;
@define-color base07  #1d1f21;
@define-color base08  #CC342B;
@define-color base09  #F96A38;
@define-color base0A  #FBA922;
@define-color base0B  #198844;
@define-color base0C  #3971ED;
@define-color base0D  #3971ED;
@define-color base0E  #A36AC7;
@define-color base0F  #3971ED;
"""

scss_colors = """
$base00: #ffffff;
$base01: #e0e0e0;
$base02: #c5c8c6;
$base03: #b4b7b4;
$base04: #969896;
$base05: #373b41;
$base06: #282a2e;
$base07: #1d1f21;
$base08: #CC342B;
$base09: #F96A38;
$base0A: #FBA922;
$base0B: #198844;
$base0C: #3971ED;
$base0D: #3971ED;
$base0E: #A36AC7;
$base0F: #3971ED;
"""
