base00 = "0c1014"
base01 = "11151c"
base02 = "091f2e"
base03 = "0a3749"
base04 = "245361"
base05 = "599cab"
base06 = "99d1ce"
base07 = "d3ebe9"
base08 = "c23127"
base09 = "d26937"
base0A = "edb443"
base0B = "33859E"
base0C = "2aa889"
base0D = "195466"
base0E = "888ca6"
base0F = "4e5166"

gtk_colors = """
@define-color base00  #0c1014;
@define-color base01  #11151c;
@define-color base02  #091f2e;
@define-color base03  #0a3749;
@define-color base04  #245361;
@define-color base05  #599cab;
@define-color base06  #99d1ce;
@define-color base07  #d3ebe9;
@define-color base08  #c23127;
@define-color base09  #d26937;
@define-color base0A  #edb443;
@define-color base0B  #33859E;
@define-color base0C  #2aa889;
@define-color base0D  #195466;
@define-color base0E  #888ca6;
@define-color base0F  #4e5166;
"""

scss_colors = """
$base00: #0c1014;
$base01: #11151c;
$base02: #091f2e;
$base03: #0a3749;
$base04: #245361;
$base05: #599cab;
$base06: #99d1ce;
$base07: #d3ebe9;
$base08: #c23127;
$base09: #d26937;
$base0A: #edb443;
$base0B: #33859E;
$base0C: #2aa889;
$base0D: #195466;
$base0E: #888ca6;
$base0F: #4e5166;
"""
