base00 = "181818"
base01 = "453d41"
base02 = "484848"
base03 = "52494e"
base04 = "e4e4ef"
base05 = "f4f4ff"
base06 = "f5f5f5"
base07 = "e4e4ef"
base08 = "f43841"
base09 = "c73c3f"
base0A = "ffdd33"
base0B = "73c936"
base0C = "95a99f"
base0D = "96a6c8"
base0E = "9e95c7"
base0F = "cc8c3c"

gtk_colors = """
@define-color base00  #181818;
@define-color base01  #453d41;
@define-color base02  #484848;
@define-color base03  #52494e;
@define-color base04  #e4e4ef;
@define-color base05  #f4f4ff;
@define-color base06  #f5f5f5;
@define-color base07  #e4e4ef;
@define-color base08  #f43841;
@define-color base09  #c73c3f;
@define-color base0A  #ffdd33;
@define-color base0B  #73c936;
@define-color base0C  #95a99f;
@define-color base0D  #96a6c8;
@define-color base0E  #9e95c7;
@define-color base0F  #cc8c3c;
"""

scss_colors = """
$base00: #181818;
$base01: #453d41;
$base02: #484848;
$base03: #52494e;
$base04: #e4e4ef;
$base05: #f4f4ff;
$base06: #f5f5f5;
$base07: #e4e4ef;
$base08: #f43841;
$base09: #c73c3f;
$base0A: #ffdd33;
$base0B: #73c936;
$base0C: #95a99f;
$base0D: #96a6c8;
$base0E: #9e95c7;
$base0F: #cc8c3c;
"""
