base00 = "fbf1c7"
base01 = "f2e5bc"
base02 = "d5c4a1"
base03 = "bdae93"
base04 = "665c54"
base05 = "654735"
base06 = "3c3836"
base07 = "282828"
base08 = "c14a4a"
base09 = "c35e0a"
base0A = "b47109"
base0B = "6c782e"
base0C = "4c7a5d"
base0D = "45707a"
base0E = "945e80"
base0F = "e78a4e"

gtk_colors = """
@define-color base00  #fbf1c7;
@define-color base01  #f2e5bc;
@define-color base02  #d5c4a1;
@define-color base03  #bdae93;
@define-color base04  #665c54;
@define-color base05  #654735;
@define-color base06  #3c3836;
@define-color base07  #282828;
@define-color base08  #c14a4a;
@define-color base09  #c35e0a;
@define-color base0A  #b47109;
@define-color base0B  #6c782e;
@define-color base0C  #4c7a5d;
@define-color base0D  #45707a;
@define-color base0E  #945e80;
@define-color base0F  #e78a4e;
"""

scss_colors = """
$base00: #fbf1c7;
$base01: #f2e5bc;
$base02: #d5c4a1;
$base03: #bdae93;
$base04: #665c54;
$base05: #654735;
$base06: #3c3836;
$base07: #282828;
$base08: #c14a4a;
$base09: #c35e0a;
$base0A: #b47109;
$base0B: #6c782e;
$base0C: #4c7a5d;
$base0D: #45707a;
$base0E: #945e80;
$base0F: #e78a4e;
"""
