base00 = "32302f"
base01 = "3c3836"
base02 = "5a524c"
base03 = "7c6f64"
base04 = "bdae93"
base05 = "ddc7a1"
base06 = "ebdbb2"
base07 = "fbf1c7"
base08 = "ea6962"
base09 = "e78a4e"
base0A = "d8a657"
base0B = "a9b665"
base0C = "89b482"
base0D = "7daea3"
base0E = "d3869b"
base0F = "bd6f3e"

gtk_colors = """
@define-color base00  #32302f;
@define-color base01  #3c3836;
@define-color base02  #5a524c;
@define-color base03  #7c6f64;
@define-color base04  #bdae93;
@define-color base05  #ddc7a1;
@define-color base06  #ebdbb2;
@define-color base07  #fbf1c7;
@define-color base08  #ea6962;
@define-color base09  #e78a4e;
@define-color base0A  #d8a657;
@define-color base0B  #a9b665;
@define-color base0C  #89b482;
@define-color base0D  #7daea3;
@define-color base0E  #d3869b;
@define-color base0F  #bd6f3e;
"""

scss_colors = """
$base00: #32302f;
$base01: #3c3836;
$base02: #5a524c;
$base03: #7c6f64;
$base04: #bdae93;
$base05: #ddc7a1;
$base06: #ebdbb2;
$base07: #fbf1c7;
$base08: #ea6962;
$base09: #e78a4e;
$base0A: #d8a657;
$base0B: #a9b665;
$base0C: #89b482;
$base0D: #7daea3;
$base0E: #d3869b;
$base0F: #bd6f3e;
"""
