base00 = "1d2021"
base01 = "3c3836"
base02 = "504945"
base03 = "665c54"
base04 = "bdae93"
base05 = "d5c4a1"
base06 = "ebdbb2"
base07 = "fbf1c7"
base08 = "fb4934"
base09 = "fe8019"
base0A = "fabd2f"
base0B = "b8bb26"
base0C = "8ec07c"
base0D = "83a598"
base0E = "d3869b"
base0F = "d65d0e"

gtk_colors = """
@define-color base00  #1d2021;
@define-color base01  #3c3836;
@define-color base02  #504945;
@define-color base03  #665c54;
@define-color base04  #bdae93;
@define-color base05  #d5c4a1;
@define-color base06  #ebdbb2;
@define-color base07  #fbf1c7;
@define-color base08  #fb4934;
@define-color base09  #fe8019;
@define-color base0A  #fabd2f;
@define-color base0B  #b8bb26;
@define-color base0C  #8ec07c;
@define-color base0D  #83a598;
@define-color base0E  #d3869b;
@define-color base0F  #d65d0e;
"""

scss_colors = """
$base00: #1d2021;
$base01: #3c3836;
$base02: #504945;
$base03: #665c54;
$base04: #bdae93;
$base05: #d5c4a1;
$base06: #ebdbb2;
$base07: #fbf1c7;
$base08: #fb4934;
$base09: #fe8019;
$base0A: #fabd2f;
$base0B: #b8bb26;
$base0C: #8ec07c;
$base0D: #83a598;
$base0E: #d3869b;
$base0F: #d65d0e;
"""
