base00 = "f9f5d7"
base01 = "fbf1c7"
base02 = "e0cfa9"
base03 = "a89984"
base04 = "c9b99a"
base05 = "654735"
base06 = "3c3836"
base07 = "282828"
base08 = "c14a4a"
base09 = "c35e0a"
base0A = "b47109"
base0B = "6c782e"
base0C = "4c7a5d"
base0D = "45707a"
base0E = "945e80"
base0F = "e78a4e"

gtk_colors = """
@define-color base00  #f9f5d7;
@define-color base01  #fbf1c7;
@define-color base02  #e0cfa9;
@define-color base03  #a89984;
@define-color base04  #c9b99a;
@define-color base05  #654735;
@define-color base06  #3c3836;
@define-color base07  #282828;
@define-color base08  #c14a4a;
@define-color base09  #c35e0a;
@define-color base0A  #b47109;
@define-color base0B  #6c782e;
@define-color base0C  #4c7a5d;
@define-color base0D  #45707a;
@define-color base0E  #945e80;
@define-color base0F  #e78a4e;
"""

scss_colors = """
$base00: #f9f5d7;
$base01: #fbf1c7;
$base02: #e0cfa9;
$base03: #a89984;
$base04: #c9b99a;
$base05: #654735;
$base06: #3c3836;
$base07: #282828;
$base08: #c14a4a;
$base09: #c35e0a;
$base0A: #b47109;
$base0B: #6c782e;
$base0C: #4c7a5d;
$base0D: #45707a;
$base0E: #945e80;
$base0F: #e78a4e;
"""
