base00 = "212121"
base01 = "303030"
base02 = "353535"
base03 = "4A4A4A"
base04 = "707070"
base05 = "cdcdcd"
base06 = "e5e5e5"
base07 = "ffffff"
base08 = "f92672"
base09 = "fd971f"
base0A = "e6db74"
base0B = "a6e22e"
base0C = "708387"
base0D = "66d9ef"
base0E = "9e6ffe"
base0F = "e8b882"

gtk_colors = """
@define-color base00  #212121;
@define-color base01  #303030;
@define-color base02  #353535;
@define-color base03  #4A4A4A;
@define-color base04  #707070;
@define-color base05  #cdcdcd;
@define-color base06  #e5e5e5;
@define-color base07  #ffffff;
@define-color base08  #f92672;
@define-color base09  #fd971f;
@define-color base0A  #e6db74;
@define-color base0B  #a6e22e;
@define-color base0C  #708387;
@define-color base0D  #66d9ef;
@define-color base0E  #9e6ffe;
@define-color base0F  #e8b882;
"""

scss_colors = """
$base00: #212121;
$base01: #303030;
$base02: #353535;
$base03: #4A4A4A;
$base04: #707070;
$base05: #cdcdcd;
$base06: #e5e5e5;
$base07: #ffffff;
$base08: #f92672;
$base09: #fd971f;
$base0A: #e6db74;
$base0B: #a6e22e;
$base0C: #708387;
$base0D: #66d9ef;
$base0E: #9e6ffe;
$base0F: #e8b882;
"""
