base00 = "190134"
base01 = "392551"
base02 = "5A496E"
base03 = "7B6D8B"
base04 = "9C92A8"
base05 = "BDB6C5"
base06 = "DEDAE2"
base07 = "FEFFFF"
base08 = "27D9D5"
base09 = "5BA2B6"
base0A = "8F6C97"
base0B = "C33678"
base0C = "F80059"
base0D = "BD0152"
base0E = "82034C"
base0F = "470546"

gtk_colors = """
@define-color base00  #190134;
@define-color base01  #392551;
@define-color base02  #5A496E;
@define-color base03  #7B6D8B;
@define-color base04  #9C92A8;
@define-color base05  #BDB6C5;
@define-color base06  #DEDAE2;
@define-color base07  #FEFFFF;
@define-color base08  #27D9D5;
@define-color base09  #5BA2B6;
@define-color base0A  #8F6C97;
@define-color base0B  #C33678;
@define-color base0C  #F80059;
@define-color base0D  #BD0152;
@define-color base0E  #82034C;
@define-color base0F  #470546;
"""

scss_colors = """
$base00: #190134;
$base01: #392551;
$base02: #5A496E;
$base03: #7B6D8B;
$base04: #9C92A8;
$base05: #BDB6C5;
$base06: #DEDAE2;
$base07: #FEFFFF;
$base08: #27D9D5;
$base09: #5BA2B6;
$base0A: #8F6C97;
$base0B: #C33678;
$base0C: #F80059;
$base0D: #BD0152;
$base0E: #82034C;
$base0F: #470546;
"""
