base00 = "feffff"
base01 = "392551"
base02 = "7b6d8b"
base03 = "9c92a8"
base04 = "ddd6e5"
base05 = "5a496e"
base06 = "470546"
base07 = "190134"
base08 = "27d9d5"
base09 = "bdb6c5"
base0A = "5ba2b6"
base0B = "f80059"
base0C = "c33678"
base0D = "47f9f5"
base0E = "bd0152"
base0F = "dedae2"

gtk_colors = """
@define-color base00  #feffff;
@define-color base01  #392551;
@define-color base02  #7b6d8b;
@define-color base03  #9c92a8;
@define-color base04  #ddd6e5;
@define-color base05  #5a496e;
@define-color base06  #470546;
@define-color base07  #190134;
@define-color base08  #27d9d5;
@define-color base09  #bdb6c5;
@define-color base0A  #5ba2b6;
@define-color base0B  #f80059;
@define-color base0C  #c33678;
@define-color base0D  #47f9f5;
@define-color base0E  #bd0152;
@define-color base0F  #dedae2;
"""

scss_colors = """
$base00: #feffff;
$base01: #392551;
$base02: #7b6d8b;
$base03: #9c92a8;
$base04: #ddd6e5;
$base05: #5a496e;
$base06: #470546;
$base07: #190134;
$base08: #27d9d5;
$base09: #bdb6c5;
$base0A: #5ba2b6;
$base0B: #f80059;
$base0C: #c33678;
$base0D: #47f9f5;
$base0E: #bd0152;
$base0F: #dedae2;
"""
