base00 = "1d2021"
base01 = "383c3e"
base02 = "53585b"
base03 = "6f7579"
base04 = "cdcdcd"
base05 = "d5d5d5"
base06 = "dddddd"
base07 = "e5e5e5"
base08 = "d72638"
base09 = "eb8413"
base0A = "f19d1a"
base0B = "88b92d"
base0C = "1ba595"
base0D = "1e8bac"
base0E = "be4264"
base0F = "c85e0d"

gtk_colors = """
@define-color base00  #1d2021;
@define-color base01  #383c3e;
@define-color base02  #53585b;
@define-color base03  #6f7579;
@define-color base04  #cdcdcd;
@define-color base05  #d5d5d5;
@define-color base06  #dddddd;
@define-color base07  #e5e5e5;
@define-color base08  #d72638;
@define-color base09  #eb8413;
@define-color base0A  #f19d1a;
@define-color base0B  #88b92d;
@define-color base0C  #1ba595;
@define-color base0D  #1e8bac;
@define-color base0E  #be4264;
@define-color base0F  #c85e0d;
"""

scss_colors = """
$base00: #1d2021;
$base01: #383c3e;
$base02: #53585b;
$base03: #6f7579;
$base04: #cdcdcd;
$base05: #d5d5d5;
$base06: #dddddd;
$base07: #e5e5e5;
$base08: #d72638;
$base09: #eb8413;
$base0A: #f19d1a;
$base0B: #88b92d;
$base0C: #1ba595;
$base0D: #1e8bac;
$base0E: #be4264;
$base0F: #c85e0d;
"""
