base00 = "FDF0ED"
base01 = "FADAD1"
base02 = "F9CBBE"
base03 = "BDB3B1"
base04 = "948C8A"
base05 = "403C3D"
base06 = "302C2D"
base07 = "201C1D"
base08 = "E95678"
base09 = "F9CEC3"
base0A = "FADAD1"
base0B = "29D398"
base0C = "59E1E3"
base0D = "26BBD9"
base0E = "EE64AC"
base0F = "F9CBBE"

gtk_colors = """
@define-color base00  #FDF0ED;
@define-color base01  #FADAD1;
@define-color base02  #F9CBBE;
@define-color base03  #BDB3B1;
@define-color base04  #948C8A;
@define-color base05  #403C3D;
@define-color base06  #302C2D;
@define-color base07  #201C1D;
@define-color base08  #E95678;
@define-color base09  #F9CEC3;
@define-color base0A  #FADAD1;
@define-color base0B  #29D398;
@define-color base0C  #59E1E3;
@define-color base0D  #26BBD9;
@define-color base0E  #EE64AC;
@define-color base0F  #F9CBBE;
"""

scss_colors = """
$base00: #FDF0ED;
$base01: #FADAD1;
$base02: #F9CBBE;
$base03: #BDB3B1;
$base04: #948C8A;
$base05: #403C3D;
$base06: #302C2D;
$base07: #201C1D;
$base08: #E95678;
$base09: #F9CEC3;
$base0A: #FADAD1;
$base0B: #29D398;
$base0C: #59E1E3;
$base0D: #26BBD9;
$base0E: #EE64AC;
$base0F: #F9CBBE;
"""
