base00 = "FDF0ED"
base01 = "FADAD1"
base02 = "F9CBBE"
base03 = "BDB3B1"
base04 = "948C8A"
base05 = "403C3D"
base06 = "302C2D"
base07 = "201C1D"
base08 = "F7939B"
base09 = "F6661E"
base0A = "FBE0D9"
base0B = "94E1B0"
base0C = "DC3318"
base0D = "DA103F"
base0E = "1D8991"
base0F = "E58C92"

gtk_colors = """
@define-color base00  #FDF0ED;
@define-color base01  #FADAD1;
@define-color base02  #F9CBBE;
@define-color base03  #BDB3B1;
@define-color base04  #948C8A;
@define-color base05  #403C3D;
@define-color base06  #302C2D;
@define-color base07  #201C1D;
@define-color base08  #F7939B;
@define-color base09  #F6661E;
@define-color base0A  #FBE0D9;
@define-color base0B  #94E1B0;
@define-color base0C  #DC3318;
@define-color base0D  #DA103F;
@define-color base0E  #1D8991;
@define-color base0F  #E58C92;
"""

scss_colors = """
$base00: #FDF0ED;
$base01: #FADAD1;
$base02: #F9CBBE;
$base03: #BDB3B1;
$base04: #948C8A;
$base05: #403C3D;
$base06: #302C2D;
$base07: #201C1D;
$base08: #F7939B;
$base09: #F6661E;
$base0A: #FBE0D9;
$base0B: #94E1B0;
$base0C: #DC3318;
$base0D: #DA103F;
$base0E: #1D8991;
$base0F: #E58C92;
"""
