base00 = "1C1E26"
base01 = "232530"
base02 = "2E303E"
base03 = "6F6F70"
base04 = "9DA0A2"
base05 = "CBCED0"
base06 = "DCDFE4"
base07 = "E3E6EE"
base08 = "E95678"
base09 = "FAB795"
base0A = "FAC29A"
base0B = "29D398"
base0C = "59E1E3"
base0D = "26BBD9"
base0E = "EE64AC"
base0F = "F09383"

gtk_colors = """
@define-color base00  #1C1E26;
@define-color base01  #232530;
@define-color base02  #2E303E;
@define-color base03  #6F6F70;
@define-color base04  #9DA0A2;
@define-color base05  #CBCED0;
@define-color base06  #DCDFE4;
@define-color base07  #E3E6EE;
@define-color base08  #E95678;
@define-color base09  #FAB795;
@define-color base0A  #FAC29A;
@define-color base0B  #29D398;
@define-color base0C  #59E1E3;
@define-color base0D  #26BBD9;
@define-color base0E  #EE64AC;
@define-color base0F  #F09383;
"""

scss_colors = """
$base00: #1C1E26;
$base01: #232530;
$base02: #2E303E;
$base03: #6F6F70;
$base04: #9DA0A2;
$base05: #CBCED0;
$base06: #DCDFE4;
$base07: #E3E6EE;
$base08: #E95678;
$base09: #FAB795;
$base0A: #FAC29A;
$base0B: #29D398;
$base0C: #59E1E3;
$base0D: #26BBD9;
$base0E: #EE64AC;
$base0F: #F09383;
"""
