base00 = "f8f8f2"
base01 = "efefe9"
base02 = "deded8"
base03 = "c0c0bd"
base04 = "60615d"
base05 = "232629"
base06 = "2f3337"
base07 = "070708"
base08 = "b0151a"
base09 = "ff3d00"
base0A = "ffb627"
base0B = "388e3c"
base0C = "008e8e"
base0D = "0082c9"
base0E = "700f98"
base0F = "b27701"

gtk_colors = """
@define-color base00  #f8f8f2;
@define-color base01  #efefe9;
@define-color base02  #deded8;
@define-color base03  #c0c0bd;
@define-color base04  #60615d;
@define-color base05  #232629;
@define-color base06  #2f3337;
@define-color base07  #070708;
@define-color base08  #b0151a;
@define-color base09  #ff3d00;
@define-color base0A  #ffb627;
@define-color base0B  #388e3c;
@define-color base0C  #008e8e;
@define-color base0D  #0082c9;
@define-color base0E  #700f98;
@define-color base0F  #b27701;
"""

scss_colors = """
$base00: #f8f8f2;
$base01: #efefe9;
$base02: #deded8;
$base03: #c0c0bd;
$base04: #60615d;
$base05: #232629;
$base06: #2f3337;
$base07: #070708;
$base08: #b0151a;
$base09: #ff3d00;
$base0A: #ffb627;
$base0B: #388e3c;
$base0C: #008e8e;
$base0D: #0082c9;
$base0E: #700f98;
$base0F: #b27701;
"""
