base00 = "232629"
base01 = "333b3d"
base02 = "484e54"
base03 = "60615d"
base04 = "c0c0bd"
base05 = "f8f8f2"
base06 = "fcfcf6"
base07 = "fcfcfc"
base08 = "f11235"
base09 = "ff9505"
base0A = "ffb627"
base0B = "02d849"
base0C = "0dd9d6"
base0D = "00a6fb"
base0E = "f15ee3"
base0F = "b27701"

gtk_colors = """
@define-color base00  #232629;
@define-color base01  #333b3d;
@define-color base02  #484e54;
@define-color base03  #60615d;
@define-color base04  #c0c0bd;
@define-color base05  #f8f8f2;
@define-color base06  #fcfcf6;
@define-color base07  #fcfcfc;
@define-color base08  #f11235;
@define-color base09  #ff9505;
@define-color base0A  #ffb627;
@define-color base0B  #02d849;
@define-color base0C  #0dd9d6;
@define-color base0D  #00a6fb;
@define-color base0E  #f15ee3;
@define-color base0F  #b27701;
"""

scss_colors = """
$base00: #232629;
$base01: #333b3d;
$base02: #484e54;
$base03: #60615d;
$base04: #c0c0bd;
$base05: #f8f8f2;
$base06: #fcfcf6;
$base07: #fcfcfc;
$base08: #f11235;
$base09: #ff9505;
$base0A: #ffb627;
$base0B: #02d849;
$base0C: #0dd9d6;
$base0D: #00a6fb;
$base0E: #f15ee3;
$base0F: #b27701;
"""
