base00 = "f6f6f6"
base01 = "dedede"
base02 = "bde5f2"
base03 = "898989"
base04 = "767676"
base05 = "181818"
base06 = "e8e8e8"
base07 = "f8f8f8"
base08 = "9c5a02"
base09 = "c43e18"
base0A = "c48218"
base0B = "38781c"
base0C = "2d6bb1"
base0D = "48bac2"
base0E = "a94598"
base0F = "8b6c37"

gtk_colors = """
@define-color base00  #f6f6f6;
@define-color base01  #dedede;
@define-color base02  #bde5f2;
@define-color base03  #898989;
@define-color base04  #767676;
@define-color base05  #181818;
@define-color base06  #e8e8e8;
@define-color base07  #f8f8f8;
@define-color base08  #9c5a02;
@define-color base09  #c43e18;
@define-color base0A  #c48218;
@define-color base0B  #38781c;
@define-color base0C  #2d6bb1;
@define-color base0D  #48bac2;
@define-color base0E  #a94598;
@define-color base0F  #8b6c37;
"""

scss_colors = """
$base00: #f6f6f6;
$base01: #dedede;
$base02: #bde5f2;
$base03: #898989;
$base04: #767676;
$base05: #181818;
$base06: #e8e8e8;
$base07: #f8f8f8;
$base08: #9c5a02;
$base09: #c43e18;
$base0A: #c48218;
$base0B: #38781c;
$base0C: #2d6bb1;
$base0D: #48bac2;
$base0E: #a94598;
$base0F: #8b6c37;
"""
