base00 = "000000"
base01 = "242422"
base02 = "484844"
base03 = "6c6c66"
base04 = "918f88"
base05 = "b5b3aa"
base06 = "d9d7cc"
base07 = "fdfbee"
base08 = "ff6c60"
base09 = "e9c062"
base0A = "ffffb6"
base0B = "a8ff60"
base0C = "c6c5fe"
base0D = "96cbfe"
base0E = "ff73fd"
base0F = "b18a3d"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #242422;
@define-color base02  #484844;
@define-color base03  #6c6c66;
@define-color base04  #918f88;
@define-color base05  #b5b3aa;
@define-color base06  #d9d7cc;
@define-color base07  #fdfbee;
@define-color base08  #ff6c60;
@define-color base09  #e9c062;
@define-color base0A  #ffffb6;
@define-color base0B  #a8ff60;
@define-color base0C  #c6c5fe;
@define-color base0D  #96cbfe;
@define-color base0E  #ff73fd;
@define-color base0F  #b18a3d;
"""

scss_colors = """
$base00: #000000;
$base01: #242422;
$base02: #484844;
$base03: #6c6c66;
$base04: #918f88;
$base05: #b5b3aa;
$base06: #d9d7cc;
$base07: #fdfbee;
$base08: #ff6c60;
$base09: #e9c062;
$base0A: #ffffb6;
$base0B: #a8ff60;
$base0C: #c6c5fe;
$base0D: #96cbfe;
$base0E: #ff73fd;
$base0F: #b18a3d;
"""
