base00 = "292d3e"
base01 = "444267"
base02 = "5c598b"
base03 = "676e95"
base04 = "8796b0"
base05 = "959dcb"
base06 = "959dcb"
base07 = "ffffff"
base08 = "6e98e1"
base09 = "f78c6c"
base0A = "e0a557"
base0B = "78c06e"
base0C = "83b7e5"
base0D = "82aaff"
base0E = "c792ea"
base0F = "ff5370"

gtk_colors = """
@define-color base00  #292d3e;
@define-color base01  #444267;
@define-color base02  #5c598b;
@define-color base03  #676e95;
@define-color base04  #8796b0;
@define-color base05  #959dcb;
@define-color base06  #959dcb;
@define-color base07  #ffffff;
@define-color base08  #6e98e1;
@define-color base09  #f78c6c;
@define-color base0A  #e0a557;
@define-color base0B  #78c06e;
@define-color base0C  #83b7e5;
@define-color base0D  #82aaff;
@define-color base0E  #c792ea;
@define-color base0F  #ff5370;
"""

scss_colors = """
$base00: #292d3e;
$base01: #444267;
$base02: #5c598b;
$base03: #676e95;
$base04: #8796b0;
$base05: #959dcb;
$base06: #959dcb;
$base07: #ffffff;
$base08: #6e98e1;
$base09: #f78c6c;
$base0A: #e0a557;
$base0B: #78c06e;
$base0C: #83b7e5;
$base0D: #82aaff;
$base0E: #c792ea;
$base0F: #ff5370;
"""
