base00 = "222222"
base01 = "313131"
base02 = "555D55"
base03 = "644646"
base04 = "5A5A5A"
base05 = "DEDEE7"
base06 = "C3C3B4"
base07 = "FFFFE6"
base08 = "C88C8C"
base09 = "476C88"
base0A = "D8B56D"
base0B = "99C899"
base0C = "78B4B4"
base0D = "537C9C"
base0E = "86CACD"
base0F = "704F4F"

gtk_colors = """
@define-color base00  #222222;
@define-color base01  #313131;
@define-color base02  #555D55;
@define-color base03  #644646;
@define-color base04  #5A5A5A;
@define-color base05  #DEDEE7;
@define-color base06  #C3C3B4;
@define-color base07  #FFFFE6;
@define-color base08  #C88C8C;
@define-color base09  #476C88;
@define-color base0A  #D8B56D;
@define-color base0B  #99C899;
@define-color base0C  #78B4B4;
@define-color base0D  #537C9C;
@define-color base0E  #86CACD;
@define-color base0F  #704F4F;
"""

scss_colors = """
$base00: #222222;
$base01: #313131;
$base02: #555D55;
$base03: #644646;
$base04: #5A5A5A;
$base05: #DEDEE7;
$base06: #C3C3B4;
$base07: #FFFFE6;
$base08: #C88C8C;
$base09: #476C88;
$base0A: #D8B56D;
$base0B: #99C899;
$base0C: #78B4B4;
$base0D: #537C9C;
$base0E: #86CACD;
$base0F: #704F4F;
"""
