base00 = "000000"
base01 = "404040"
base02 = "404040"
base03 = "808080"
base04 = "808080"
base05 = "c0c0c0"
base06 = "c0c0c0"
base07 = "ffffff"
base08 = "dd0907"
base09 = "ff6403"
base0A = "fbf305"
base0B = "1fb714"
base0C = "02abea"
base0D = "0000d3"
base0E = "4700a5"
base0F = "90713a"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #404040;
@define-color base02  #404040;
@define-color base03  #808080;
@define-color base04  #808080;
@define-color base05  #c0c0c0;
@define-color base06  #c0c0c0;
@define-color base07  #ffffff;
@define-color base08  #dd0907;
@define-color base09  #ff6403;
@define-color base0A  #fbf305;
@define-color base0B  #1fb714;
@define-color base0C  #02abea;
@define-color base0D  #0000d3;
@define-color base0E  #4700a5;
@define-color base0F  #90713a;
"""

scss_colors = """
$base00: #000000;
$base01: #404040;
$base02: #404040;
$base03: #808080;
$base04: #808080;
$base05: #c0c0c0;
$base06: #c0c0c0;
$base07: #ffffff;
$base08: #dd0907;
$base09: #ff6403;
$base0A: #fbf305;
$base0B: #1fb714;
$base0C: #02abea;
$base0D: #0000d3;
$base0E: #4700a5;
$base0F: #90713a;
"""
