base00 = "201602"
base01 = "302e00"
base02 = "5f5b17"
base03 = "6c6823"
base04 = "86813b"
base05 = "948e48"
base06 = "ccc37a"
base07 = "faf0a5"
base08 = "c35359"
base09 = "b36144"
base0A = "a88339"
base0B = "18974e"
base0C = "75a738"
base0D = "477ca1"
base0E = "8868b3"
base0F = "b3588e"

gtk_colors = """
@define-color base00  #201602;
@define-color base01  #302e00;
@define-color base02  #5f5b17;
@define-color base03  #6c6823;
@define-color base04  #86813b;
@define-color base05  #948e48;
@define-color base06  #ccc37a;
@define-color base07  #faf0a5;
@define-color base08  #c35359;
@define-color base09  #b36144;
@define-color base0A  #a88339;
@define-color base0B  #18974e;
@define-color base0C  #75a738;
@define-color base0D  #477ca1;
@define-color base0E  #8868b3;
@define-color base0F  #b3588e;
"""

scss_colors = """
$base00: #201602;
$base01: #302e00;
$base02: #5f5b17;
$base03: #6c6823;
$base04: #86813b;
$base05: #948e48;
$base06: #ccc37a;
$base07: #faf0a5;
$base08: #c35359;
$base09: #b36144;
$base0A: #a88339;
$base0B: #18974e;
$base0C: #75a738;
$base0D: #477ca1;
$base0E: #8868b3;
$base0F: #b3588e;
"""
