base00 = "FAFAFA"
base01 = "E7EAEC"
base02 = "CCEAE7"
base03 = "CCD7DA"
base04 = "8796B0"
base05 = "80CBC4"
base06 = "80CBC4"
base07 = "FFFFFF"
base08 = "FF5370"
base09 = "F76D47"
base0A = "FFB62C"
base0B = "91B859"
base0C = "39ADB5"
base0D = "6182B8"
base0E = "7C4DFF"
base0F = "E53935"

gtk_colors = """
@define-color base00  #FAFAFA;
@define-color base01  #E7EAEC;
@define-color base02  #CCEAE7;
@define-color base03  #CCD7DA;
@define-color base04  #8796B0;
@define-color base05  #80CBC4;
@define-color base06  #80CBC4;
@define-color base07  #FFFFFF;
@define-color base08  #FF5370;
@define-color base09  #F76D47;
@define-color base0A  #FFB62C;
@define-color base0B  #91B859;
@define-color base0C  #39ADB5;
@define-color base0D  #6182B8;
@define-color base0E  #7C4DFF;
@define-color base0F  #E53935;
"""

scss_colors = """
$base00: #FAFAFA;
$base01: #E7EAEC;
$base02: #CCEAE7;
$base03: #CCD7DA;
$base04: #8796B0;
$base05: #80CBC4;
$base06: #80CBC4;
$base07: #FFFFFF;
$base08: #FF5370;
$base09: #F76D47;
$base0A: #FFB62C;
$base0B: #91B859;
$base0C: #39ADB5;
$base0D: #6182B8;
$base0E: #7C4DFF;
$base0F: #E53935;
"""
