base00 = "263238"
base01 = "2C393F"
base02 = "37474F"
base03 = "707880"
base04 = "C9CCD3"
base05 = "CDD3DE"
base06 = "D5DBE5"
base07 = "FFFFFF"
base08 = "EC5F67"
base09 = "EA9560"
base0A = "FFCC00"
base0B = "8BD649"
base0C = "80CBC4"
base0D = "89DDFF"
base0E = "82AAFF"
base0F = "EC5F67"

gtk_colors = """
@define-color base00  #263238;
@define-color base01  #2C393F;
@define-color base02  #37474F;
@define-color base03  #707880;
@define-color base04  #C9CCD3;
@define-color base05  #CDD3DE;
@define-color base06  #D5DBE5;
@define-color base07  #FFFFFF;
@define-color base08  #EC5F67;
@define-color base09  #EA9560;
@define-color base0A  #FFCC00;
@define-color base0B  #8BD649;
@define-color base0C  #80CBC4;
@define-color base0D  #89DDFF;
@define-color base0E  #82AAFF;
@define-color base0F  #EC5F67;
"""

scss_colors = """
$base00: #263238;
$base01: #2C393F;
$base02: #37474F;
$base03: #707880;
$base04: #C9CCD3;
$base05: #CDD3DE;
$base06: #D5DBE5;
$base07: #FFFFFF;
$base08: #EC5F67;
$base09: #EA9560;
$base0A: #FFCC00;
$base0B: #8BD649;
$base0C: #80CBC4;
$base0D: #89DDFF;
$base0E: #82AAFF;
$base0F: #EC5F67;
"""
