base00 = "202124"
base01 = "27292c"
base02 = "323639"
base03 = "44464d"
base04 = "676c71"
base05 = "80868b"
base06 = "9e9e9e"
base07 = "ffffff"
base08 = "f44336"
base09 = "ff9800"
base0A = "ffeb3b"
base0B = "00e676"
base0C = "00bcd4"
base0D = "2196f3"
base0E = "673ab7"
base0F = "8d6e63"

gtk_colors = """
@define-color base00  #202124;
@define-color base01  #27292c;
@define-color base02  #323639;
@define-color base03  #44464d;
@define-color base04  #676c71;
@define-color base05  #80868b;
@define-color base06  #9e9e9e;
@define-color base07  #ffffff;
@define-color base08  #f44336;
@define-color base09  #ff9800;
@define-color base0A  #ffeb3b;
@define-color base0B  #00e676;
@define-color base0C  #00bcd4;
@define-color base0D  #2196f3;
@define-color base0E  #673ab7;
@define-color base0F  #8d6e63;
"""

scss_colors = """
$base00: #202124;
$base01: #27292c;
$base02: #323639;
$base03: #44464d;
$base04: #676c71;
$base05: #80868b;
$base06: #9e9e9e;
$base07: #ffffff;
$base08: #f44336;
$base09: #ff9800;
$base0A: #ffeb3b;
$base0B: #00e676;
$base0C: #00bcd4;
$base0D: #2196f3;
$base0E: #673ab7;
$base0F: #8d6e63;
"""
