base00 = "292D3E"
base01 = "444267"
base02 = "32374D"
base03 = "676E95"
base04 = "8796B0"
base05 = "959DCB"
base06 = "959DCB"
base07 = "FFFFFF"
base08 = "F07178"
base09 = "F78C6C"
base0A = "FFCB6B"
base0B = "C3E88D"
base0C = "89DDFF"
base0D = "82AAFF"
base0E = "C792EA"
base0F = "FF5370"

gtk_colors = """
@define-color base00  #292D3E;
@define-color base01  #444267;
@define-color base02  #32374D;
@define-color base03  #676E95;
@define-color base04  #8796B0;
@define-color base05  #959DCB;
@define-color base06  #959DCB;
@define-color base07  #FFFFFF;
@define-color base08  #F07178;
@define-color base09  #F78C6C;
@define-color base0A  #FFCB6B;
@define-color base0B  #C3E88D;
@define-color base0C  #89DDFF;
@define-color base0D  #82AAFF;
@define-color base0E  #C792EA;
@define-color base0F  #FF5370;
"""

scss_colors = """
$base00: #292D3E;
$base01: #444267;
$base02: #32374D;
$base03: #676E95;
$base04: #8796B0;
$base05: #959DCB;
$base06: #959DCB;
$base07: #FFFFFF;
$base08: #F07178;
$base09: #F78C6C;
$base0A: #FFCB6B;
$base0B: #C3E88D;
$base0C: #89DDFF;
$base0D: #82AAFF;
$base0E: #C792EA;
$base0F: #FF5370;
"""
