base00 = "1e0528"
base01 = "1A092D"
base02 = "331354"
base03 = "320f55"
base04 = "873582"
base05 = "ffeeff"
base06 = "ffeeff"
base07 = "f8c0ff"
base08 = "00d9e9"
base09 = "aa00a3"
base0A = "955ae7"
base0B = "05cb0d"
base0C = "b900b1"
base0D = "550068"
base0E = "8991bb"
base0F = "4d6fff"

gtk_colors = """
@define-color base00  #1e0528;
@define-color base01  #1A092D;
@define-color base02  #331354;
@define-color base03  #320f55;
@define-color base04  #873582;
@define-color base05  #ffeeff;
@define-color base06  #ffeeff;
@define-color base07  #f8c0ff;
@define-color base08  #00d9e9;
@define-color base09  #aa00a3;
@define-color base0A  #955ae7;
@define-color base0B  #05cb0d;
@define-color base0C  #b900b1;
@define-color base0D  #550068;
@define-color base0E  #8991bb;
@define-color base0F  #4d6fff;
"""

scss_colors = """
$base00: #1e0528;
$base01: #1A092D;
$base02: #331354;
$base03: #320f55;
$base04: #873582;
$base05: #ffeeff;
$base06: #ffeeff;
$base07: #f8c0ff;
$base08: #00d9e9;
$base09: #aa00a3;
$base0A: #955ae7;
$base0B: #05cb0d;
$base0C: #b900b1;
$base0D: #550068;
$base0E: #8991bb;
$base0F: #4d6fff;
"""
