base00 = "272822"
base01 = "383830"
base02 = "49483e"
base03 = "75715e"
base04 = "a59f85"
base05 = "f8f8f2"
base06 = "f5f4f1"
base07 = "f9f8f5"
base08 = "f92672"
base09 = "fd971f"
base0A = "f4bf75"
base0B = "a6e22e"
base0C = "a1efe4"
base0D = "66d9ef"
base0E = "ae81ff"
base0F = "cc6633"

gtk_colors = """
@define-color base00  #272822;
@define-color base01  #383830;
@define-color base02  #49483e;
@define-color base03  #75715e;
@define-color base04  #a59f85;
@define-color base05  #f8f8f2;
@define-color base06  #f5f4f1;
@define-color base07  #f9f8f5;
@define-color base08  #f92672;
@define-color base09  #fd971f;
@define-color base0A  #f4bf75;
@define-color base0B  #a6e22e;
@define-color base0C  #a1efe4;
@define-color base0D  #66d9ef;
@define-color base0E  #ae81ff;
@define-color base0F  #cc6633;
"""

scss_colors = """
$base00: #272822;
$base01: #383830;
$base02: #49483e;
$base03: #75715e;
$base04: #a59f85;
$base05: #f8f8f2;
$base06: #f5f4f1;
$base07: #f9f8f5;
$base08: #f92672;
$base09: #fd971f;
$base0A: #f4bf75;
$base0B: #a6e22e;
$base0C: #a1efe4;
$base0D: #66d9ef;
$base0E: #ae81ff;
$base0F: #cc6633;
"""
