base00 = "0f0f0f"
base01 = "191919"
base02 = "262626"
base03 = "4c4c4c"
base04 = "ac8a8c"
base05 = "cacaca"
base06 = "e7e7e7"
base07 = "f0f0f0"
base08 = "ac8a8c"
base09 = "ceb188"
base0A = "aca98a"
base0B = "8aac8b"
base0C = "8aabac"
base0D = "8f8aac"
base0E = "ac8aac"
base0F = "ac8a8c"

gtk_colors = """
@define-color base00  #0f0f0f;
@define-color base01  #191919;
@define-color base02  #262626;
@define-color base03  #4c4c4c;
@define-color base04  #ac8a8c;
@define-color base05  #cacaca;
@define-color base06  #e7e7e7;
@define-color base07  #f0f0f0;
@define-color base08  #ac8a8c;
@define-color base09  #ceb188;
@define-color base0A  #aca98a;
@define-color base0B  #8aac8b;
@define-color base0C  #8aabac;
@define-color base0D  #8f8aac;
@define-color base0E  #ac8aac;
@define-color base0F  #ac8a8c;
"""

scss_colors = """
$base00: #0f0f0f;
$base01: #191919;
$base02: #262626;
$base03: #4c4c4c;
$base04: #ac8a8c;
$base05: #cacaca;
$base06: #e7e7e7;
$base07: #f0f0f0;
$base08: #ac8a8c;
$base09: #ceb188;
$base0A: #aca98a;
$base0B: #8aac8b;
$base0C: #8aabac;
$base0D: #8f8aac;
$base0E: #ac8aac;
$base0F: #ac8a8c;
"""
