base00 = "22273b"
base01 = "414f60"
base02 = "5a8380"
base03 = "6e6f72"
base04 = "87888b"
base05 = "a4a6a9"
base06 = "c7c9cd"
base07 = "8dbdaa"
base08 = "777abc"
base09 = "94929e"
base0A = "4f9062"
base0B = "6562a8"
base0C = "226f68"
base0D = "4d6bb6"
base0E = "716cae"
base0F = "8c70a7"

gtk_colors = """
@define-color base00  #22273b;
@define-color base01  #414f60;
@define-color base02  #5a8380;
@define-color base03  #6e6f72;
@define-color base04  #87888b;
@define-color base05  #a4a6a9;
@define-color base06  #c7c9cd;
@define-color base07  #8dbdaa;
@define-color base08  #777abc;
@define-color base09  #94929e;
@define-color base0A  #4f9062;
@define-color base0B  #6562a8;
@define-color base0C  #226f68;
@define-color base0D  #4d6bb6;
@define-color base0E  #716cae;
@define-color base0F  #8c70a7;
"""

scss_colors = """
$base00: #22273b;
$base01: #414f60;
$base02: #5a8380;
$base03: #6e6f72;
$base04: #87888b;
$base05: #a4a6a9;
$base06: #c7c9cd;
$base07: #8dbdaa;
$base08: #777abc;
$base09: #94929e;
$base0A: #4f9062;
$base0B: #6562a8;
$base0C: #226f68;
$base0D: #4d6bb6;
$base0E: #716cae;
$base0F: #8c70a7;
"""
