base00 = "2E3440"
base01 = "3B4252"
base02 = "434C5E"
base03 = "4C566A"
base04 = "D8DEE9"
base05 = "E5E9F0"
base06 = "ECEFF4"
base07 = "8FBCBB"
base08 = "BF616A"
base09 = "D08770"
base0A = "EBCB8B"
base0B = "A3BE8C"
base0C = "88C0D0"
base0D = "81A1C1"
base0E = "B48EAD"
base0F = "5E81AC"

gtk_colors = """
@define-color base00  #2E3440;
@define-color base01  #3B4252;
@define-color base02  #434C5E;
@define-color base03  #4C566A;
@define-color base04  #D8DEE9;
@define-color base05  #E5E9F0;
@define-color base06  #ECEFF4;
@define-color base07  #8FBCBB;
@define-color base08  #BF616A;
@define-color base09  #D08770;
@define-color base0A  #EBCB8B;
@define-color base0B  #A3BE8C;
@define-color base0C  #88C0D0;
@define-color base0D  #81A1C1;
@define-color base0E  #B48EAD;
@define-color base0F  #5E81AC;
"""

scss_colors = """
$base00: #2E3440;
$base01: #3B4252;
$base02: #434C5E;
$base03: #4C566A;
$base04: #D8DEE9;
$base05: #E5E9F0;
$base06: #ECEFF4;
$base07: #8FBCBB;
$base08: #BF616A;
$base09: #D08770;
$base0A: #EBCB8B;
$base0B: #A3BE8C;
$base0C: #88C0D0;
$base0D: #81A1C1;
$base0E: #B48EAD;
$base0F: #5E81AC;
"""
