base00 = "1B2B34"
base01 = "343D46"
base02 = "4F5B66"
base03 = "65737E"
base04 = "A7ADBA"
base05 = "C0C5CE"
base06 = "CDD3DE"
base07 = "D8DEE9"
base08 = "EC5f67"
base09 = "F99157"
base0A = "FAC863"
base0B = "99C794"
base0C = "5FB3B3"
base0D = "6699CC"
base0E = "C594C5"
base0F = "AB7967"

gtk_colors = """
@define-color base00  #1B2B34;
@define-color base01  #343D46;
@define-color base02  #4F5B66;
@define-color base03  #65737E;
@define-color base04  #A7ADBA;
@define-color base05  #C0C5CE;
@define-color base06  #CDD3DE;
@define-color base07  #D8DEE9;
@define-color base08  #EC5f67;
@define-color base09  #F99157;
@define-color base0A  #FAC863;
@define-color base0B  #99C794;
@define-color base0C  #5FB3B3;
@define-color base0D  #6699CC;
@define-color base0E  #C594C5;
@define-color base0F  #AB7967;
"""

scss_colors = """
$base00: #1B2B34;
$base01: #343D46;
$base02: #4F5B66;
$base03: #65737E;
$base04: #A7ADBA;
$base05: #C0C5CE;
$base06: #CDD3DE;
$base07: #D8DEE9;
$base08: #EC5f67;
$base09: #F99157;
$base0A: #FAC863;
$base0B: #99C794;
$base0C: #5FB3B3;
$base0D: #6699CC;
$base0E: #C594C5;
$base0F: #AB7967;
"""
