base00 = "282c34"
base01 = "353b45"
base02 = "3e4451"
base03 = "545862"
base04 = "565c64"
base05 = "abb2bf"
base06 = "b6bdca"
base07 = "c8ccd4"
base08 = "e06c75"
base09 = "d19a66"
base0A = "e5c07b"
base0B = "98c379"
base0C = "56b6c2"
base0D = "61afef"
base0E = "c678dd"
base0F = "be5046"

gtk_colors = """
@define-color base00  #282c34;
@define-color base01  #353b45;
@define-color base02  #3e4451;
@define-color base03  #545862;
@define-color base04  #565c64;
@define-color base05  #abb2bf;
@define-color base06  #b6bdca;
@define-color base07  #c8ccd4;
@define-color base08  #e06c75;
@define-color base09  #d19a66;
@define-color base0A  #e5c07b;
@define-color base0B  #98c379;
@define-color base0C  #56b6c2;
@define-color base0D  #61afef;
@define-color base0E  #c678dd;
@define-color base0F  #be5046;
"""

scss_colors = """
$base00: #282c34;
$base01: #353b45;
$base02: #3e4451;
$base03: #545862;
$base04: #565c64;
$base05: #abb2bf;
$base06: #b6bdca;
$base07: #c8ccd4;
$base08: #e06c75;
$base09: #d19a66;
$base0A: #e5c07b;
$base0B: #98c379;
$base0C: #56b6c2;
$base0D: #61afef;
$base0E: #c678dd;
$base0F: #be5046;
"""
