base00 = "00002A"
base01 = "20204A"
base02 = "30305A"
base03 = "50507A"
base04 = "B0B0DA"
base05 = "D0D0FA"
base06 = "E0E0FF"
base07 = "F5F5FF"
base08 = "FF4242"
base09 = "FC8D28"
base0A = "F3E877"
base0B = "59F176"
base0C = "0EF0F0"
base0D = "66B0FF"
base0E = "F10596"
base0F = "F003EF"

gtk_colors = """
@define-color base00  #00002A;
@define-color base01  #20204A;
@define-color base02  #30305A;
@define-color base03  #50507A;
@define-color base04  #B0B0DA;
@define-color base05  #D0D0FA;
@define-color base06  #E0E0FF;
@define-color base07  #F5F5FF;
@define-color base08  #FF4242;
@define-color base09  #FC8D28;
@define-color base0A  #F3E877;
@define-color base0B  #59F176;
@define-color base0C  #0EF0F0;
@define-color base0D  #66B0FF;
@define-color base0E  #F10596;
@define-color base0F  #F003EF;
"""

scss_colors = """
$base00: #00002A;
$base01: #20204A;
$base02: #30305A;
$base03: #50507A;
$base04: #B0B0DA;
$base05: #D0D0FA;
$base06: #E0E0FF;
$base07: #F5F5FF;
$base08: #FF4242;
$base09: #FC8D28;
$base0A: #F3E877;
$base0B: #59F176;
$base0C: #0EF0F0;
$base0D: #66B0FF;
$base0E: #F10596;
$base0F: #F003EF;
"""
