base00 = "f2f4f8"
base01 = "dde1e6"
base02 = "525252"
base03 = "161616"
base04 = "262626"
base05 = "393939"
base06 = "525252"
base07 = "08bdba"
base08 = "ff7eb6"
base09 = "ee5396"
base0A = "FF6F00"
base0B = "0f62fe"
base0C = "673AB7"
base0D = "42be65"
base0E = "be95ff"
base0F = "37474F"

gtk_colors = """
@define-color base00  #f2f4f8;
@define-color base01  #dde1e6;
@define-color base02  #525252;
@define-color base03  #161616;
@define-color base04  #262626;
@define-color base05  #393939;
@define-color base06  #525252;
@define-color base07  #08bdba;
@define-color base08  #ff7eb6;
@define-color base09  #ee5396;
@define-color base0A  #FF6F00;
@define-color base0B  #0f62fe;
@define-color base0C  #673AB7;
@define-color base0D  #42be65;
@define-color base0E  #be95ff;
@define-color base0F  #37474F;
"""

scss_colors = """
$base00: #f2f4f8;
$base01: #dde1e6;
$base02: #525252;
$base03: #161616;
$base04: #262626;
$base05: #393939;
$base06: #525252;
$base07: #08bdba;
$base08: #ff7eb6;
$base09: #ee5396;
$base0A: #FF6F00;
$base0B: #0f62fe;
$base0C: #673AB7;
$base0D: #42be65;
$base0E: #be95ff;
$base0F: #37474F;
"""
