base00 = "161616"
base01 = "262626"
base02 = "393939"
base03 = "525252"
base04 = "dde1e6"
base05 = "f2f4f8"
base06 = "ffffff"
base07 = "08bdba"
base08 = "3ddbd9"
base09 = "78a9ff"
base0A = "ee5396"
base0B = "33b1ff"
base0C = "ff7eb6"
base0D = "42be65"
base0E = "be95ff"
base0F = "82cfff"

gtk_colors = """
@define-color base00  #161616;
@define-color base01  #262626;
@define-color base02  #393939;
@define-color base03  #525252;
@define-color base04  #dde1e6;
@define-color base05  #f2f4f8;
@define-color base06  #ffffff;
@define-color base07  #08bdba;
@define-color base08  #3ddbd9;
@define-color base09  #78a9ff;
@define-color base0A  #ee5396;
@define-color base0B  #33b1ff;
@define-color base0C  #ff7eb6;
@define-color base0D  #42be65;
@define-color base0E  #be95ff;
@define-color base0F  #82cfff;
"""

scss_colors = """
$base00: #161616;
$base01: #262626;
$base02: #393939;
$base03: #525252;
$base04: #dde1e6;
$base05: #f2f4f8;
$base06: #ffffff;
$base07: #08bdba;
$base08: #3ddbd9;
$base09: #78a9ff;
$base0A: #ee5396;
$base0B: #33b1ff;
$base0C: #ff7eb6;
$base0D: #42be65;
$base0E: #be95ff;
$base0F: #82cfff;
"""
