base00 = "131213"
base01 = "2f1823"
base02 = "472234"
base03 = "ffbee3"
base04 = "9b2a46"
base05 = "f15c99"
base06 = "81506a"
base07 = "632227"
base08 = "b00b69"
base09 = "ff9153"
base0A = "ffcc00"
base0B = "9ddf69"
base0C = "714ca6"
base0D = "008080"
base0E = "a24030"
base0F = "a24030"

gtk_colors = """
@define-color base00  #131213;
@define-color base01  #2f1823;
@define-color base02  #472234;
@define-color base03  #ffbee3;
@define-color base04  #9b2a46;
@define-color base05  #f15c99;
@define-color base06  #81506a;
@define-color base07  #632227;
@define-color base08  #b00b69;
@define-color base09  #ff9153;
@define-color base0A  #ffcc00;
@define-color base0B  #9ddf69;
@define-color base0C  #714ca6;
@define-color base0D  #008080;
@define-color base0E  #a24030;
@define-color base0F  #a24030;
"""

scss_colors = """
$base00: #131213;
$base01: #2f1823;
$base02: #472234;
$base03: #ffbee3;
$base04: #9b2a46;
$base05: #f15c99;
$base06: #81506a;
$base07: #632227;
$base08: #b00b69;
$base09: #ff9153;
$base0A: #ffcc00;
$base0B: #9ddf69;
$base0C: #714ca6;
$base0D: #008080;
$base0E: #a24030;
$base0F: #a24030;
"""
