base00 = "1c1c1c"
base01 = "af005f"
base02 = "5faf00"
base03 = "d7af5f"
base04 = "5fafd7"
base05 = "808080"
base06 = "d7875f"
base07 = "d0d0d0"
base08 = "585858"
base09 = "5faf5f"
base0A = "afd700"
base0B = "af87d7"
base0C = "ffaf00"
base0D = "ff5faf"
base0E = "00afaf"
base0F = "5f8787"

gtk_colors = """
@define-color base00  #1c1c1c;
@define-color base01  #af005f;
@define-color base02  #5faf00;
@define-color base03  #d7af5f;
@define-color base04  #5fafd7;
@define-color base05  #808080;
@define-color base06  #d7875f;
@define-color base07  #d0d0d0;
@define-color base08  #585858;
@define-color base09  #5faf5f;
@define-color base0A  #afd700;
@define-color base0B  #af87d7;
@define-color base0C  #ffaf00;
@define-color base0D  #ff5faf;
@define-color base0E  #00afaf;
@define-color base0F  #5f8787;
"""

scss_colors = """
$base00: #1c1c1c;
$base01: #af005f;
$base02: #5faf00;
$base03: #d7af5f;
$base04: #5fafd7;
$base05: #808080;
$base06: #d7875f;
$base07: #d0d0d0;
$base08: #585858;
$base09: #5faf5f;
$base0A: #afd700;
$base0B: #af87d7;
$base0C: #ffaf00;
$base0D: #ff5faf;
$base0E: #00afaf;
$base0F: #5f8787;
"""
