base00 = "eeeeee"
base01 = "af0000"
base02 = "008700"
base03 = "5f8700"
base04 = "0087af"
base05 = "444444"
base06 = "005f87"
base07 = "878787"
base08 = "bcbcbc"
base09 = "d70000"
base0A = "d70087"
base0B = "8700af"
base0C = "d75f00"
base0D = "d75f00"
base0E = "005faf"
base0F = "005f87"

gtk_colors = """
@define-color base00  #eeeeee;
@define-color base01  #af0000;
@define-color base02  #008700;
@define-color base03  #5f8700;
@define-color base04  #0087af;
@define-color base05  #444444;
@define-color base06  #005f87;
@define-color base07  #878787;
@define-color base08  #bcbcbc;
@define-color base09  #d70000;
@define-color base0A  #d70087;
@define-color base0B  #8700af;
@define-color base0C  #d75f00;
@define-color base0D  #d75f00;
@define-color base0E  #005faf;
@define-color base0F  #005f87;
"""

scss_colors = """
$base00: #eeeeee;
$base01: #af0000;
$base02: #008700;
$base03: #5f8700;
$base04: #0087af;
$base05: #444444;
$base06: #005f87;
$base07: #878787;
$base08: #bcbcbc;
$base09: #d70000;
$base0A: #d70087;
$base0B: #8700af;
$base0C: #d75f00;
$base0D: #d75f00;
$base0E: #005faf;
$base0F: #005f87;
"""
