base00 = "000000"
base01 = "1d2b53"
base02 = "7e2553"
base03 = "008751"
base04 = "ab5236"
base05 = "5f574f"
base06 = "c2c3c7"
base07 = "fff1e8"
base08 = "ff004d"
base09 = "ffa300"
base0A = "fff024"
base0B = "00e756"
base0C = "29adff"
base0D = "83769c"
base0E = "ff77a8"
base0F = "ffccaa"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #1d2b53;
@define-color base02  #7e2553;
@define-color base03  #008751;
@define-color base04  #ab5236;
@define-color base05  #5f574f;
@define-color base06  #c2c3c7;
@define-color base07  #fff1e8;
@define-color base08  #ff004d;
@define-color base09  #ffa300;
@define-color base0A  #fff024;
@define-color base0B  #00e756;
@define-color base0C  #29adff;
@define-color base0D  #83769c;
@define-color base0E  #ff77a8;
@define-color base0F  #ffccaa;
"""

scss_colors = """
$base00: #000000;
$base01: #1d2b53;
$base02: #7e2553;
$base03: #008751;
$base04: #ab5236;
$base05: #5f574f;
$base06: #c2c3c7;
$base07: #fff1e8;
$base08: #ff004d;
$base09: #ffa300;
$base0A: #fff024;
$base0B: #00e756;
$base0C: #29adff;
$base0D: #83769c;
$base0E: #ff77a8;
$base0F: #ffccaa;
"""
