base00 = "292c36"
base01 = "333344"
base02 = "474160"
base03 = "65568a"
base04 = "b8b8b8"
base05 = "d8d8d8"
base06 = "e8e8e8"
base07 = "f8f8f8"
base08 = "f84547"
base09 = "d28e5d"
base0A = "efa16b"
base0B = "95c76f"
base0C = "64878f"
base0D = "8485ce"
base0E = "b74989"
base0F = "986841"

gtk_colors = """
@define-color base00  #292c36;
@define-color base01  #333344;
@define-color base02  #474160;
@define-color base03  #65568a;
@define-color base04  #b8b8b8;
@define-color base05  #d8d8d8;
@define-color base06  #e8e8e8;
@define-color base07  #f8f8f8;
@define-color base08  #f84547;
@define-color base09  #d28e5d;
@define-color base0A  #efa16b;
@define-color base0B  #95c76f;
@define-color base0C  #64878f;
@define-color base0D  #8485ce;
@define-color base0E  #b74989;
@define-color base0F  #986841;
"""

scss_colors = """
$base00: #292c36;
$base01: #333344;
$base02: #474160;
$base03: #65568a;
$base04: #b8b8b8;
$base05: #d8d8d8;
$base06: #e8e8e8;
$base07: #f8f8f8;
$base08: #f84547;
$base09: #d28e5d;
$base0A: #efa16b;
$base0B: #95c76f;
$base0C: #64878f;
$base0D: #8485ce;
$base0E: #b74989;
$base0F: #986841;
"""
