base00 = "010409"
base01 = "21262d"
base02 = "30363d"
base03 = "484f58"
base04 = "8b949e"
base05 = "b1bac4"
base06 = "c9d1d9"
base07 = "f0f6fc"
base08 = "ff7b72"
base09 = "f0883e"
base0A = "d29922"
base0B = "3fb950"
base0C = "a5d6ff"
base0D = "58a6ff"
base0E = "f778ba"
base0F = "bd561d"

gtk_colors = """
@define-color base00  #010409;
@define-color base01  #21262d;
@define-color base02  #30363d;
@define-color base03  #484f58;
@define-color base04  #8b949e;
@define-color base05  #b1bac4;
@define-color base06  #c9d1d9;
@define-color base07  #f0f6fc;
@define-color base08  #ff7b72;
@define-color base09  #f0883e;
@define-color base0A  #d29922;
@define-color base0B  #3fb950;
@define-color base0C  #a5d6ff;
@define-color base0D  #58a6ff;
@define-color base0E  #f778ba;
@define-color base0F  #bd561d;
"""

scss_colors = """
$base00: #010409;
$base01: #21262d;
$base02: #30363d;
$base03: #484f58;
$base04: #8b949e;
$base05: #b1bac4;
$base06: #c9d1d9;
$base07: #f0f6fc;
$base08: #ff7b72;
$base09: #f0883e;
$base0A: #d29922;
$base0B: #3fb950;
$base0C: #a5d6ff;
$base0D: #58a6ff;
$base0E: #f778ba;
$base0F: #bd561d;
"""
