base00 = "1c2128"
base01 = "373e47"
base02 = "444c56"
base03 = "545d68"
base04 = "768390"
base05 = "909dab"
base06 = "adbac7"
base07 = "cdd9e5"
base08 = "f47067"
base09 = "e0823d"
base0A = "c69026"
base0B = "57ab5a"
base0C = "96d0ff"
base0D = "539bf5"
base0E = "e275ad"
base0F = "ae5622"

gtk_colors = """
@define-color base00  #1c2128;
@define-color base01  #373e47;
@define-color base02  #444c56;
@define-color base03  #545d68;
@define-color base04  #768390;
@define-color base05  #909dab;
@define-color base06  #adbac7;
@define-color base07  #cdd9e5;
@define-color base08  #f47067;
@define-color base09  #e0823d;
@define-color base0A  #c69026;
@define-color base0B  #57ab5a;
@define-color base0C  #96d0ff;
@define-color base0D  #539bf5;
@define-color base0E  #e275ad;
@define-color base0F  #ae5622;
"""

scss_colors = """
$base00: #1c2128;
$base01: #373e47;
$base02: #444c56;
$base03: #545d68;
$base04: #768390;
$base05: #909dab;
$base06: #adbac7;
$base07: #cdd9e5;
$base08: #f47067;
$base09: #e0823d;
$base0A: #c69026;
$base0B: #57ab5a;
$base0C: #96d0ff;
$base0D: #539bf5;
$base0E: #e275ad;
$base0F: #ae5622;
"""
