base00 = "fafbfc"
base01 = "e1e4e8"
base02 = "d1d5da"
base03 = "959da5"
base04 = "444d56"
base05 = "2f363d"
base06 = "24292e"
base07 = "1b1f23"
base08 = "d73a49"
base09 = "f66a0a"
base0A = "ffd33d"
base0B = "28a745"
base0C = "79b8ff"
base0D = "0366d6"
base0E = "ea4aaa"
base0F = "a04100"

gtk_colors = """
@define-color base00  #fafbfc;
@define-color base01  #e1e4e8;
@define-color base02  #d1d5da;
@define-color base03  #959da5;
@define-color base04  #444d56;
@define-color base05  #2f363d;
@define-color base06  #24292e;
@define-color base07  #1b1f23;
@define-color base08  #d73a49;
@define-color base09  #f66a0a;
@define-color base0A  #ffd33d;
@define-color base0B  #28a745;
@define-color base0C  #79b8ff;
@define-color base0D  #0366d6;
@define-color base0E  #ea4aaa;
@define-color base0F  #a04100;
"""

scss_colors = """
$base00: #fafbfc;
$base01: #e1e4e8;
$base02: #d1d5da;
$base03: #959da5;
$base04: #444d56;
$base05: #2f363d;
$base06: #24292e;
$base07: #1b1f23;
$base08: #d73a49;
$base09: #f66a0a;
$base0A: #ffd33d;
$base0B: #28a745;
$base0C: #79b8ff;
$base0D: #0366d6;
$base0E: #ea4aaa;
$base0F: #a04100;
"""
