base00 = "100510"
base01 = "302030"
base02 = "403040"
base03 = "605060"
base04 = "bbb0bb"
base05 = "ddd0dd"
base06 = "eee0ee"
base07 = "fff0ff"
base08 = "FF1D0D"
base09 = "CCAE14"
base0A = "F000A0"
base0B = "14CC64"
base0C = "0075B0"
base0D = "00A0F0"
base0E = "B000D0"
base0F = "6A2A3C"

gtk_colors = """
@define-color base00  #100510;
@define-color base01  #302030;
@define-color base02  #403040;
@define-color base03  #605060;
@define-color base04  #bbb0bb;
@define-color base05  #ddd0dd;
@define-color base06  #eee0ee;
@define-color base07  #fff0ff;
@define-color base08  #FF1D0D;
@define-color base09  #CCAE14;
@define-color base0A  #F000A0;
@define-color base0B  #14CC64;
@define-color base0C  #0075B0;
@define-color base0D  #00A0F0;
@define-color base0E  #B000D0;
@define-color base0F  #6A2A3C;
"""

scss_colors = """
$base00: #100510;
$base01: #302030;
$base02: #403040;
$base03: #605060;
$base04: #bbb0bb;
$base05: #ddd0dd;
$base06: #eee0ee;
$base07: #fff0ff;
$base08: #FF1D0D;
$base09: #CCAE14;
$base0A: #F000A0;
$base0B: #14CC64;
$base0C: #0075B0;
$base0D: #00A0F0;
$base0E: #B000D0;
$base0F: #6A2A3C;
"""
