base00 = "101010"
base01 = "454545"
base02 = "454545"
base03 = "454545"
base04 = "808080"
base05 = "C0C0C0"
base06 = "C0C0C0"
base07 = "454545"
base08 = "EFA6A2"
base09 = "A3B8EF"
base0A = "E6A3DC"
base0B = "80C990"
base0C = "C8C874"
base0D = "50CACD"
base0E = "E0AF85"
base0F = "808080"

gtk_colors = """
@define-color base00  #101010;
@define-color base01  #454545;
@define-color base02  #454545;
@define-color base03  #454545;
@define-color base04  #808080;
@define-color base05  #C0C0C0;
@define-color base06  #C0C0C0;
@define-color base07  #454545;
@define-color base08  #EFA6A2;
@define-color base09  #A3B8EF;
@define-color base0A  #E6A3DC;
@define-color base0B  #80C990;
@define-color base0C  #C8C874;
@define-color base0D  #50CACD;
@define-color base0E  #E0AF85;
@define-color base0F  #808080;
"""

scss_colors = """
$base00: #101010;
$base01: #454545;
$base02: #454545;
$base03: #454545;
$base04: #808080;
$base05: #C0C0C0;
$base06: #C0C0C0;
$base07: #454545;
$base08: #EFA6A2;
$base09: #A3B8EF;
$base0A: #E6A3DC;
$base0B: #80C990;
$base0C: #C8C874;
$base0D: #50CACD;
$base0E: #E0AF85;
$base0F: #808080;
"""
