base00 = "faf4ed"
base01 = "fffaf3"
base02 = "f2e9de"
base03 = "9893a5"
base04 = "797593"
base05 = "575279"
base06 = "575279"
base07 = "cecacd"
base08 = "b4637a"
base09 = "ea9d34"
base0A = "d7827e"
base0B = "286983"
base0C = "56949f"
base0D = "907aa9"
base0E = "ea9d34"
base0F = "cecacd"

gtk_colors = """
@define-color base00  #faf4ed;
@define-color base01  #fffaf3;
@define-color base02  #f2e9de;
@define-color base03  #9893a5;
@define-color base04  #797593;
@define-color base05  #575279;
@define-color base06  #575279;
@define-color base07  #cecacd;
@define-color base08  #b4637a;
@define-color base09  #ea9d34;
@define-color base0A  #d7827e;
@define-color base0B  #286983;
@define-color base0C  #56949f;
@define-color base0D  #907aa9;
@define-color base0E  #ea9d34;
@define-color base0F  #cecacd;
"""

scss_colors = """
$base00: #faf4ed;
$base01: #fffaf3;
$base02: #f2e9de;
$base03: #9893a5;
$base04: #797593;
$base05: #575279;
$base06: #575279;
$base07: #cecacd;
$base08: #b4637a;
$base09: #ea9d34;
$base0A: #d7827e;
$base0B: #286983;
$base0C: #56949f;
$base0D: #907aa9;
$base0E: #ea9d34;
$base0F: #cecacd;
"""
