base00 = "ffffff"
base01 = "ebebeb"
base02 = "cdcdcd"
base03 = "878787"
base04 = "878787"
base05 = "474747"
base06 = "282828"
base07 = "282828"
base08 = "bf0000"
base09 = "ba3700"
base0A = "af8500"
base0B = "008400"
base0C = "009a8a"
base0D = "0054cf"
base0E = "6b40c3"
base0F = "dd0f9d"

gtk_colors = """
@define-color base00  #ffffff;
@define-color base01  #ebebeb;
@define-color base02  #cdcdcd;
@define-color base03  #878787;
@define-color base04  #878787;
@define-color base05  #474747;
@define-color base06  #282828;
@define-color base07  #282828;
@define-color base08  #bf0000;
@define-color base09  #ba3700;
@define-color base0A  #af8500;
@define-color base0B  #008400;
@define-color base0C  #009a8a;
@define-color base0D  #0054cf;
@define-color base0E  #6b40c3;
@define-color base0F  #dd0f9d;
"""

scss_colors = """
$base00: #ffffff;
$base01: #ebebeb;
$base02: #cdcdcd;
$base03: #878787;
$base04: #878787;
$base05: #474747;
$base06: #282828;
$base07: #282828;
$base08: #bf0000;
$base09: #ba3700;
$base0A: #af8500;
$base0B: #008400;
$base0C: #009a8a;
$base0D: #0054cf;
$base0E: #6b40c3;
$base0F: #dd0f9d;
"""
