base00 = "181818"
base01 = "252525"
base02 = "3b3b3b"
base03 = "777777"
base04 = "777777"
base05 = "b9b9b9"
base06 = "dedede"
base07 = "dedede"
base08 = "ed4a46"
base09 = "e67f43"
base0A = "dbb32d"
base0B = "70b433"
base0C = "3fc5b7"
base0D = "368aeb"
base0E = "a580e2"
base0F = "eb6eb7"

gtk_colors = """
@define-color base00  #181818;
@define-color base01  #252525;
@define-color base02  #3b3b3b;
@define-color base03  #777777;
@define-color base04  #777777;
@define-color base05  #b9b9b9;
@define-color base06  #dedede;
@define-color base07  #dedede;
@define-color base08  #ed4a46;
@define-color base09  #e67f43;
@define-color base0A  #dbb32d;
@define-color base0B  #70b433;
@define-color base0C  #3fc5b7;
@define-color base0D  #368aeb;
@define-color base0E  #a580e2;
@define-color base0F  #eb6eb7;
"""

scss_colors = """
$base00: #181818;
$base01: #252525;
$base02: #3b3b3b;
$base03: #777777;
$base04: #777777;
$base05: #b9b9b9;
$base06: #dedede;
$base07: #dedede;
$base08: #ed4a46;
$base09: #e67f43;
$base0A: #dbb32d;
$base0B: #70b433;
$base0C: #3fc5b7;
$base0D: #368aeb;
$base0E: #a580e2;
$base0F: #eb6eb7;
"""
