base00 = "fbf3db"
base01 = "ece3cc"
base02 = "d5cdb6"
base03 = "909995"
base04 = "909995"
base05 = "53676d"
base06 = "3a4d53"
base07 = "3a4d53"
base08 = "cc1729"
base09 = "bc5819"
base0A = "a78300"
base0B = "428b00"
base0C = "00978a"
base0D = "006dce"
base0E = "825dc0"
base0F = "c44392"

gtk_colors = """
@define-color base00  #fbf3db;
@define-color base01  #ece3cc;
@define-color base02  #d5cdb6;
@define-color base03  #909995;
@define-color base04  #909995;
@define-color base05  #53676d;
@define-color base06  #3a4d53;
@define-color base07  #3a4d53;
@define-color base08  #cc1729;
@define-color base09  #bc5819;
@define-color base0A  #a78300;
@define-color base0B  #428b00;
@define-color base0C  #00978a;
@define-color base0D  #006dce;
@define-color base0E  #825dc0;
@define-color base0F  #c44392;
"""

scss_colors = """
$base00: #fbf3db;
$base01: #ece3cc;
$base02: #d5cdb6;
$base03: #909995;
$base04: #909995;
$base05: #53676d;
$base06: #3a4d53;
$base07: #3a4d53;
$base08: #cc1729;
$base09: #bc5819;
$base0A: #a78300;
$base0B: #428b00;
$base0C: #00978a;
$base0D: #006dce;
$base0E: #825dc0;
$base0F: #c44392;
"""
