base00 = "151718"
base01 = "282a2b"
base02 = "3B758C"
base03 = "41535B"
base04 = "43a5d5"
base05 = "d6d6d6"
base06 = "eeeeee"
base07 = "ffffff"
base08 = "Cd3f45"
base09 = "db7b55"
base0A = "e6cd69"
base0B = "9fca56"
base0C = "55dbbe"
base0D = "55b5db"
base0E = "a074c4"
base0F = "8a553f"

gtk_colors = """
@define-color base00  #151718;
@define-color base01  #282a2b;
@define-color base02  #3B758C;
@define-color base03  #41535B;
@define-color base04  #43a5d5;
@define-color base05  #d6d6d6;
@define-color base06  #eeeeee;
@define-color base07  #ffffff;
@define-color base08  #Cd3f45;
@define-color base09  #db7b55;
@define-color base0A  #e6cd69;
@define-color base0B  #9fca56;
@define-color base0C  #55dbbe;
@define-color base0D  #55b5db;
@define-color base0E  #a074c4;
@define-color base0F  #8a553f;
"""

scss_colors = """
$base00: #151718;
$base01: #282a2b;
$base02: #3B758C;
$base03: #41535B;
$base04: #43a5d5;
$base05: #d6d6d6;
$base06: #eeeeee;
$base07: #ffffff;
$base08: #Cd3f45;
$base09: #db7b55;
$base0A: #e6cd69;
$base0B: #9fca56;
$base0C: #55dbbe;
$base0D: #55b5db;
$base0E: #a074c4;
$base0F: #8a553f;
"""
