base00 = "232323"
base01 = "1C1C1C"
base02 = "4E4E4E"
base03 = "C0C0C0"
base04 = "E4E4E4"
base05 = "DBDBDB"
base06 = "E4E4E4"
base07 = "1C1C1C"
base08 = "CC5450"
base09 = "A64270"
base0A = "307878"
base0B = "71983B"
base0C = "C57D42"
base0D = "376388"
base0E = "D7AB54"
base0F = "6D6D6D"

gtk_colors = """
@define-color base00  #232323;
@define-color base01  #1C1C1C;
@define-color base02  #4E4E4E;
@define-color base03  #C0C0C0;
@define-color base04  #E4E4E4;
@define-color base05  #DBDBDB;
@define-color base06  #E4E4E4;
@define-color base07  #1C1C1C;
@define-color base08  #CC5450;
@define-color base09  #A64270;
@define-color base0A  #307878;
@define-color base0B  #71983B;
@define-color base0C  #C57D42;
@define-color base0D  #376388;
@define-color base0E  #D7AB54;
@define-color base0F  #6D6D6D;
"""

scss_colors = """
$base00: #232323;
$base01: #1C1C1C;
$base02: #4E4E4E;
$base03: #C0C0C0;
$base04: #E4E4E4;
$base05: #DBDBDB;
$base06: #E4E4E4;
$base07: #1C1C1C;
$base08: #CC5450;
$base09: #A64270;
$base0A: #307878;
$base0B: #71983B;
$base0C: #C57D42;
$base0D: #376388;
$base0E: #D7AB54;
$base0F: #6D6D6D;
"""
