base00 = "1e1e3f"
base01 = "43d426"
base02 = "f1d000"
base03 = "808080"
base04 = "6871ff"
base05 = "c7c7c7"
base06 = "ff77ff"
base07 = "ffffff"
base08 = "d90429"
base09 = "f92a1c"
base0A = "ffe700"
base0B = "3ad900"
base0C = "00c5c7"
base0D = "6943ff"
base0E = "ff2c70"
base0F = "79e8fb"

gtk_colors = """
@define-color base00  #1e1e3f;
@define-color base01  #43d426;
@define-color base02  #f1d000;
@define-color base03  #808080;
@define-color base04  #6871ff;
@define-color base05  #c7c7c7;
@define-color base06  #ff77ff;
@define-color base07  #ffffff;
@define-color base08  #d90429;
@define-color base09  #f92a1c;
@define-color base0A  #ffe700;
@define-color base0B  #3ad900;
@define-color base0C  #00c5c7;
@define-color base0D  #6943ff;
@define-color base0E  #ff2c70;
@define-color base0F  #79e8fb;
"""

scss_colors = """
$base00: #1e1e3f;
$base01: #43d426;
$base02: #f1d000;
$base03: #808080;
$base04: #6871ff;
$base05: #c7c7c7;
$base06: #ff77ff;
$base07: #ffffff;
$base08: #d90429;
$base09: #f92a1c;
$base0A: #ffe700;
$base0B: #3ad900;
$base0C: #00c5c7;
$base0D: #6943ff;
$base0E: #ff2c70;
$base0F: #79e8fb;
"""
