base00 = "f9f9f9"
base01 = "e0e0e0"
base02 = "ababab"
base03 = "555555"
base04 = "343434"
base05 = "102015"
base06 = "040404"
base07 = "000000"
base08 = "e92f2f"
base09 = "e09448"
base0A = "dddd13"
base0B = "0ed839"
base0C = "23edda"
base0D = "3b48e3"
base0E = "f996e2"
base0F = "69542d"

gtk_colors = """
@define-color base00  #f9f9f9;
@define-color base01  #e0e0e0;
@define-color base02  #ababab;
@define-color base03  #555555;
@define-color base04  #343434;
@define-color base05  #102015;
@define-color base06  #040404;
@define-color base07  #000000;
@define-color base08  #e92f2f;
@define-color base09  #e09448;
@define-color base0A  #dddd13;
@define-color base0B  #0ed839;
@define-color base0C  #23edda;
@define-color base0D  #3b48e3;
@define-color base0E  #f996e2;
@define-color base0F  #69542d;
"""

scss_colors = """
$base00: #f9f9f9;
$base01: #e0e0e0;
$base02: #ababab;
$base03: #555555;
$base04: #343434;
$base05: #102015;
$base06: #040404;
$base07: #000000;
$base08: #e92f2f;
$base09: #e09448;
$base0A: #dddd13;
$base0B: #0ed839;
$base0C: #23edda;
$base0D: #3b48e3;
$base0E: #f996e2;
$base0F: #69542d;
"""
