base00 = "0e3c46"
base01 = "1D494E"
base02 = "2A5054"
base03 = "587073"
base04 = "9DC8CD"
base05 = "C7DBDD"
base06 = "CBF2F7"
base07 = "D2FAFF"
base08 = "fb6953"
base09 = "fcab74"
base0A = "fce380"
base0B = "73d8ad"
base0C = "3fb2b9"
base0D = "46bddd"
base0E = "756b8a"
base0F = "9b647b"

gtk_colors = """
@define-color base00  #0e3c46;
@define-color base01  #1D494E;
@define-color base02  #2A5054;
@define-color base03  #587073;
@define-color base04  #9DC8CD;
@define-color base05  #C7DBDD;
@define-color base06  #CBF2F7;
@define-color base07  #D2FAFF;
@define-color base08  #fb6953;
@define-color base09  #fcab74;
@define-color base0A  #fce380;
@define-color base0B  #73d8ad;
@define-color base0C  #3fb2b9;
@define-color base0D  #46bddd;
@define-color base0E  #756b8a;
@define-color base0F  #9b647b;
"""

scss_colors = """
$base00: #0e3c46;
$base01: #1D494E;
$base02: #2A5054;
$base03: #587073;
$base04: #9DC8CD;
$base05: #C7DBDD;
$base06: #CBF2F7;
$base07: #D2FAFF;
$base08: #fb6953;
$base09: #fcab74;
$base0A: #fce380;
$base0B: #73d8ad;
$base0C: #3fb2b9;
$base0D: #46bddd;
$base0E: #756b8a;
$base0F: #9b647b;
"""
