base00 = "E9F1EF"
base01 = "CCD4D3"
base02 = "90B7B6"
base03 = "5C787B"
base04 = "4B5B5F"
base05 = "385156"
base06 = "0e3c46"
base07 = "D2FAFF"
base08 = "CF432E"
base09 = "D27F46"
base0A = "CFAD25"
base0B = "6CA38C"
base0C = "329CA2"
base0D = "39AAC9"
base0E = "6E6582"
base0F = "865369"

gtk_colors = """
@define-color base00  #E9F1EF;
@define-color base01  #CCD4D3;
@define-color base02  #90B7B6;
@define-color base03  #5C787B;
@define-color base04  #4B5B5F;
@define-color base05  #385156;
@define-color base06  #0e3c46;
@define-color base07  #D2FAFF;
@define-color base08  #CF432E;
@define-color base09  #D27F46;
@define-color base0A  #CFAD25;
@define-color base0B  #6CA38C;
@define-color base0C  #329CA2;
@define-color base0D  #39AAC9;
@define-color base0E  #6E6582;
@define-color base0F  #865369;
"""

scss_colors = """
$base00: #E9F1EF;
$base01: #CCD4D3;
$base02: #90B7B6;
$base03: #5C787B;
$base04: #4B5B5F;
$base05: #385156;
$base06: #0e3c46;
$base07: #D2FAFF;
$base08: #CF432E;
$base09: #D27F46;
$base0A: #CFAD25;
$base0B: #6CA38C;
$base0C: #329CA2;
$base0D: #39AAC9;
$base0E: #6E6582;
$base0F: #865369;
"""
