base00 = "282a36"
base01 = "34353e"
base02 = "43454f"
base03 = "78787e"
base04 = "a5a5a9"
base05 = "e2e4e5"
base06 = "eff0eb"
base07 = "f1f1f0"
base08 = "ff5c57"
base09 = "ff9f43"
base0A = "f3f99d"
base0B = "5af78e"
base0C = "9aedfe"
base0D = "57c7ff"
base0E = "ff6ac1"
base0F = "b2643c"

gtk_colors = """
@define-color base00  #282a36;
@define-color base01  #34353e;
@define-color base02  #43454f;
@define-color base03  #78787e;
@define-color base04  #a5a5a9;
@define-color base05  #e2e4e5;
@define-color base06  #eff0eb;
@define-color base07  #f1f1f0;
@define-color base08  #ff5c57;
@define-color base09  #ff9f43;
@define-color base0A  #f3f99d;
@define-color base0B  #5af78e;
@define-color base0C  #9aedfe;
@define-color base0D  #57c7ff;
@define-color base0E  #ff6ac1;
@define-color base0F  #b2643c;
"""

scss_colors = """
$base00: #282a36;
$base01: #34353e;
$base02: #43454f;
$base03: #78787e;
$base04: #a5a5a9;
$base05: #e2e4e5;
$base06: #eff0eb;
$base07: #f1f1f0;
$base08: #ff5c57;
$base09: #ff9f43;
$base0A: #f3f99d;
$base0B: #5af78e;
$base0C: #9aedfe;
$base0D: #57c7ff;
$base0E: #ff6ac1;
$base0F: #b2643c;
"""
