base00 = "18262F"
base01 = "222E38"
base02 = "586875"
base03 = "667581"
base04 = "85939E"
base05 = "A6AFB8"
base06 = "E8E9ED"
base07 = "F5F7FA"
base08 = "EF5253"
base09 = "E66B2B"
base0A = "E4B51C"
base0B = "7CC844"
base0C = "52CBB0"
base0D = "33B5E1"
base0E = "A363D5"
base0F = "D73C9A"

gtk_colors = """
@define-color base00  #18262F;
@define-color base01  #222E38;
@define-color base02  #586875;
@define-color base03  #667581;
@define-color base04  #85939E;
@define-color base05  #A6AFB8;
@define-color base06  #E8E9ED;
@define-color base07  #F5F7FA;
@define-color base08  #EF5253;
@define-color base09  #E66B2B;
@define-color base0A  #E4B51C;
@define-color base0B  #7CC844;
@define-color base0C  #52CBB0;
@define-color base0D  #33B5E1;
@define-color base0E  #A363D5;
@define-color base0F  #D73C9A;
"""

scss_colors = """
$base00: #18262F;
$base01: #222E38;
$base02: #586875;
$base03: #667581;
$base04: #85939E;
$base05: #A6AFB8;
$base06: #E8E9ED;
$base07: #F5F7FA;
$base08: #EF5253;
$base09: #E66B2B;
$base0A: #E4B51C;
$base0B: #7CC844;
$base0C: #52CBB0;
$base0D: #33B5E1;
$base0E: #A363D5;
$base0F: #D73C9A;
"""
