base00 = "222222"
base01 = "303030"
base02 = "555555"
base03 = "898989"
base04 = "898989"
base05 = "c0c0c0"
base06 = "e0e0e0"
base07 = "ffffff"
base08 = "e15d67"
base09 = "fc804e"
base0A = "e1b31a"
base0B = "5db129"
base0C = "21c992"
base0D = "00a3f2"
base0E = "b46ee0"
base0F = "b87d28"

gtk_colors = """
@define-color base00  #222222;
@define-color base01  #303030;
@define-color base02  #555555;
@define-color base03  #898989;
@define-color base04  #898989;
@define-color base05  #c0c0c0;
@define-color base06  #e0e0e0;
@define-color base07  #ffffff;
@define-color base08  #e15d67;
@define-color base09  #fc804e;
@define-color base0A  #e1b31a;
@define-color base0B  #5db129;
@define-color base0C  #21c992;
@define-color base0D  #00a3f2;
@define-color base0E  #b46ee0;
@define-color base0F  #b87d28;
"""

scss_colors = """
$base00: #222222;
$base01: #303030;
$base02: #555555;
$base03: #898989;
$base04: #898989;
$base05: #c0c0c0;
$base06: #e0e0e0;
$base07: #ffffff;
$base08: #e15d67;
$base09: #fc804e;
$base0A: #e1b31a;
$base0B: #5db129;
$base0C: #21c992;
$base0D: #00a3f2;
$base0E: #b46ee0;
$base0F: #b87d28;
"""
