base00 = "2B213C"
base01 = "362B48"
base02 = "4D4160"
base03 = "655978"
base04 = "7F7192"
base05 = "998BAD"
base06 = "B4A5C8"
base07 = "EBDCFF"
base08 = "C79987"
base09 = "8865C6"
base0A = "C7C691"
base0B = "ACC79B"
base0C = "9BC7BF"
base0D = "A5AAD4"
base0E = "C594FF"
base0F = "C7AB87"

gtk_colors = """
@define-color base00  #2B213C;
@define-color base01  #362B48;
@define-color base02  #4D4160;
@define-color base03  #655978;
@define-color base04  #7F7192;
@define-color base05  #998BAD;
@define-color base06  #B4A5C8;
@define-color base07  #EBDCFF;
@define-color base08  #C79987;
@define-color base09  #8865C6;
@define-color base0A  #C7C691;
@define-color base0B  #ACC79B;
@define-color base0C  #9BC7BF;
@define-color base0D  #A5AAD4;
@define-color base0E  #C594FF;
@define-color base0F  #C7AB87;
"""

scss_colors = """
$base00: #2B213C;
$base01: #362B48;
$base02: #4D4160;
$base03: #655978;
$base04: #7F7192;
$base05: #998BAD;
$base06: #B4A5C8;
$base07: #EBDCFF;
$base08: #C79987;
$base09: #8865C6;
$base0A: #C7C691;
$base0B: #ACC79B;
$base0C: #9BC7BF;
$base0D: #A5AAD4;
$base0E: #C594FF;
$base0F: #C7AB87;
"""
