base00 = "F0F0F0"
base01 = "F0D848"
base02 = "FFF018"
base03 = "F01818"
base04 = "F00000"
base05 = "D80000"
base06 = "489000"
base07 = "30A860"
base08 = "487830"
base09 = "183048"
base0A = "426395"
base0B = "5C5C6A"
base0C = "2C3C57"
base0D = "001878"
base0E = "900000"
base0F = "140C0D"

gtk_colors = """
@define-color base00  #F0F0F0;
@define-color base01  #F0D848;
@define-color base02  #FFF018;
@define-color base03  #F01818;
@define-color base04  #F00000;
@define-color base05  #D80000;
@define-color base06  #489000;
@define-color base07  #30A860;
@define-color base08  #487830;
@define-color base09  #183048;
@define-color base0A  #426395;
@define-color base0B  #5C5C6A;
@define-color base0C  #2C3C57;
@define-color base0D  #001878;
@define-color base0E  #900000;
@define-color base0F  #140C0D;
"""

scss_colors = """
$base00: #F0F0F0;
$base01: #F0D848;
$base02: #FFF018;
$base03: #F01818;
$base04: #F00000;
$base05: #D80000;
$base06: #489000;
$base07: #30A860;
$base08: #487830;
$base09: #183048;
$base0A: #426395;
$base0B: #5C5C6A;
$base0C: #2C3C57;
$base0D: #001878;
$base0E: #900000;
$base0F: #140C0D;
"""
