base00 = "1c1810"
base01 = "2a261c"
base02 = "3a3527"
base03 = "504b38"
base04 = "5f5b45"
base05 = "736e55"
base06 = "bab696"
base07 = "f8f5de"
base08 = "e35142"
base09 = "fba11b"
base0A = "f2ff27"
base0B = "5ceb5a"
base0C = "5aebbc"
base0D = "489bf0"
base0E = "FF8080"
base0F = "F69BE7"

gtk_colors = """
@define-color base00  #1c1810;
@define-color base01  #2a261c;
@define-color base02  #3a3527;
@define-color base03  #504b38;
@define-color base04  #5f5b45;
@define-color base05  #736e55;
@define-color base06  #bab696;
@define-color base07  #f8f5de;
@define-color base08  #e35142;
@define-color base09  #fba11b;
@define-color base0A  #f2ff27;
@define-color base0B  #5ceb5a;
@define-color base0C  #5aebbc;
@define-color base0D  #489bf0;
@define-color base0E  #FF8080;
@define-color base0F  #F69BE7;
"""

scss_colors = """
$base00: #1c1810;
$base01: #2a261c;
$base02: #3a3527;
$base03: #504b38;
$base04: #5f5b45;
$base05: #736e55;
$base06: #bab696;
$base07: #f8f5de;
$base08: #e35142;
$base09: #fba11b;
$base0A: #f2ff27;
$base0B: #5ceb5a;
$base0C: #5aebbc;
$base0D: #489bf0;
$base0E: #FF8080;
$base0F: #F69BE7;
"""
