base00 = "dddfe0"
base01 = "cfd1d2"
base02 = "c1c3c4"
base03 = "a3a5a6"
base04 = "474849"
base05 = "28292a"
base06 = "1a1b1c"
base07 = "050608"
base08 = "b53b50"
base09 = "ea770d"
base0A = "c9d364"
base0B = "06ea61"
base0C = "42fff9"
base0D = "03aeff"
base0E = "ea5ce2"
base0F = "cd6320"

gtk_colors = """
@define-color base00  #dddfe0;
@define-color base01  #cfd1d2;
@define-color base02  #c1c3c4;
@define-color base03  #a3a5a6;
@define-color base04  #474849;
@define-color base05  #28292a;
@define-color base06  #1a1b1c;
@define-color base07  #050608;
@define-color base08  #b53b50;
@define-color base09  #ea770d;
@define-color base0A  #c9d364;
@define-color base0B  #06ea61;
@define-color base0C  #42fff9;
@define-color base0D  #03aeff;
@define-color base0E  #ea5ce2;
@define-color base0F  #cd6320;
"""

scss_colors = """
$base00: #dddfe0;
$base01: #cfd1d2;
$base02: #c1c3c4;
$base03: #a3a5a6;
$base04: #474849;
$base05: #28292a;
$base06: #1a1b1c;
$base07: #050608;
$base08: #b53b50;
$base09: #ea770d;
$base0A: #c9d364;
$base0B: #06ea61;
$base0C: #42fff9;
$base0D: #03aeff;
$base0E: #ea5ce2;
$base0F: #cd6320;
"""
