base00 = "2e3436"
base01 = "8ae234"
base02 = "fce94f"
base03 = "555753"
base04 = "729fcf"
base05 = "d3d7cf"
base06 = "ad7fa8"
base07 = "eeeeec"
base08 = "cc0000"
base09 = "ef2929"
base0A = "c4a000"
base0B = "4e9a06"
base0C = "06989a"
base0D = "3465a4"
base0E = "75507b"
base0F = "34e2e2"

gtk_colors = """
@define-color base00  #2e3436;
@define-color base01  #8ae234;
@define-color base02  #fce94f;
@define-color base03  #555753;
@define-color base04  #729fcf;
@define-color base05  #d3d7cf;
@define-color base06  #ad7fa8;
@define-color base07  #eeeeec;
@define-color base08  #cc0000;
@define-color base09  #ef2929;
@define-color base0A  #c4a000;
@define-color base0B  #4e9a06;
@define-color base0C  #06989a;
@define-color base0D  #3465a4;
@define-color base0E  #75507b;
@define-color base0F  #34e2e2;
"""

scss_colors = """
$base00: #2e3436;
$base01: #8ae234;
$base02: #fce94f;
$base03: #555753;
$base04: #729fcf;
$base05: #d3d7cf;
$base06: #ad7fa8;
$base07: #eeeeec;
$base08: #cc0000;
$base09: #ef2929;
$base0A: #c4a000;
$base0B: #4e9a06;
$base0C: #06989a;
$base0D: #3465a4;
$base0E: #75507b;
$base0F: #34e2e2;
"""
