base00 = "0e091d"
base01 = "2a153c"
base02 = "4b2054"
base03 = "74316b"
base04 = "8c406f"
base05 = "aa556f"
base06 = "c4686d"
base07 = "dc8f7c"
base08 = "c53253"
base09 = "ea4d60"
base0A = "ff6565"
base0B = "a68e5a"
base0C = "8c9785"
base0D = "6e6080"
base0E = "a45782"
base0F = "984d51"

gtk_colors = """
@define-color base00  #0e091d;
@define-color base01  #2a153c;
@define-color base02  #4b2054;
@define-color base03  #74316b;
@define-color base04  #8c406f;
@define-color base05  #aa556f;
@define-color base06  #c4686d;
@define-color base07  #dc8f7c;
@define-color base08  #c53253;
@define-color base09  #ea4d60;
@define-color base0A  #ff6565;
@define-color base0B  #a68e5a;
@define-color base0C  #8c9785;
@define-color base0D  #6e6080;
@define-color base0E  #a45782;
@define-color base0F  #984d51;
"""

scss_colors = """
$base00: #0e091d;
$base01: #2a153c;
$base02: #4b2054;
$base03: #74316b;
$base04: #8c406f;
$base05: #aa556f;
$base06: #c4686d;
$base07: #dc8f7c;
$base08: #c53253;
$base09: #ea4d60;
$base0A: #ff6565;
$base0B: #a68e5a;
$base0C: #8c9785;
$base0D: #6e6080;
$base0E: #a45782;
$base0F: #984d51;
"""
