base00 = "282828"
base01 = "383838"
base02 = "484848"
base03 = "4c4c4c"
base04 = "b8b8b8"
base05 = "eeeeee"
base06 = "e8e8e8"
base07 = "feffff"
base08 = "f43753"
base09 = "dc9656"
base0A = "ffc24b"
base0B = "c9d05c"
base0C = "73cef4"
base0D = "b3deef"
base0E = "d3b987"
base0F = "a16946"

gtk_colors = """
@define-color base00  #282828;
@define-color base01  #383838;
@define-color base02  #484848;
@define-color base03  #4c4c4c;
@define-color base04  #b8b8b8;
@define-color base05  #eeeeee;
@define-color base06  #e8e8e8;
@define-color base07  #feffff;
@define-color base08  #f43753;
@define-color base09  #dc9656;
@define-color base0A  #ffc24b;
@define-color base0B  #c9d05c;
@define-color base0C  #73cef4;
@define-color base0D  #b3deef;
@define-color base0E  #d3b987;
@define-color base0F  #a16946;
"""

scss_colors = """
$base00: #282828;
$base01: #383838;
$base02: #484848;
$base03: #4c4c4c;
$base04: #b8b8b8;
$base05: #eeeeee;
$base06: #e8e8e8;
$base07: #feffff;
$base08: #f43753;
$base09: #dc9656;
$base0A: #ffc24b;
$base0B: #c9d05c;
$base0C: #73cef4;
$base0D: #b3deef;
$base0E: #d3b987;
$base0F: #a16946;
"""
