base00 = "11121d"
base01 = "151621"
base02 = "43444f"
base03 = "393a45"
base04 = "1b1c27"
base05 = "abb2bf"
base06 = "555661"
base07 = "2c2d38"
base08 = "a485dd"
base09 = "a485dd"
base0A = "7199ee"
base0B = "d7A65f"
base0C = "a485dd"
base0D = "95c561"
base0E = "ee6d85"
base0F = "773440"

gtk_colors = """
@define-color base00  #11121d;
@define-color base01  #151621;
@define-color base02  #43444f;
@define-color base03  #393a45;
@define-color base04  #1b1c27;
@define-color base05  #abb2bf;
@define-color base06  #555661;
@define-color base07  #2c2d38;
@define-color base08  #a485dd;
@define-color base09  #a485dd;
@define-color base0A  #7199ee;
@define-color base0B  #d7A65f;
@define-color base0C  #a485dd;
@define-color base0D  #95c561;
@define-color base0E  #ee6d85;
@define-color base0F  #773440;
"""

scss_colors = """
$base00: #11121d;
$base01: #151621;
$base02: #43444f;
$base03: #393a45;
$base04: #1b1c27;
$base05: #abb2bf;
$base06: #555661;
$base07: #2c2d38;
$base08: #a485dd;
$base09: #a485dd;
$base0A: #7199ee;
$base0B: #d7A65f;
$base0C: #a485dd;
$base0D: #95c561;
$base0E: #ee6d85;
$base0F: #773440;
"""
