base00 = "FBFBFD"
base01 = "F6F6F8"
base02 = "D8E2EC"
base03 = "B7C5D3"
base04 = "526270"
base05 = "28323A"
base06 = "1D252C"
base07 = "171D23"
base08 = "8C4351"
base09 = "965027"
base0A = "8f5E15"
base0B = "33635C"
base0C = "0F4B6E"
base0D = "34548A"
base0E = "5A4A78"
base0F = "7E5140"

gtk_colors = """
@define-color base00  #FBFBFD;
@define-color base01  #F6F6F8;
@define-color base02  #D8E2EC;
@define-color base03  #B7C5D3;
@define-color base04  #526270;
@define-color base05  #28323A;
@define-color base06  #1D252C;
@define-color base07  #171D23;
@define-color base08  #8C4351;
@define-color base09  #965027;
@define-color base0A  #8f5E15;
@define-color base0B  #33635C;
@define-color base0C  #0F4B6E;
@define-color base0D  #34548A;
@define-color base0E  #5A4A78;
@define-color base0F  #7E5140;
"""

scss_colors = """
$base00: #FBFBFD;
$base01: #F6F6F8;
$base02: #D8E2EC;
$base03: #B7C5D3;
$base04: #526270;
$base05: #28323A;
$base06: #1D252C;
$base07: #171D23;
$base08: #8C4351;
$base09: #965027;
$base0A: #8f5E15;
$base0B: #33635C;
$base0C: #0F4B6E;
$base0D: #34548A;
$base0E: #5A4A78;
$base0F: #7E5140;
"""
