base00 = "FBFBFD"
base01 = "F6F6F8"
base02 = "EDEFF6"
base03 = "9699A3"
base04 = "4c505e"
base05 = "343B59"
base06 = "1D252C"
base07 = "171D23"
base08 = "8C4351"
base09 = "965027"
base0A = "4C505E"
base0B = "485E30"
base0C = "4C505E"
base0D = "34548a"
base0E = "5A4A78"
base0F = "5A4A78"

gtk_colors = """
@define-color base00  #FBFBFD;
@define-color base01  #F6F6F8;
@define-color base02  #EDEFF6;
@define-color base03  #9699A3;
@define-color base04  #4c505e;
@define-color base05  #343B59;
@define-color base06  #1D252C;
@define-color base07  #171D23;
@define-color base08  #8C4351;
@define-color base09  #965027;
@define-color base0A  #4C505E;
@define-color base0B  #485E30;
@define-color base0C  #4C505E;
@define-color base0D  #34548a;
@define-color base0E  #5A4A78;
@define-color base0F  #5A4A78;
"""

scss_colors = """
$base00: #FBFBFD;
$base01: #F6F6F8;
$base02: #EDEFF6;
$base03: #9699A3;
$base04: #4c505e;
$base05: #343B59;
$base06: #1D252C;
$base07: #171D23;
$base08: #8C4351;
$base09: #965027;
$base0A: #4C505E;
$base0B: #485E30;
$base0C: #4C505E;
$base0D: #34548a;
$base0E: #5A4A78;
$base0F: #5A4A78;
"""
