base00 = "24283B"
base01 = "16161E"
base02 = "343A52"
base03 = "444B6A"
base04 = "787C99"
base05 = "A9B1D6"
base06 = "CBCCD1"
base07 = "D5D6DB"
base08 = "C0CAF5"
base09 = "A9B1D6"
base0A = "0DB9D7"
base0B = "9ECE6A"
base0C = "B4F9F8"
base0D = "2AC3DE"
base0E = "BB9AF7"
base0F = "F7768E"

gtk_colors = """
@define-color base00  #24283B;
@define-color base01  #16161E;
@define-color base02  #343A52;
@define-color base03  #444B6A;
@define-color base04  #787C99;
@define-color base05  #A9B1D6;
@define-color base06  #CBCCD1;
@define-color base07  #D5D6DB;
@define-color base08  #C0CAF5;
@define-color base09  #A9B1D6;
@define-color base0A  #0DB9D7;
@define-color base0B  #9ECE6A;
@define-color base0C  #B4F9F8;
@define-color base0D  #2AC3DE;
@define-color base0E  #BB9AF7;
@define-color base0F  #F7768E;
"""

scss_colors = """
$base00: #24283B;
$base01: #16161E;
$base02: #343A52;
$base03: #444B6A;
$base04: #787C99;
$base05: #A9B1D6;
$base06: #CBCCD1;
$base07: #D5D6DB;
$base08: #C0CAF5;
$base09: #A9B1D6;
$base0A: #0DB9D7;
$base0B: #9ECE6A;
$base0C: #B4F9F8;
$base0D: #2AC3DE;
$base0E: #BB9AF7;
$base0F: #F7768E;
"""
