base00 = "11121d"
base01 = "1A1B2A"
base02 = "212234"
base03 = "282c34"
base04 = "4a5057"
base05 = "a0a8cd"
base06 = "a0a8cd"
base07 = "a0a8cd"
base08 = "ee6d85"
base09 = "f6955b"
base0A = "d7a65f"
base0B = "95c561"
base0C = "38a89d"
base0D = "7199ee"
base0E = "a485dd"
base0F = "773440"

gtk_colors = """
@define-color base00  #11121d;
@define-color base01  #1A1B2A;
@define-color base02  #212234;
@define-color base03  #282c34;
@define-color base04  #4a5057;
@define-color base05  #a0a8cd;
@define-color base06  #a0a8cd;
@define-color base07  #a0a8cd;
@define-color base08  #ee6d85;
@define-color base09  #f6955b;
@define-color base0A  #d7a65f;
@define-color base0B  #95c561;
@define-color base0C  #38a89d;
@define-color base0D  #7199ee;
@define-color base0E  #a485dd;
@define-color base0F  #773440;
"""

scss_colors = """
$base00: #11121d;
$base01: #1A1B2A;
$base02: #212234;
$base03: #282c34;
$base04: #4a5057;
$base05: #a0a8cd;
$base06: #a0a8cd;
$base07: #a0a8cd;
$base08: #ee6d85;
$base09: #f6955b;
$base0A: #d7a65f;
$base0B: #95c561;
$base0C: #38a89d;
$base0D: #7199ee;
$base0E: #a485dd;
$base0F: #773440;
"""
