base00 = "2d2d2d"
base01 = "393939"
base02 = "515151"
base03 = "999999"
base04 = "b4b7b4"
base05 = "cccccc"
base06 = "e0e0e0"
base07 = "ffffff"
base08 = "f2777a"
base09 = "f99157"
base0A = "ffcc66"
base0B = "99cc99"
base0C = "66cccc"
base0D = "6699cc"
base0E = "cc99cc"
base0F = "a3685a"

gtk_colors = """
@define-color base00  #2d2d2d;
@define-color base01  #393939;
@define-color base02  #515151;
@define-color base03  #999999;
@define-color base04  #b4b7b4;
@define-color base05  #cccccc;
@define-color base06  #e0e0e0;
@define-color base07  #ffffff;
@define-color base08  #f2777a;
@define-color base09  #f99157;
@define-color base0A  #ffcc66;
@define-color base0B  #99cc99;
@define-color base0C  #66cccc;
@define-color base0D  #6699cc;
@define-color base0E  #cc99cc;
@define-color base0F  #a3685a;
"""

scss_colors = """
$base00: #2d2d2d;
$base01: #393939;
$base02: #515151;
$base03: #999999;
$base04: #b4b7b4;
$base05: #cccccc;
$base06: #e0e0e0;
$base07: #ffffff;
$base08: #f2777a;
$base09: #f99157;
$base0A: #ffcc66;
$base0B: #99cc99;
$base0C: #66cccc;
$base0D: #6699cc;
$base0E: #cc99cc;
$base0F: #a3685a;
"""
