base00 = "231f20"
base01 = "1c3f95"
base02 = "5a5758"
base03 = "737171"
base04 = "959ca1"
base05 = "d9d8d8"
base06 = "e7e7e8"
base07 = "ffffff"
base08 = "ee2e24"
base09 = "f386a1"
base0A = "ffd204"
base0B = "00853e"
base0C = "85cebc"
base0D = "009ddc"
base0E = "98005d"
base0F = "b06110"

gtk_colors = """
@define-color base00  #231f20;
@define-color base01  #1c3f95;
@define-color base02  #5a5758;
@define-color base03  #737171;
@define-color base04  #959ca1;
@define-color base05  #d9d8d8;
@define-color base06  #e7e7e8;
@define-color base07  #ffffff;
@define-color base08  #ee2e24;
@define-color base09  #f386a1;
@define-color base0A  #ffd204;
@define-color base0B  #00853e;
@define-color base0C  #85cebc;
@define-color base0D  #009ddc;
@define-color base0E  #98005d;
@define-color base0F  #b06110;
"""

scss_colors = """
$base00: #231f20;
$base01: #1c3f95;
$base02: #5a5758;
$base03: #737171;
$base04: #959ca1;
$base05: #d9d8d8;
$base06: #e7e7e8;
$base07: #ffffff;
$base08: #ee2e24;
$base09: #f386a1;
$base0A: #ffd204;
$base0B: #00853e;
$base0C: #85cebc;
$base0D: #009ddc;
$base0E: #98005d;
$base0F: #b06110;
"""
