base00 = "2e2a31"
base01 = "4a464d"
base02 = "666369"
base03 = "838085"
base04 = "9f9da2"
base05 = "bcbabe"
base06 = "d8d7da"
base07 = "f5f4f7"
base08 = "d8137f"
base09 = "d65407"
base0A = "dc8a0e"
base0B = "17ad98"
base0C = "149bda"
base0D = "796af5"
base0E = "bb60ea"
base0F = "c720ca"

gtk_colors = """
@define-color base00  #2e2a31;
@define-color base01  #4a464d;
@define-color base02  #666369;
@define-color base03  #838085;
@define-color base04  #9f9da2;
@define-color base05  #bcbabe;
@define-color base06  #d8d7da;
@define-color base07  #f5f4f7;
@define-color base08  #d8137f;
@define-color base09  #d65407;
@define-color base0A  #dc8a0e;
@define-color base0B  #17ad98;
@define-color base0C  #149bda;
@define-color base0D  #796af5;
@define-color base0E  #bb60ea;
@define-color base0F  #c720ca;
"""

scss_colors = """
$base00: #2e2a31;
$base01: #4a464d;
$base02: #666369;
$base03: #838085;
$base04: #9f9da2;
$base05: #bcbabe;
$base06: #d8d7da;
$base07: #f5f4f7;
$base08: #d8137f;
$base09: #d65407;
$base0A: #dc8a0e;
$base0B: #17ad98;
$base0C: #149bda;
$base0D: #796af5;
$base0E: #bb60ea;
$base0F: #c720ca;
"""
