base00 = "241b26"
base01 = "2f2a3f"
base02 = "46354a"
base03 = "6c3cb2"
base04 = "7e5f83"
base05 = "eed5d9"
base06 = "d9c2c6"
base07 = "e4ccd0"
base08 = "877bb6"
base09 = "de5b44"
base0A = "a84a73"
base0B = "c965bf"
base0C = "9c5fce"
base0D = "6a9eb5"
base0E = "78a38f"
base0F = "a3a079"

gtk_colors = """
@define-color base00  #241b26;
@define-color base01  #2f2a3f;
@define-color base02  #46354a;
@define-color base03  #6c3cb2;
@define-color base04  #7e5f83;
@define-color base05  #eed5d9;
@define-color base06  #d9c2c6;
@define-color base07  #e4ccd0;
@define-color base08  #877bb6;
@define-color base09  #de5b44;
@define-color base0A  #a84a73;
@define-color base0B  #c965bf;
@define-color base0C  #9c5fce;
@define-color base0D  #6a9eb5;
@define-color base0E  #78a38f;
@define-color base0F  #a3a079;
"""

scss_colors = """
$base00: #241b26;
$base01: #2f2a3f;
$base02: #46354a;
$base03: #6c3cb2;
$base04: #7e5f83;
$base05: #eed5d9;
$base06: #d9c2c6;
$base07: #e4ccd0;
$base08: #877bb6;
$base09: #de5b44;
$base0A: #a84a73;
$base0B: #c965bf;
$base0C: #9c5fce;
$base0D: #6a9eb5;
$base0E: #78a38f;
$base0F: #a3a079;
"""
