base00 = "041523"
base01 = "122339"
base02 = "003552"
base03 = "7a5759"
base04 = "6b6977"
base05 = "5b778c"
base06 = "333238"
base07 = "214d68"
base08 = "818591"
base09 = "9198a3"
base0A = "adb4b9"
base0B = "977d7c"
base0C = "977d7c"
base0D = "977d7c"
base0E = "9198a3"
base0F = "977d7c"

gtk_colors = """
@define-color base00  #041523;
@define-color base01  #122339;
@define-color base02  #003552;
@define-color base03  #7a5759;
@define-color base04  #6b6977;
@define-color base05  #5b778c;
@define-color base06  #333238;
@define-color base07  #214d68;
@define-color base08  #818591;
@define-color base09  #9198a3;
@define-color base0A  #adb4b9;
@define-color base0B  #977d7c;
@define-color base0C  #977d7c;
@define-color base0D  #977d7c;
@define-color base0E  #9198a3;
@define-color base0F  #977d7c;
"""

scss_colors = """
$base00: #041523;
$base01: #122339;
$base02: #003552;
$base03: #7a5759;
$base04: #6b6977;
$base05: #5b778c;
$base06: #333238;
$base07: #214d68;
$base08: #818591;
$base09: #9198a3;
$base0A: #adb4b9;
$base0B: #977d7c;
$base0C: #977d7c;
$base0D: #977d7c;
$base0E: #9198a3;
$base0F: #977d7c;
"""
