base00 = "0c0c0c"
base01 = "2f2f2f"
base02 = "535353"
base03 = "767676"
base04 = "b9b9b9"
base05 = "cccccc"
base06 = "dfdfdf"
base07 = "f2f2f2"
base08 = "e74856"
base09 = "c19c00"
base0A = "f9f1a5"
base0B = "16c60c"
base0C = "61d6d6"
base0D = "3b78ff"
base0E = "b4009e"
base0F = "13a10e"

gtk_colors = """
@define-color base00  #0c0c0c;
@define-color base01  #2f2f2f;
@define-color base02  #535353;
@define-color base03  #767676;
@define-color base04  #b9b9b9;
@define-color base05  #cccccc;
@define-color base06  #dfdfdf;
@define-color base07  #f2f2f2;
@define-color base08  #e74856;
@define-color base09  #c19c00;
@define-color base0A  #f9f1a5;
@define-color base0B  #16c60c;
@define-color base0C  #61d6d6;
@define-color base0D  #3b78ff;
@define-color base0E  #b4009e;
@define-color base0F  #13a10e;
"""

scss_colors = """
$base00: #0c0c0c;
$base01: #2f2f2f;
$base02: #535353;
$base03: #767676;
$base04: #b9b9b9;
$base05: #cccccc;
$base06: #dfdfdf;
$base07: #f2f2f2;
$base08: #e74856;
$base09: #c19c00;
$base0A: #f9f1a5;
$base0B: #16c60c;
$base0C: #61d6d6;
$base0D: #3b78ff;
$base0E: #b4009e;
$base0F: #13a10e;
"""
