base00 = "fcfcfc"
base01 = "e0e0e0"
base02 = "c4c4c4"
base03 = "a8a8a8"
base04 = "7e7e7e"
base05 = "545454"
base06 = "2a2a2a"
base07 = "000000"
base08 = "a80000"
base09 = "fcfc54"
base0A = "a85400"
base0B = "00a800"
base0C = "00a8a8"
base0D = "0000a8"
base0E = "a800a8"
base0F = "54fc54"

gtk_colors = """
@define-color base00  #fcfcfc;
@define-color base01  #e0e0e0;
@define-color base02  #c4c4c4;
@define-color base03  #a8a8a8;
@define-color base04  #7e7e7e;
@define-color base05  #545454;
@define-color base06  #2a2a2a;
@define-color base07  #000000;
@define-color base08  #a80000;
@define-color base09  #fcfc54;
@define-color base0A  #a85400;
@define-color base0B  #00a800;
@define-color base0C  #00a8a8;
@define-color base0D  #0000a8;
@define-color base0E  #a800a8;
@define-color base0F  #54fc54;
"""

scss_colors = """
$base00: #fcfcfc;
$base01: #e0e0e0;
$base02: #c4c4c4;
$base03: #a8a8a8;
$base04: #7e7e7e;
$base05: #545454;
$base06: #2a2a2a;
$base07: #000000;
$base08: #a80000;
$base09: #fcfc54;
$base0A: #a85400;
$base0B: #00a800;
$base0C: #00a8a8;
$base0D: #0000a8;
$base0E: #a800a8;
$base0F: #54fc54;
"""
