base00 = "fcfcfc"
base01 = "e8e8e8"
base02 = "d4d4d4"
base03 = "c0c0c0"
base04 = "7e7e7e"
base05 = "545454"
base06 = "2a2a2a"
base07 = "000000"
base08 = "800000"
base09 = "fcfc54"
base0A = "808000"
base0B = "008000"
base0C = "008080"
base0D = "000080"
base0E = "800080"
base0F = "54fc54"

gtk_colors = """
@define-color base00  #fcfcfc;
@define-color base01  #e8e8e8;
@define-color base02  #d4d4d4;
@define-color base03  #c0c0c0;
@define-color base04  #7e7e7e;
@define-color base05  #545454;
@define-color base06  #2a2a2a;
@define-color base07  #000000;
@define-color base08  #800000;
@define-color base09  #fcfc54;
@define-color base0A  #808000;
@define-color base0B  #008000;
@define-color base0C  #008080;
@define-color base0D  #000080;
@define-color base0E  #800080;
@define-color base0F  #54fc54;
"""

scss_colors = """
$base00: #fcfcfc;
$base01: #e8e8e8;
$base02: #d4d4d4;
$base03: #c0c0c0;
$base04: #7e7e7e;
$base05: #545454;
$base06: #2a2a2a;
$base07: #000000;
$base08: #800000;
$base09: #fcfc54;
$base0A: #808000;
$base0B: #008000;
$base0C: #008080;
$base0D: #000080;
$base0E: #800080;
$base0F: #54fc54;
"""
