base00 = "000000"
base01 = "2a2a2a"
base02 = "555555"
base03 = "808080"
base04 = "a1a1a1"
base05 = "c0c0c0"
base06 = "e0e0e0"
base07 = "ffffff"
base08 = "ff0000"
base09 = "808000"
base0A = "ffff00"
base0B = "00ff00"
base0C = "00ffff"
base0D = "0000ff"
base0E = "ff00ff"
base0F = "008000"

gtk_colors = """
@define-color base00  #000000;
@define-color base01  #2a2a2a;
@define-color base02  #555555;
@define-color base03  #808080;
@define-color base04  #a1a1a1;
@define-color base05  #c0c0c0;
@define-color base06  #e0e0e0;
@define-color base07  #ffffff;
@define-color base08  #ff0000;
@define-color base09  #808000;
@define-color base0A  #ffff00;
@define-color base0B  #00ff00;
@define-color base0C  #00ffff;
@define-color base0D  #0000ff;
@define-color base0E  #ff00ff;
@define-color base0F  #008000;
"""

scss_colors = """
$base00: #000000;
$base01: #2a2a2a;
$base02: #555555;
$base03: #808080;
$base04: #a1a1a1;
$base05: #c0c0c0;
$base06: #e0e0e0;
$base07: #ffffff;
$base08: #ff0000;
$base09: #808000;
$base0A: #ffff00;
$base0B: #00ff00;
$base0C: #00ffff;
$base0D: #0000ff;
$base0E: #ff00ff;
$base0F: #008000;
"""
