base00 = "231e18"
base01 = "302b25"
base02 = "48413a"
base03 = "9d8b70"
base04 = "b4a490"
base05 = "cabcb1"
base06 = "d7c8bc"
base07 = "e4d4c8"
base08 = "d35c5c"
base09 = "ca7f32"
base0A = "e0ac16"
base0B = "b7ba53"
base0C = "6eb958"
base0D = "88a4d3"
base0E = "bb90e2"
base0F = "b49368"

gtk_colors = """
@define-color base00  #231e18;
@define-color base01  #302b25;
@define-color base02  #48413a;
@define-color base03  #9d8b70;
@define-color base04  #b4a490;
@define-color base05  #cabcb1;
@define-color base06  #d7c8bc;
@define-color base07  #e4d4c8;
@define-color base08  #d35c5c;
@define-color base09  #ca7f32;
@define-color base0A  #e0ac16;
@define-color base0B  #b7ba53;
@define-color base0C  #6eb958;
@define-color base0D  #88a4d3;
@define-color base0E  #bb90e2;
@define-color base0F  #b49368;
"""

scss_colors = """
$base00: #231e18;
$base01: #302b25;
$base02: #48413a;
$base03: #9d8b70;
$base04: #b4a490;
$base05: #cabcb1;
$base06: #d7c8bc;
$base07: #e4d4c8;
$base08: #d35c5c;
$base09: #ca7f32;
$base0A: #e0ac16;
$base0B: #b7ba53;
$base0C: #6eb958;
$base0D: #88a4d3;
$base0E: #bb90e2;
$base0F: #b49368;
"""
