base00 = "282B35"
base01 = "3D4048"
base02 = "53555D"
base03 = "686A71"
base04 = "7E8086"
base05 = "939599"
base06 = "A9AAAE"
base07 = "BEBFC2"
base08 = "B21889"
base09 = "786DC5"
base0A = "438288"
base0B = "DF0002"
base0C = "00A0BE"
base0D = "790EAD"
base0E = "B21889"
base0F = "C77C48"

gtk_colors = """
@define-color base00  #282B35;
@define-color base01  #3D4048;
@define-color base02  #53555D;
@define-color base03  #686A71;
@define-color base04  #7E8086;
@define-color base05  #939599;
@define-color base06  #A9AAAE;
@define-color base07  #BEBFC2;
@define-color base08  #B21889;
@define-color base09  #786DC5;
@define-color base0A  #438288;
@define-color base0B  #DF0002;
@define-color base0C  #00A0BE;
@define-color base0D  #790EAD;
@define-color base0E  #B21889;
@define-color base0F  #C77C48;
"""

scss_colors = """
$base00: #282B35;
$base01: #3D4048;
$base02: #53555D;
$base03: #686A71;
$base04: #7E8086;
$base05: #939599;
$base06: #A9AAAE;
$base07: #BEBFC2;
$base08: #B21889;
$base09: #786DC5;
$base0A: #438288;
$base0B: #DF0002;
$base0C: #00A0BE;
$base0D: #790EAD;
$base0E: #B21889;
$base0F: #C77C48;
"""
