base00 = "191919"
base01 = "DE6E7C"
base02 = "819B69"
base03 = "B77E64"
base04 = "6099C0"
base05 = "B279A7"
base06 = "66A5AD"
base07 = "BBBBBB"
base08 = "3D3839"
base09 = "E8838F"
base0A = "8BAE68"
base0B = "D68C67"
base0C = "61ABDA"
base0D = "CF86C1"
base0E = "65B8C1"
base0F = "8E8E8E"

gtk_colors = """
@define-color base00  #191919;
@define-color base01  #DE6E7C;
@define-color base02  #819B69;
@define-color base03  #B77E64;
@define-color base04  #6099C0;
@define-color base05  #B279A7;
@define-color base06  #66A5AD;
@define-color base07  #BBBBBB;
@define-color base08  #3D3839;
@define-color base09  #E8838F;
@define-color base0A  #8BAE68;
@define-color base0B  #D68C67;
@define-color base0C  #61ABDA;
@define-color base0D  #CF86C1;
@define-color base0E  #65B8C1;
@define-color base0F  #8E8E8E;
"""

scss_colors = """
$base00: #191919;
$base01: #DE6E7C;
$base02: #819B69;
$base03: #B77E64;
$base04: #6099C0;
$base05: #B279A7;
$base06: #66A5AD;
$base07: #BBBBBB;
$base08: #3D3839;
$base09: #E8838F;
$base0A: #8BAE68;
$base0B: #D68C67;
$base0C: #61ABDA;
$base0D: #CF86C1;
$base0E: #65B8C1;
$base0F: #8E8E8E;
"""
