base00 = "383838"
base01 = "404040"
base02 = "606060"
base03 = "6f6f6f"
base04 = "808080"
base05 = "dcdccc"
base06 = "c0c0c0"
base07 = "ffffff"
base08 = "dca3a3"
base09 = "dfaf8f"
base0A = "e0cf9f"
base0B = "5f7f5f"
base0C = "93e0e3"
base0D = "7cb8bb"
base0E = "dc8cc3"
base0F = "000000"

gtk_colors = """
@define-color base00  #383838;
@define-color base01  #404040;
@define-color base02  #606060;
@define-color base03  #6f6f6f;
@define-color base04  #808080;
@define-color base05  #dcdccc;
@define-color base06  #c0c0c0;
@define-color base07  #ffffff;
@define-color base08  #dca3a3;
@define-color base09  #dfaf8f;
@define-color base0A  #e0cf9f;
@define-color base0B  #5f7f5f;
@define-color base0C  #93e0e3;
@define-color base0D  #7cb8bb;
@define-color base0E  #dc8cc3;
@define-color base0F  #000000;
"""

scss_colors = """
$base00: #383838;
$base01: #404040;
$base02: #606060;
$base03: #6f6f6f;
$base04: #808080;
$base05: #dcdccc;
$base06: #c0c0c0;
$base07: #ffffff;
$base08: #dca3a3;
$base09: #dfaf8f;
$base0A: #e0cf9f;
$base0B: #5f7f5f;
$base0C: #93e0e3;
$base0D: #7cb8bb;
$base0E: #dc8cc3;
$base0F: #000000;
"""
