[profiles]
# Device profiles
laptop = { vars = ["profiles/vars/laptop.toml"] }
desktop = { vars = ["profiles/vars/desktop.toml"] }

# Theme profiles
3024 = { vars = ["profiles/themes/3024.toml"] }
apathy = { vars = ["profiles/themes/apathy.toml"] }
apprentice = { vars = ["profiles/themes/apprentice.toml"] }
ashes = { vars = ["profiles/themes/ashes.toml"] }
atelier-cave-light = { vars = ["profiles/themes/atelier-cave-light.toml"] }
atelier-cave = { vars = ["profiles/themes/atelier-cave.toml"] }
atelier-dune-light = { vars = ["profiles/themes/atelier-dune-light.toml"] }
atelier-dune = { vars = ["profiles/themes/atelier-dune.toml"] }
atelier-estuary-light = { vars = ["profiles/themes/atelier-estuary-light.toml"] }
atelier-estuary = { vars = ["profiles/themes/atelier-estuary.toml"] }
atelier-forest-light = { vars = ["profiles/themes/atelier-forest-light.toml"] }
atelier-forest = { vars = ["profiles/themes/atelier-forest.toml"] }
atelier-heath-light = { vars = ["profiles/themes/atelier-heath-light.toml"] }
atelier-heath = { vars = ["profiles/themes/atelier-heath.toml"] }
atelier-lakeside-light = { vars = ["profiles/themes/atelier-lakeside-light.toml"] }
atelier-lakeside = { vars = ["profiles/themes/atelier-lakeside.toml"] }
atelier-plateau-light = { vars = ["profiles/themes/atelier-plateau-light.toml"] }
atelier-plateau = { vars = ["profiles/themes/atelier-plateau.toml"] }
atelier-savanna-light = { vars = ["profiles/themes/atelier-savanna-light.toml"] }
atelier-savanna = { vars = ["profiles/themes/atelier-savanna.toml"] }
atelier-seaside-light = { vars = ["profiles/themes/atelier-seaside-light.toml"] }
atelier-seaside = { vars = ["profiles/themes/atelier-seaside.toml"] }
atelier-sulphurpool-light = { vars = ["profiles/themes/atelier-sulphurpool-light.toml"] }
atelier-sulphurpool = { vars = ["profiles/themes/atelier-sulphurpool.toml"] }
atlas = { vars = ["profiles/themes/atlas.toml"] }
ayu-dark = { vars = ["profiles/themes/ayu-dark.toml"] }
ayu-light = { vars = ["profiles/themes/ayu-light.toml"] }
ayu-mirage = { vars = ["profiles/themes/ayu-mirage.toml"] }
bespin = { vars = ["profiles/themes/bespin.toml"] }
black-metal-bathory = { vars = ["profiles/themes/black-metal-bathory.toml"] }
black-metal-burzum = { vars = ["profiles/themes/black-metal-burzum.toml"] }
black-metal-dark-funeral = { vars = ["profiles/themes/black-metal-dark-funeral.toml"] }
black-metal-gorgoroth = { vars = ["profiles/themes/black-metal-gorgoroth.toml"] }
black-metal-immortal = { vars = ["profiles/themes/black-metal-immortal.toml"] }
black-metal-khold = { vars = ["profiles/themes/black-metal-khold.toml"] }
black-metal-marduk = { vars = ["profiles/themes/black-metal-marduk.toml"] }
black-metal-mayhem = { vars = ["profiles/themes/black-metal-mayhem.toml"] }
black-metal-nile = { vars = ["profiles/themes/black-metal-nile.toml"] }
black-metal = { vars = ["profiles/themes/black-metal.toml"] }
black-metal-venom = { vars = ["profiles/themes/black-metal-venom.toml"] }
blueforest = { vars = ["profiles/themes/blueforest.toml"] }
blueish = { vars = ["profiles/themes/blueish.toml"] }
brewer = { vars = ["profiles/themes/brewer.toml"] }
bright = { vars = ["profiles/themes/bright.toml"] }
brogrammer = { vars = ["profiles/themes/brogrammer.toml"] }
brushtrees-dark = { vars = ["profiles/themes/brushtrees-dark.toml"] }
brushtrees = { vars = ["profiles/themes/brushtrees.toml"] }
caroline = { vars = ["profiles/themes/caroline.toml"] }
catppuccin-frappe = { vars = ["profiles/themes/catppuccin-frappe.toml"] }
catppuccin-latte = { vars = ["profiles/themes/catppuccin-latte.toml"] }
catppuccin-macchiato = { vars = ["profiles/themes/catppuccin-macchiato.toml"] }
catppuccin-mocha = { vars = ["profiles/themes/catppuccin-mocha.toml"] }
chalk = { vars = ["profiles/themes/chalk.toml"] }
circus = { vars = ["profiles/themes/circus.toml"] }
classic-dark = { vars = ["profiles/themes/classic-dark.toml"] }
classic-light = { vars = ["profiles/themes/classic-light.toml"] }
codeschool = { vars = ["profiles/themes/codeschool.toml"] }
colors = { vars = ["profiles/themes/colors.toml"] }
cupcake = { vars = ["profiles/themes/cupcake.toml"] }
cupertino = { vars = ["profiles/themes/cupertino.toml"] }
danqing-light = { vars = ["profiles/themes/danqing-light.toml"] }
danqing = { vars = ["profiles/themes/danqing.toml"] }
da-one-black = { vars = ["profiles/themes/da-one-black.toml"] }
da-one-gray = { vars = ["profiles/themes/da-one-gray.toml"] }
da-one-ocean = { vars = ["profiles/themes/da-one-ocean.toml"] }
da-one-paper = { vars = ["profiles/themes/da-one-paper.toml"] }
da-one-sea = { vars = ["profiles/themes/da-one-sea.toml"] }
da-one-white = { vars = ["profiles/themes/da-one-white.toml"] }
darcula = { vars = ["profiles/themes/darcula.toml"] }
darkmoss = { vars = ["profiles/themes/darkmoss.toml"] }
darktooth = { vars = ["profiles/themes/darktooth.toml"] }
darkviolet = { vars = ["profiles/themes/darkviolet.toml"] }
decaf = { vars = ["profiles/themes/decaf.toml"] }
default-dark = { vars = ["profiles/themes/default-dark.toml"] }
default-light = { vars = ["profiles/themes/default-light.toml"] }
dirtysea = { vars = ["profiles/themes/dirtysea.toml"] }
dracula = { vars = ["profiles/themes/dracula.toml"] }
edge-dark = { vars = ["profiles/themes/edge-dark.toml"] }
edge-light = { vars = ["profiles/themes/edge-light.toml"] }
eighties = { vars = ["profiles/themes/eighties.toml"] }
embers = { vars = ["profiles/themes/embers.toml"] }
emil = { vars = ["profiles/themes/emil.toml"] }
equilibrium-dark = { vars = ["profiles/themes/equilibrium-dark.toml"] }
equilibrium-gray-dark = { vars = ["profiles/themes/equilibrium-gray-dark.toml"] }
equilibrium-gray-light = { vars = ["profiles/themes/equilibrium-gray-light.toml"] }
equilibrium-light = { vars = ["profiles/themes/equilibrium-light.toml"] }
eris = { vars = ["profiles/themes/eris.toml"] }
espresso = { vars = ["profiles/themes/espresso.toml"] }
eva-dim = { vars = ["profiles/themes/eva-dim.toml"] }
eva = { vars = ["profiles/themes/eva.toml"] }
evenok-dark = { vars = ["profiles/themes/evenok-dark.toml"] }
everforest-dark-hard = { vars = ["profiles/themes/everforest-dark-hard.toml"] }
everforest = { vars = ["profiles/themes/everforest.toml"] }
flat = { vars = ["profiles/themes/flat.toml"] }
framer = { vars = ["profiles/themes/framer.toml"] }
fruit-soda = { vars = ["profiles/themes/fruit-soda.toml"] }
gigavolt = { vars = ["profiles/themes/gigavolt.toml"] }
github = { vars = ["profiles/themes/github.toml"] }
google-dark = { vars = ["profiles/themes/google-dark.toml"] }
google-light = { vars = ["profiles/themes/google-light.toml"] }
gotham = { vars = ["profiles/themes/gotham.toml"] }
grayscale-dark = { vars = ["profiles/themes/grayscale-dark.toml"] }
grayscale-light = { vars = ["profiles/themes/grayscale-light.toml"] }
greenscreen = { vars = ["profiles/themes/greenscreen.toml"] }
gruber = { vars = ["profiles/themes/gruber.toml"] }
gruvbox-dark-hard = { vars = ["profiles/themes/gruvbox-dark-hard.toml"] }
gruvbox-dark-medium = { vars = ["profiles/themes/gruvbox-dark-medium.toml"] }
gruvbox-dark-pale = { vars = ["profiles/themes/gruvbox-dark-pale.toml"] }
gruvbox-dark-soft = { vars = ["profiles/themes/gruvbox-dark-soft.toml"] }
gruvbox-light-hard = { vars = ["profiles/themes/gruvbox-light-hard.toml"] }
gruvbox-light-medium = { vars = ["profiles/themes/gruvbox-light-medium.toml"] }
gruvbox-light-soft = { vars = ["profiles/themes/gruvbox-light-soft.toml"] }
gruvbox-material-dark-hard = { vars = ["profiles/themes/gruvbox-material-dark-hard.toml"] }
gruvbox-material-dark-medium = { vars = ["profiles/themes/gruvbox-material-dark-medium.toml"] }
gruvbox-material-dark-soft = { vars = ["profiles/themes/gruvbox-material-dark-soft.toml"] }
gruvbox-material-light-hard = { vars = ["profiles/themes/gruvbox-material-light-hard.toml"] }
gruvbox-material-light-medium = { vars = ["profiles/themes/gruvbox-material-light-medium.toml"] }
gruvbox-material-light-soft = { vars = ["profiles/themes/gruvbox-material-light-soft.toml"] }
hardcore = { vars = ["profiles/themes/hardcore.toml"] }
harmonic16-dark = { vars = ["profiles/themes/harmonic16-dark.toml"] }
harmonic16-light = { vars = ["profiles/themes/harmonic16-light.toml"] }
heetch-light = { vars = ["profiles/themes/heetch-light.toml"] }
heetch = { vars = ["profiles/themes/heetch.toml"] }
helios = { vars = ["profiles/themes/helios.toml"] }
hopscotch = { vars = ["profiles/themes/hopscotch.toml"] }
horizon-dark = { vars = ["profiles/themes/horizon-dark.toml"] }
horizon-light = { vars = ["profiles/themes/horizon-light.toml"] }
horizon-terminal-dark = { vars = ["profiles/themes/horizon-terminal-dark.toml"] }
horizon-terminal-light = { vars = ["profiles/themes/horizon-terminal-light.toml"] }
humanoid-dark = { vars = ["profiles/themes/humanoid-dark.toml"] }
humanoid-light = { vars = ["profiles/themes/humanoid-light.toml"] }
ia-dark = { vars = ["profiles/themes/ia-dark.toml"] }
ia-light = { vars = ["profiles/themes/ia-light.toml"] }
icy = { vars = ["profiles/themes/icy.toml"] }
irblack = { vars = ["profiles/themes/irblack.toml"] }
isotope = { vars = ["profiles/themes/isotope.toml"] }
kanagawa = { vars = ["profiles/themes/kanagawa.toml"] }
katy = { vars = ["profiles/themes/katy.toml"] }
kimber = { vars = ["profiles/themes/kimber.toml"] }
lime = { vars = ["profiles/themes/lime.toml"] }
macintosh = { vars = ["profiles/themes/macintosh.toml"] }
marrakesh = { vars = ["profiles/themes/marrakesh.toml"] }
material-darker = { vars = ["profiles/themes/material-darker.toml"] }
material-lighter = { vars = ["profiles/themes/material-lighter.toml"] }
material-palenight = { vars = ["profiles/themes/material-palenight.toml"] }
material = { vars = ["profiles/themes/material.toml"] }
material-vivid = { vars = ["profiles/themes/material-vivid.toml"] }
materia = { vars = ["profiles/themes/materia.toml"] }
mellow-purple = { vars = ["profiles/themes/mellow-purple.toml"] }
mexico-light = { vars = ["profiles/themes/mexico-light.toml"] }
mocha = { vars = ["profiles/themes/mocha.toml"] }
monokai = { vars = ["profiles/themes/monokai.toml"] }
mountain = { vars = ["profiles/themes/mountain.toml"] }
nebula = { vars = ["profiles/themes/nebula.toml"] }
nord = { vars = ["profiles/themes/nord.toml"] }
nova = { vars = ["profiles/themes/nova.toml"] }
oceanicnext = { vars = ["profiles/themes/oceanicnext.toml"] }
ocean = { vars = ["profiles/themes/ocean.toml"] }
onedark = { vars = ["profiles/themes/onedark.toml"] }
one-light = { vars = ["profiles/themes/one-light.toml"] }
outrun-dark = { vars = ["profiles/themes/outrun-dark.toml"] }
oxocarbon-dark = { vars = ["profiles/themes/oxocarbon-dark.toml"] }
oxocarbon-light = { vars = ["profiles/themes/oxocarbon-light.toml"] }
pandora = { vars = ["profiles/themes/pandora.toml"] }
papercolor-dark = { vars = ["profiles/themes/papercolor-dark.toml"] }
papercolor-light = { vars = ["profiles/themes/papercolor-light.toml"] }
paraiso = { vars = ["profiles/themes/paraiso.toml"] }
pasque = { vars = ["profiles/themes/pasque.toml"] }
phd = { vars = ["profiles/themes/phd.toml"] }
pico = { vars = ["profiles/themes/pico.toml"] }
pinky = { vars = ["profiles/themes/pinky.toml"] }
pop = { vars = ["profiles/themes/pop.toml"] }
porple = { vars = ["profiles/themes/porple.toml"] }
primer-dark-dimmed = { vars = ["profiles/themes/primer-dark-dimmed.toml"] }
primer-dark = { vars = ["profiles/themes/primer-dark.toml"] }
primer-light = { vars = ["profiles/themes/primer-light.toml"] }
purpledream = { vars = ["profiles/themes/purpledream.toml"] }
qualia = { vars = ["profiles/themes/qualia.toml"] }
railscasts = { vars = ["profiles/themes/railscasts.toml"] }
rebecca = { vars = ["profiles/themes/rebecca.toml"] }
rose-pine-dawn = { vars = ["profiles/themes/rose-pine-dawn.toml"] }
rose-pine-moon = { vars = ["profiles/themes/rose-pine-moon.toml"] }
rose-pine = { vars = ["profiles/themes/rose-pine.toml"] }
sagelight = { vars = ["profiles/themes/sagelight.toml"] }
sakura = { vars = ["profiles/themes/sakura.toml"] }
sandcastle = { vars = ["profiles/themes/sandcastle.toml"] }
selenized-black = { vars = ["profiles/themes/selenized-black.toml"] }
selenized-dark = { vars = ["profiles/themes/selenized-dark.toml"] }
selenized-light = { vars = ["profiles/themes/selenized-light.toml"] }
selenized-white = { vars = ["profiles/themes/selenized-white.toml"] }
seti = { vars = ["profiles/themes/seti.toml"] }
shadesmear-dark = { vars = ["profiles/themes/shadesmear-dark.toml"] }
shadesmear-light = { vars = ["profiles/themes/shadesmear-light.toml"] }
shades-of-purple = { vars = ["profiles/themes/shades-of-purple.toml"] }
shapeshifter = { vars = ["profiles/themes/shapeshifter.toml"] }
silk-dark = { vars = ["profiles/themes/silk-dark.toml"] }
silk-light = { vars = ["profiles/themes/silk-light.toml"] }
snazzy = { vars = ["profiles/themes/snazzy.toml"] }
solarflare-light = { vars = ["profiles/themes/solarflare-light.toml"] }
solarflare = { vars = ["profiles/themes/solarflare.toml"] }
solarized-dark = { vars = ["profiles/themes/solarized-dark.toml"] }
solarized-light = { vars = ["profiles/themes/solarized-light.toml"] }
spaceduck = { vars = ["profiles/themes/spaceduck.toml"] }
spacemacs = { vars = ["profiles/themes/spacemacs.toml"] }
standardized-dark = { vars = ["profiles/themes/standardized-dark.toml"] }
standardized-light = { vars = ["profiles/themes/standardized-light.toml"] }
stella = { vars = ["profiles/themes/stella.toml"] }
still-alive = { vars = ["profiles/themes/still-alive.toml"] }
summercamp = { vars = ["profiles/themes/summercamp.toml"] }
summerfruit-dark = { vars = ["profiles/themes/summerfruit-dark.toml"] }
summerfruit-light = { vars = ["profiles/themes/summerfruit-light.toml"] }
synth-midnight-dark = { vars = ["profiles/themes/synth-midnight-dark.toml"] }
synth-midnight-light = { vars = ["profiles/themes/synth-midnight-light.toml"] }
tango = { vars = ["profiles/themes/tango.toml"] }
tarot = { vars = ["profiles/themes/tarot.toml"] }
tender = { vars = ["profiles/themes/tender.toml"] }
tokyo-city-dark = { vars = ["profiles/themes/tokyo-city-dark.toml"] }
tokyo-city-light = { vars = ["profiles/themes/tokyo-city-light.toml"] }
tokyo-city-terminal-dark = { vars = ["profiles/themes/tokyo-city-terminal-dark.toml"] }
tokyo-city-terminal-light = { vars = ["profiles/themes/tokyo-city-terminal-light.toml"] }
tokyodark-terminal = { vars = ["profiles/themes/tokyodark-terminal.toml"] }
tokyodark = { vars = ["profiles/themes/tokyodark.toml"] }
tokyo-night-dark = { vars = ["profiles/themes/tokyo-night-dark.toml"] }
tokyo-night-light = { vars = ["profiles/themes/tokyo-night-light.toml"] }
tokyo-night-storm = { vars = ["profiles/themes/tokyo-night-storm.toml"] }
tokyo-night-terminal-dark = { vars = ["profiles/themes/tokyo-night-terminal-dark.toml"] }
tokyo-night-terminal-light = { vars = ["profiles/themes/tokyo-night-terminal-light.toml"] }
tokyo-night-terminal-storm = { vars = ["profiles/themes/tokyo-night-terminal-storm.toml"] }
tomorrow-night-eighties = { vars = ["profiles/themes/tomorrow-night-eighties.toml"] }
tomorrow-night = { vars = ["profiles/themes/tomorrow-night.toml"] }
tomorrow = { vars = ["profiles/themes/tomorrow.toml"] }
tube = { vars = ["profiles/themes/tube.toml"] }
twilight = { vars = ["profiles/themes/twilight.toml"] }
unikitty-dark = { vars = ["profiles/themes/unikitty-dark.toml"] }
unikitty-light = { vars = ["profiles/themes/unikitty-light.toml"] }
unikitty-reversible = { vars = ["profiles/themes/unikitty-reversible.toml"] }
uwunicorn = { vars = ["profiles/themes/uwunicorn.toml"] }
vice = { vars = ["profiles/themes/vice.toml"] }
vulcan = { vars = ["profiles/themes/vulcan.toml"] }
windows-10-light = { vars = ["profiles/themes/windows-10-light.toml"] }
windows-10 = { vars = ["profiles/themes/windows-10.toml"] }
windows-95-light = { vars = ["profiles/themes/windows-95-light.toml"] }
windows-95 = { vars = ["profiles/themes/windows-95.toml"] }
windows-highcontrast-light = { vars = ["profiles/themes/windows-highcontrast-light.toml"] }
windows-highcontrast = { vars = ["profiles/themes/windows-highcontrast.toml"] }
windows-nt-light = { vars = ["profiles/themes/windows-nt-light.toml"] }
windows-nt = { vars = ["profiles/themes/windows-nt.toml"] }
woodland = { vars = ["profiles/themes/woodland.toml"] }
xcode-dusk = { vars = ["profiles/themes/xcode-dusk.toml"] }
zenbones = { vars = ["profiles/themes/zenbones.toml"] }
zenburn = { vars = ["profiles/themes/zenburn.toml"] }