battery = "/sys/class/power_supply/BAT0"

[desktop]
overview = "/home/okno/dotfiles/assets/wallpapers/darkforest-ultrawide.jpg"
wallpaper = "/home/okno/dotfiles/assets/wallpapers/stock-mountain.jpg"

[niri]
gaps = 5
focusring_width = 1
struts = { bottom = 5, top = 5 }

[editor]
fontsize = 16

[bar]
iconsize = 22
tray_iconsize = 22
