[package]
name = "pico16"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
dirs = "6.0.0"
image = "0.25.6"
kmeans_colors = "0.7.0"
palette = "0.7.6"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
